### ISSUE TITLE
Many cases of "Exception in thread "AWT-EventQueue-0 @coroutine#5" java.lang.NullPointerException" in Compose desktop

### ISSUE THREAD

**Issue by ArTemmey** [JetBrains/compose-multiplatform#1242]
Hello everyone! I'm stuck in development with Compose for desktop because of the following exception:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at androidx.compose.ui.platform.SkiaLayer.isInLayer-k-4lQ0M(SkiaLayer.desktop.kt:128)
	at androidx.compose.ui.node.LayoutNodeWrapper.withinLayerBounds-3MmeM6k(LayoutNodeWrapper.kt:639)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:77)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.LayoutNode.hitTest-9KIMszo$ui(LayoutNode.kt:846)
	at androidx.compose.ui.node.InnerPlaceable.hitTest-9KIMszo(InnerPlaceable.kt:146)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.hitTest-9KIMszo(DelegatingLayoutNodeWrapper.kt:79)
	at androidx.compose.ui.node.LayoutNode.hitTest-9KIMszo$ui(LayoutNode.kt:846)
	at androidx.compose.ui.node.LayoutNode.hitTest-9KIMszo$ui$default(LayoutNode.kt:840)
	at androidx.compose.ui.platform.DesktopOwner.onPointerEnter-k-4lQ0M$ui(DesktopOwner.desktop.kt:405)
	at androidx.compose.ui.platform.DesktopOwners.onMouseEntered(DesktopOwners.desktop.kt:211)
	at androidx.compose.ui.awt.ComposeLayer$initCanvas$2$mouseEntered$1.invoke(ComposeLayer.desktop.kt:191)
	at androidx.compose.ui.awt.ComposeLayer$initCanvas$2$mouseEntered$1.invoke(ComposeLayer.desktop.kt:190)
	at androidx.compose.ui.awt.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.desktop.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
```

It overtakes me on a variety of occasions. The easiest way to reproduce is to write the following code:
```
var testsState by remember {
    mutableStateOf<List<String>?>(null)
}
LaunchedEffect(Unit) {
    delay(2000)
    testsState = listOf("Hello")
}
LazyColumn {
    val tests = testsState
    if (tests != null) items(tests) { Text(it) }
}
```
and quickly move the mouse while the LaunchedEffect coroutine continues.

It also happens with other launches of coroutines, and very often when using TextField with DropdownMenu under it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6281">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
