### ISSUE TITLE
Running Web Compose samples errors

### ISSUE THREAD

**Issue by meshpaul** [JetBrains/compose-multiplatform#1270]
I first followed this readme and using Intellij Ultimate latest with JDK 15 and getting issue below.

I was following https://github.com/JetBrains/compose-jb/blob/v1.0.0-alpha4-build398/tutorials/Web/Getting_Started/README.md

I also checked out[ web-with-react ](https://github.com/JetBrains/compose-jb/tree/v1.0.0-alpha4-build362/examples/web-with-react)and I got the same error for build /tag `git checkout tags/v1.0.0-alpha4-build362 -b v1.0.0-alpha4-build362`

I noticed that README.md was not in sync with `v1.0.0-alpha4-build398` In both cases, I am getting the same Error see below.

I take it there is a step missing, please advise

```
9:33:53 PM: Executing task 'jsBrowserRun'...


> Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.


> Task :kotlinNpmCachesSetup
> Task :jsPackageJson
> Task :kotlinNodeJsSetup SKIPPED
> Task :rootPackageJson
> Task :kotlinNpmInstall
> Task :jsGenerateExternalsIntegrated SKIPPED
> Task :compileKotlinJs
> Task :jsProcessResources UP-TO-DATE
> Task :jsMainClasses
> Task :compileDevelopmentExecutableKotlinJs
> Task :jsDevelopmentExecutableCompileSync

> Task :jsBrowserDevelopmentRun FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1/userguide/command_line_interface.html#sec:command_line_warnings
9 actionable tasks: 8 executed, 1 up-to-date
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (/Users/user/projects/JetPackComposePOC/build/js/node_modules/webpack-cli/lib/webpack-cli.js:173:21)
    at ServeCommand.apply (/Users/user/projects/JetPackComposePOC/build/js/node_modules/@webpack-cli/serve/lib/index.js:41:19)
    at loadCommandByName (/Users/user/projects/JetPackComposePOC/build/js/node_modules/webpack-cli/lib/webpack-cli.js:907:35)
    at async Command.<anonymous> (/Users/user/projects/JetPackComposePOC/build/js/node_modules/webpack-cli/lib/webpack-cli.js:1462:17)
    at async Promise.all (index 0)
    at async WebpackCLI.run (/Users/user/projects/JetPackComposePOC/build/js/node_modules/webpack-cli/lib/webpack-cli.js:1500:9)
    at async runCLI (/Users/user/projects/JetPackComposePOC/build/js/node_modules/webpack-cli/lib/bootstrap.js:11:9)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jsBrowserDevelopmentRun'.
> [webpack-cli] Unable to load '@webpack-cli/serve' command
  [webpack-cli] TypeError: options.forEach is not a function
  [webpack-cli] TypeError: options.forEach is not a function
      at WebpackCLI.makeCommand (/Users/user/projects/JetPackComposePOC/build/js/node_modules/webpack-cli/lib/webpack-cli.js:173:21)
      at ServeCommand.apply (/Users/user/projects/JetPackComposePOC/build/js/node_modules/@webpack-cli/serve/lib/index.js:41:19)
      at loadCommandByName (/Users/user/projects/JetPackComposePOC/build/js/node_modules/webpack-cli/lib/webpack-cli.js:907:35)
      at async Command.<anonymous> (/Users/user/projects/JetPackComposePOC/build/js/node_modules/webpack-cli/lib/webpack-cli.js:1462:17)
      at async Promise.all (index 0)
      at async WebpackCLI.run (/Users/user/projects/JetPackComposePOC/build/js/node_modules/webpack-cli/lib/webpack-cli.js:1500:9)
      at async runCLI (/Users/user/projects/JetPackComposePOC/build/js/node_modules/webpack-cli/lib/bootstrap.js:11:9)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
9:34:01 PM: Task execution finished 'jsBrowserRun'.
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6270">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
