### ISSUE TITLE
java.lang.NullPointerException: event.text must not be null

### ISSUE THREAD

**Issue by lz233** [JetBrains/compose-multiplatform#152]
When type Chinese punctuation "。" in `TextField`, it crashed.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: event.text must not be null
	at androidx.compose.ui.platform.DesktopPlatformInput.onInputMethodTextChanged(DesktopPlatformInput.kt:163)
	at androidx.compose.ui.platform.DesktopOwners.onInputMethodTextChanged(DesktopOwners.kt:160)
	at androidx.compose.desktop.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.kt:145)
	at androidx.compose.desktop.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.kt)
	at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by olonho** [comment]
Could you please check with `0.2.0-build132`?

**Comment by CHH2000day** [comment]
Having same problem when typing Chinese characters.I'm using 0.2.0-build132

**Comment by prepor** [comment]
@CHH2000day could you please try with 0.3.0-build133 ?

**Comment by prepor** [comment]
Actually, it SHOULD work with `0.2.0-build132`. @CHH2000day are you sure about the version? and an exception is exactly the same?

**Comment by CHH2000day** [comment]
> @CHH2000day could you please try with 0.3.0-build133 ?

Updating to build133 works for me.And the exception on build132 is exactly the same.

**Comment by prepor** [comment]
Ok, thank you for the report!

**Comment by 201810988** [comment]
i have same problem with 0.2.0-build132 when typing Korean characters. Updating to build133 works for me too

**Comment by jimgoog** [comment]
The latest version numbers can be found here: https://github.com/JetBrains/compose-jb/tags

**Comment by jimgoog** [comment]
@201810988 This was closed last year, and `build133` is very very old at this point.  You can find the latest version numbers can be found here: https://github.com/JetBrains/compose-jb/tags

**Comment by ArTemmey** [comment]
have the similar problem on v1.0.0-alpha4-build348:
`Exception in thread "AWT-EventQueue-0 @coroutine#5" java.lang.NullPointerException
	at androidx.compose.ui.platform.SkiaLayer.isInLayer-k-4lQ0M(SkiaLayer.desktop.kt:128)`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5582">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
