### ISSUE TITLE
BottomSheetScaffold. `The initial value must have an associated anchor`

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1564]
Compose 1.0.0

```
import androidx.compose.material.BottomSheetScaffold
import androidx.compose.material.ExperimentalMaterialApi
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.window.singleWindowApplication

@OptIn(ExperimentalComposeUiApi::class, ExperimentalMaterialApi::class)
fun main() = singleWindowApplication {
    BottomSheetScaffold(
        sheetContent = {},
    ) { contentPadding ->
    }
}
```
Crash:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: The initial value must have an associated anchor.
	at androidx.compose.material.SwipeableState.ensureInit$material(Swipeable.kt:138)
	at androidx.compose.material.SwipeableKt$swipeable$3.invoke(Swipeable.kt:594)
	at androidx.compose.material.SwipeableKt$swipeable$3.invoke(Swipeable.kt:573)
	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:73)
	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:68)
	at androidx.compose.ui.Modifier$Element$DefaultImpls.foldIn(Modifier.kt:107)
	at androidx.compose.ui.ComposedModifier.foldIn(ComposedModifier.kt:46)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.ComposedModifierKt.materialize(ComposedModifier.kt:68)
	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke-Deg8D_g(Layout.kt:221)
	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke(Layout.kt:220)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:302)
	at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:255)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:252)
	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:110)
	at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1$2.invoke(BottomSheetScaffold.kt:336)
	at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1$2.invoke(BottomSheetScaffold.kt:335)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2427)
	at androidx.compose.material.BottomSheetScaffoldKt.BottomSheetScaffoldStack-SlNgfk0(BottomSheetScaffold.kt:427)
	at androidx.compose.material.BottomSheetScaffoldKt.access$BottomSheetScaffoldStack-SlNgfk0(BottomSheetScaffold.kt:1)
	at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1.invoke(BottomSheetScaffold.kt:323)
	at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1$child$1.invoke(BottomSheetScaffold.kt:322)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1.invoke(BottomSheetScaffold.kt:365)
	at androidx.compose.material.BottomSheetScaffoldKt$BottomSheetScaffold$1.invoke(BottomSheetScaffold.kt:285)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:2547)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:351)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:224)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:222)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:89)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:70)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:222)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.jvm.kt:433)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.update(Direct3DRedrawer.kt:56)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.access$update(Direct3DRedrawer.kt:12)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invokeSuspend(Direct3DRedrawer.kt:30)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6100">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
