### ISSUE TITLE
offset is out of bounds when VisualTransformation is used

### ISSUE THREAD

**Issue by bmalkow** [JetBrains/compose-multiplatform#1653]
Hi!

Im trying to use `VisualTransformation` in `TextField`. When transformer changing length of text.
The problem happens when I write some letters and then I try to move cursor using arrows on keyboard (left or right) from end of wrote text.
I assume that my transformer is wrong, so I checked two from tutorial ground in the internet:

```kotlin
class CameroonNumberVisualTransformation : VisualTransformation {

	override fun filter(text: AnnotatedString): TransformedText {
		// Make the string XXX-XXX-XXX
		val trimmed = if (text.text.length >= 9) text.text.substring(0..8) else text.text
		var output = ""
		for (i in trimmed.indices) {
			output += trimmed[i]
			if (i % 3 == 2 && i != 8) output += "-"
		}

		/**
		 * The offset works such that the translator ignores hyphens. Conversions
		 * from original to transformed text works like this
		- 3rd character in the original text is the 4th in the transformed text
		- The 6th character in the original becomes the 8th
		In reverse, the conversion is such that
		- 10th Character in transformed becomes the 8th in original
		- 4th in transformed becomes 3rd in original

		 */

		val cameroonNumberTranslator = object : OffsetMapping {
			override fun originalToTransformed(offset: Int): Int {
				// [offset [0 - 2] remain the same]
				if (offset <= 2) return offset
				// [3 - 5] transformed to [4 - 6] respectively
				if (offset <= 5) return offset + 1
				// [6 - 8] transformed to [8 - 10] respectively
				if (offset <= 8) return offset + 2
				return 11
			}

			override fun transformedToOriginal(offset: Int): Int {

				if (offset <= 2) return offset
				if (offset <= 6) return offset - 1
				if (offset <= 10) return offset - 2
				return 9

			}

		}

		return TransformedText(
			AnnotatedString(output), cameroonNumberTranslator
		)

	}

}
```

and the second one:

```kotlin
class CreditCardVisualTransformation : androidx.compose.ui.text.input.VisualTransformation {

	override fun filter(text: AnnotatedString): TransformedText {
		val mask = "1234  5678  1234  5678"
		val trimmed = if (text.text.length >= 16) text.text.substring(0..15) else text.text

		val annotatedString = AnnotatedString.Builder()
			.run {
				for (i in trimmed.indices) {
					append(trimmed[i])
					if (i % 4 == 3 && i != 15) {
						append("  ")
					}
				}
				pushStyle(SpanStyle(color = Color.LightGray))
				append(mask.takeLast(mask.length - length))
				toAnnotatedString()
			}

		val creditCardOffsetTranslator = object : OffsetMapping {
			override fun originalToTransformed(offset: Int): Int {
				if (offset <= 3) return offset
				if (offset <= 7) return offset + 2
				if (offset <= 11) return offset + 4
				if (offset <= 16) return offset + 6
				return 22
			}

			override fun transformedToOriginal(offset: Int): Int {
				if (offset <= 4) return offset
				if (offset <= 9) return offset - 2
				if (offset <= 14) return offset - 4
				if (offset <= 19) return offset - 6
				return 16
			}
		}

		return TransformedText(annotatedString, creditCardOffsetTranslator)
	}

}
```

In any it produces exception like this one:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: offset(90) is out of bounds [0, 22]
	at androidx.compose.ui.text.MultiParagraph.requireIndexInRangeInclusiveEnd(MultiParagraph.kt:593)
	at androidx.compose.ui.text.MultiParagraph.getParagraphDirection(MultiParagraph.kt:389)
	at androidx.compose.ui.text.TextLayoutResult.getParagraphDirection(TextLayoutResult.kt:343)
	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.isLtr(TextPreparedSelection.kt:250)
	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.moveCursorLeft(TextPreparedSelection.kt:99)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2$1.invoke(TextFieldKeyInput.kt:101)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2$1.invoke(TextFieldKeyInput.kt:101)
	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.collapseLeftOr(TextPreparedSelection.kt:120)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:101)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:96)
	at androidx.compose.foundation.text.TextFieldKeyInput.commandExecutionContext(TextFieldKeyInput.kt:193)
	at androidx.compose.foundation.text.TextFieldKeyInput.process-ZmokQxo(TextFieldKeyInput.kt:96)
	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$1$1.invoke-ZmokQxo(TextFieldKeyInput.kt:223)
	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$1$1.invoke(TextFieldKeyInput.kt:223)
	at androidx.compose.ui.node.ModifiedKeyInputNode.propagateKeyEvent-ZmokQxo(ModifiedKeyInputNode.kt:53)
	at androidx.compose.ui.input.key.KeyInputModifier.processKeyInput-ZmokQxo(KeyInputModifier.kt:78)
	at androidx.compose.ui.platform.DesktopOwner_desktopKt.sendKeyEvent-eyBIOjY(DesktopOwner.desktop.kt:42)
	at androidx.compose.ui.platform.SkiaBasedOwner.sendKeyEvent-ZmokQxo(SkiaBasedOwner.skiko.kt:209)
	at androidx.compose.ui.ComposeScene.sendKeyEvent-ZmokQxo(ComposeScene.skiko.kt:486)
	at androidx.compose.ui.awt.ComposeLayer$onKeyEvent$1.invoke(ComposeLayer.desktop.kt:354)
	at androidx.compose.ui.awt.ComposeLayer$onKeyEvent$1.invoke(ComposeLayer.desktop.kt:353)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:89)
	at androidx.compose.ui.awt.ComposeLayer.onKeyEvent(ComposeLayer.desktop.kt:353)
	at androidx.compose.ui.awt.ComposeLayer.access$onKeyEvent(ComposeLayer.desktop.kt:70)
	at androidx.compose.ui.awt.ComposeLayer$6.keyPressed(ComposeLayer.desktop.kt:263)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6593)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4892)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by akurasov** [comment]
Does you example work fine on Android? And could you share a complete reproducer for the issue, please?

**Comment by fcat97** [comment]
Getting the same issue. Here is my implementation:

```kotlin
class BanglaTransformation: VisualTransformation {
    override fun filter(text: AnnotatedString): TransformedText {
        if (text.isBlank()) return TransformedText(text, OffsetMapping.Identity)

        return if (App.appLang == "bn") {
            val transformedText = App.avro.parse(text.text)

            val map = object : OffsetMapping {
                override fun originalToTransformed(offset: Int): Int {
                    val reduced = text.length - transformedText.length
                    "o2t: len:${transformedText.length}(${text.length})  off:$offset ret:$reduced ${text.text}-->$transformedText".print()
                    return offset - reduced
                }

                override fun transformedToOriginal(offset: Int): Int {
                    val reduced = text.length - transformedText.length
                    "t2o: len:${transformedText.length}(${text.length})  off:$offset ret:$reduced ${text.text}-->$transformedText".print()
                    return offset + reduced
                }
            }

            TransformedText(AnnotatedString(transformedText), map)
        } else {
            TransformedText(text, OffsetMapping.Identity)
        }
    }
}
```

In my case, I'm trying to parse English text into Bangla. For instance, if the input is `Bangla` which has 6 char, after transformation it becomes `বাংলা‍‍‍` which has 5 char. It works fine when typing but crashes when I move the cursor with arrow key.

**Comment by KYamshanov** [comment]
It`s reproduce for BasicTextField with property singleLine = true. I use compose version "1.4.0".

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1653">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
