### ISSUE TITLE
Skiko native crash when running screenshot tests in GitHub actions

### ISSUE THREAD

**Issue by dzirbel** [JetBrains/compose-multiplatform#1691]
I've been running into what appears to be a crash in native code from skiko when running my application's "screenshot" tests via GitHub actions. For some context, my application has a small suite of unit tests which generate a screenshot of various content via `ImageComposeScene()`, and then verify that it matches the expected image; for reference the code can be found [here](https://github.com/dzirbel/kotify/blob/master/src/test/kotlin/com/dzirbel/kotify/ui/ScreenshotTest.kt).

This generally works great, but recently I've been seeing an issue specifically when running these tests in GitHub actions. Some details:
- I've never been able to reproduce this on my own machine or anything outside of GH actions. It could easily be a problem with their environment but given that it's specifically an exception from skiko I thought I'd start here.
- The exception occurs after the last test in the suite runs, never earlier. It seems that the tests themselves are fine, and perhaps this is some kind of cleanup code that has the issue. Given the stack trace is pretty sparse I haven't been able to track it down further than that.
- My action configuration can be found [here](https://github.com/dzirbel/kotify/blob/master/.github/workflows/build.yml), for reference. It uses `windows-latest` and OpenJDK 16.0.2, the same version as I have installed myself.
- It does succeed occasionally but fails ~75% of the time.
- I'm using the latest Compose (1.0.1) and Gradle (7.3.3) versions

A full run with this error is [here](https://github.com/dzirbel/kotify/runs/4798153212). The relevant error is:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff99d6f65ce, pid=5932, tid=5452
#
# JRE version: OpenJDK Runtime Environment Temurin-16.0.2+7 (16.0.2+7) (build 16.0.2+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (16.0.2+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [skiko-windows-x64.dll+0x565ce]
#
# Core dump will be written. Default location: D:\a\kotify\kotify\hs_err_pid5932.mdmp
#
# An error report file with more information is saved as:
# D:\a\kotify\kotify\hs_err_pid5932.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Unexpected exception thrown.


org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:50093'.
> Task :testLocal FAILED
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:140)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:333)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:279)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:267)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:261)
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:138)
	... 7 more
```

I believe (but am not certain) that the gradle stack trace is just a generic gradle exception due to the JVM error during the test suite.

**Comment by olonho** [comment]
Could you please attach `hs_err_pid5932.log`.

**Comment by igordmn** [comment]
Unfortunately, `ImageComposeScene` [doesn't work well](https://github.com/JetBrains/compose-jb/issues?q=is%3Aissue+is%3Aopen+ImageComposeScene) if we use it outside of AWT thread. I plan to fix that in the near future.

As a temporary workaround - use `ImageComposeScene` inside `runBlocking(Dispatchers.Swing) { }`

**Comment by dzirbel** [comment]
> Could you please attach `hs_err_pid5932.log`.

No, unfortunately - I don't believe I have access to the file on the Actions workspace, and I can't reproduce the error anywhere else.

> Unfortunately, `ImageComposeScene` [doesn't work well](https://github.com/JetBrains/compose-jb/issues?q=is%3Aissue+is%3Aopen+ImageComposeScene) if we use it outside of AWT thread. I plan to fix that in the near future.
> 
> As a temporary workaround - use `ImageComposeScene` inside `runBlocking(Dispatchers.Swing) { }`

Thanks, this seems to have worked! 3/3 runs have passed now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1691">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
