### ISSUE TITLE
ComposePanel as SwingNode.content = Cannot read field "width" because "d" is null

### ISSUE THREAD

**Issue by graycatdeveloper** [JetBrains/compose-multiplatform#1964]
My code fragment
```
class OverlayWindow : JFrame() {
private val jfxPanel = JFXPanel()
init {
...
add(jfxPanel)
}

fun setContent(root: () -> Parent) {
        val pane = root() as VBox
        val swingNode = SwingNode()
        Platform.runLater {
            pane.children.add(swingNode)
            val scene = Scene(pane, 570.0, 252.0, FXColor.TRANSPARENT)
            jfxPanel.scene = scene
        }
        CoroutineScope(Dispatchers.Swing).launch {
            //delay(3000)
            val composePanel = ComposePanel()
            composePanel.setContent {
                Text("zkdjdfvbd")
            }
            swingNode.content = composePanel//JButton("Click me!")
        }
    }
```
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "width" because "d" is null
	at java.desktop/sun.swing.JLightweightFrame.setContent(JLightweightFrame.java:193)
	at jdk.unsupported.desktop/jdk.swing.interop.LightweightFrameWrapper.setContent(LightweightFrameWrapper.java:109)
	at javafx.swing/com.sun.javafx.embed.swing.newimpl.SwingNodeInteropN.setContent(SwingNodeInteropN.java:150)
	at javafx.swing/javafx.embed.swing.SwingNode.setContentImpl(SwingNode.java:381)
	at javafx.swing/javafx.embed.swing.SwingNode.lambda$setContent$5(SwingNode.java:340)
	at javafx.swing/com.sun.javafx.embed.swing.SwingNodeHelper.runOnEDT(SwingNodeHelper.java:170)
	at javafx.swing/javafx.embed.swing.SwingNode.setContent(SwingNode.java:340)
	at dev.bint.ui.window.OverlayWindow$setContent$2.invokeSuspend(OverlayWindow.kt:147)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
	at kotlinx.coroutines.swing.SwingDispatcher.scheduleResumeAfterDelay$lambda-1(SwingDispatcher.kt:33)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "width" because "d" is null
	at java.desktop/sun.swing.JLightweightFrame.setContent(JLightweightFrame.java:193)
	at jdk.unsupported.desktop/jdk.swing.interop.LightweightFrameWrapper.setContent(LightweightFrameWrapper.java:109)
	at javafx.swing/com.sun.javafx.embed.swing.newimpl.SwingNodeInteropN.setContent(SwingNodeInteropN.java:150)
	at javafx.swing/javafx.embed.swing.SwingNode.setContentImpl(SwingNode.java:381)
	at javafx.swing/javafx.embed.swing.SwingNode.lambda$setContent$5(SwingNode.java:340)
	at javafx.swing/com.sun.javafx.embed.swing.SwingNodeHelper.runOnEDT(SwingNodeHelper.java:170)
	at javafx.swing/javafx.embed.swing.SwingNode.setContent(SwingNode.java:340)
	at dev.bint.ui.window.OverlayWindow$setContent$2.invokeSuspend(OverlayWindow.kt:147)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
	at kotlinx.coroutines.swing.SwingDispatcher.scheduleResumeAfterDelay$lambda-1(SwingDispatcher.kt:33)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.peer.FramePeer.emulateActivation(boolean)" because "peer" is null
	at java.desktop/sun.awt.LightweightFrame.emulateActivation(LightweightFrame.java:120)
	at jdk.unsupported.desktop/jdk.swing.interop.LightweightFrameWrapper.emulateActivation(LightweightFrameWrapper.java:115)
	at javafx.swing/com.sun.javafx.embed.swing.newimpl.SwingNodeInteropN.emulateActivation(SwingNodeInteropN.java:222)
	at javafx.swing/javafx.embed.swing.SwingNode.lambda$activateLwFrame$22(SwingNode.java:732)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1964">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
