### ISSUE TITLE
UnsatisfiedLinkError when running UberJar with isSystemInDarkTheme method

### ISSUE THREAD

**Issue by russellbanks** [JetBrains/compose-multiplatform#2069]
### Bug Description

In my [application](https://github.com/russellbanks/HashHash), packaging an UberJar and then running it will result in a `java.lang.UnsatisfiedLinkError`, pointing to Skiko's `getCurrentSystemTheme` method. In my code, I have this the associated `isSystemInDarkTheme` method [here](https://github.com/russellbanks/HashHash/blob/ee047da5ea1535fccc4b3323b24e9a9300bc8cfc/src/main/kotlin/Main.kt#L117). I have been unsuccessful so far in trying to reproduce this in smaller environments than my app. Running the app normally through any other distribution works just fine.

#### Exception:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme()'
        at org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme(Native Method)
        at org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme(SystemTheme.awt.kt:4)
        at androidx.compose.foundation.DarkTheme_skikoKt._isSystemInDarkTheme(DarkTheme.skiko.kt:48)
        at androidx.compose.foundation.DarkThemeKt.isSystemInDarkTheme(DarkTheme.kt:41)
        at ComposableSingletons$MainKt$lambda-1$1.invoke(Main.kt:117)
        at ComposableSingletons$MainKt$lambda-1$1.invoke(Main.kt:76)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at org.pushingpixels.aurora.window.AuroraWindowKt$auroraApplication$1$1.invoke(AuroraWindow.kt:543)
        at org.pushingpixels.aurora.window.AuroraWindowKt$auroraApplication$1$1.invoke(AuroraWindow.kt:542)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at org.pushingpixels.aurora.window.AuroraWindowKt$auroraApplication$1.invoke(AuroraWindow.kt:538)
        at org.pushingpixels.aurora.window.AuroraWindowKt$auroraApplication$1.invoke(AuroraWindow.kt:536)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:115)
        at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:114)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:226)
        at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:225)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:221)
        at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:219)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:71)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3152)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3142)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3142)
        at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3079)
        at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:570)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:814)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:505)
        at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Platform Info

Compose Version: 1.2.0-alpha01-dev686

Operating System: Windows 11

**Comment by russellbanks** [comment]
#1761 Seems to be have had the same/similar issue, but says it has been fixed in `1.1.0-alpha03`, whereas I am experiencing this in later versions.

**Comment by russellbanks** [comment]
Supposedly fixed with [this commit](https://github.com/manu-unter/skiko/commit/d77b7d13d91d1f413e68723ebfad4285636b5dfb).

**Comment by Cryolitia** [comment]
I have the same problem in compose 1.1.1

**Comment by kxmpxtxnt** [comment]
Same here with "1.2.0-alpha01-dev764"

**Comment by kxmpxtxnt** [comment]
Is there any fix atm?

**Comment by russellbanks** [comment]
> Is there any fix atm?

@kxmpxtxnt I've been using [Dansoftowner/jSystemThemeDetector](https://github.com/Dansoftowner/jSystemThemeDetector) instead of the `isSystemInDarkTheme` method:

```kotlin
val osThemeDetector = OsThemeDetector.getDetector()
val isDark = osThemeDetector.isDark
```

The added bonus is jSystemThemeDetector has a listener for when the system's theme changes so that your app's theme can change too.

**Comment by kxmpxtxnt** [comment]
Thank you

**Comment by lizhongyue248** [comment]
Same here with "1.6.0-beta02"

## Steps
1. Generate project only desktop in https://kmp.jetbrains.com/
2. Upgrade compose to 1.6.0, compose-plugin to 1.6.0-beta02 and kotlin to 1.9.22
3. Run code
```kotlin
fun main() = application {
    println("isSystemInDarkTheme() ${isSystemInDarkTheme()}")

    Window(onCloseRequest = ::exitApplication, title = "KotlinProject12") {
        App()
    }
}
```

Get errors
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme()'
	at org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme(Native Method)
	at org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme(SystemTheme.awt.kt:4)
	at androidx.compose.ui.SystemThemeKt$LocalSystemTheme$1.invoke(SystemTheme.kt:30)
	at androidx.compose.ui.SystemThemeKt$LocalSystemTheme$1.invoke(SystemTheme.kt:29)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
	at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:90)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:2136)
	at androidx.compose.foundation.DarkTheme_skikoKt._isSystemInDarkTheme(DarkTheme.skiko.kt:53)
	at androidx.compose.foundation.DarkThemeKt.isSystemInDarkTheme(DarkTheme.kt:41)
	at ComposableSingletons$MainKt$lambda-2$1.invoke(main.kt:12)
	at ComposableSingletons$MainKt$lambda-2$1.invoke(main.kt:11)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:115)
	at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:114)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:227)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:226)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:221)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:219)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:33)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3303)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3236)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:723)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1071)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:631)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:617)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by m-sasha** [comment]
This should be fixed by https://github.com/JetBrains/skiko/pull/866 when we update skiko in Compose Multiplatform. In the meanwhile you can add 
```
Library.load()
```
before calling `isSystemInDarkTheme()`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2069">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
