### ISSUE TITLE
k/js: IncompatibleClassChangeError when updating to 1.6.21 and corresponding compose build

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-multiplatform#2115]
From slack:

> I'm trying to upgrade to Kotlin 1.6.21 but I keep getting this error no matter what version of compose-web I use (but mainly trying to get 1.2.0-alpha01-dev709 working)

```
java.lang.IncompatibleClassChangeError: Found class org.jetbrains.kotlin.ir.types.IrType, but interface was expected
	at androidx.compose.compiler.plugins.kotlin.lower.decoys.WrapNotInlineableComposableLambdasForJs$wrapComposableLambdasInCall$mappedArguments$2.invoke(WrapNotInlineableComposableLambdasForJs.kt:142)
	at androidx.compose.compiler.plugins.kotlin.lower.decoys.WrapNotInlineableComposableLambdasForJs$wrapComposableLambdasInCall$mappedArguments$2.invoke(WrapNotInlineableComposableLambdasForJs.kt:135)

etc...
```

https://github.com/dellisd/reroute/tree/upgrades

```
If I try to force gradle to resolve 1.6.21 for all Kotlin modules I get a different error
FATAL ERROR: Could not find "...\.gradle\caches\modules-2\files-2.1\app.cash.sqldelight\sqljs-driver\2.0.0-SNAPSHOT\4f3b183e3f1c1b4797f9f186dc1ad2f60f0d87f5\sqljs-driver-2.0.0-SNAPSHOT.klib"
I checked and this file does exist, so I don't know why it gives this error.
The sqljs-driver module depends on the Kotlin 1.7.0 stdlib so I wonder if that's why?
```

```
If I downgrade SQLDelight and compile with 1.6.21 I get the following error instead:
kotlin.NotImplementedError: An operation is not implemented: org.jetbrains.kotlin.ir.types.impl.IrDynamicTypeImpl@2712046a
	at org.jetbrains.kotlin.ir.descriptors.IrBasedDescriptorsKt.toIrBasedKotlinType(IrBasedDescriptors.kt:1137)
	at org.jetbrains.kotlin.ir.descriptors.IrBasedDescriptorsKt.makeKotlinType(IrBasedDescriptors.kt:1151)
	at org.jetbrains.kotlin.ir.descriptors.IrBasedDescriptorsKt.toIrBasedKotlinType(IrBasedDescriptors.kt:1136)
    ...
If I upgrade Kotlin, ksp, and compose for 1.7.0 I get this error:
java.lang.AssertionError: Unexpected type: org.jetbrains.kotlin.ir.types.impl.IrDynamicTypeImpl@3c59468a = dynamic
	at org.jetbrains.kotlin.ir.descriptors.IrBasedDescriptorsKt.toIrBasedKotlinType(IrBasedDescriptors.kt:1142)
	at org.jetbrains.kotlin.ir.descriptors.IrBasedDescriptorsKt.makeKotlinType(IrBasedDescriptors.kt:1157)
	at org.jetbrains.kotlin.ir.descriptors.IrBasedDescriptorsKt.toIrBasedKotlinType(IrBasedDescriptors.kt:1134)
    ...
(edited)
```

**Comment by kirill-grouchnikov** [comment]
There's no really way out of this until we have an official Compose Desktop build that supports Kotlin 1.7.0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2115">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
