### ISSUE TITLE
Preview window stop updating

### ISSUE THREAD

**Issue by denchic45** [JetBrains/compose-multiplatform#2156]
When you try to show a preview, loading appears for a couple of seconds, then an empty window

![Снимок экрана 2022-07-01 212604](https://user-images.githubusercontent.com/80104523/176950156-a9a28857-177b-4530-ba0f-cfe11811d735.png)

![Снимок экрана 2022-07-01 212522](https://user-images.githubusercontent.com/80104523/176949999-d291bbf2-9ea9-4022-972c-8eeb32d59c0a.png)

Using Android Studio Chipmunk | 2021.2.1 Patch 1
Compose version: 1.1.1

**Comment by denchic45** [comment]
After the last update, this problem seems to have disappeared and the preview began to work correctly. For now, I'll close this question.

**Comment by denchic45** [comment]
Ran into this problem again. After some time, the preview simply stops updating, leaving only the last render. The last time this happened was after I resized the android studio window. Only restarting android studio helps

**Comment by denchic45** [comment]
Restarting the plugin also helps.

**Comment by denchic45** [comment]
I checked again, but restarting the plugin doesn't always work.

**Comment by dsvoronin** [comment]
Same issue with Intellij Idea CE 2022.2.3
Got the same exception in `idea.log` everytime
Reproducible in Linux and Windows

```
2022-10-19 21:42:39,503 [1688338]   INFO - STDOUT - CONNECTION (GRADLE_CALLBACK) #1:GOT COMMAND 'PREVIEW_CONFIG C%3A%5CUsers%5Cdsvor%5C.jdks%5Copenjdk-17.0.2%5Cbin%5Cjava.exe'
2022-10-19 21:42:39,504 [1688339]   INFO - STDOUT - CONNECTION (GRADLE_CALLBACK) #1:GOT [625]
2022-10-19 21:42:39,504 [1688339]   INFO - STDOUT - CONNECTION (GRADLE_CALLBACK) #1:GOT COMMAND 'PREVIEW_CLASSPATH'
2022-10-19 21:42:39,504 [1688339]   INFO - STDOUT - CONNECTION (GRADLE_CALLBACK) #1:GOT [10779]
2022-10-19 21:42:39,505 [1688340]   INFO - STDOUT - CONNECTION (GRADLE_CALLBACK) #1:GOT COMMAND 'PREVIEW_FQ_NAME'
2022-10-19 21:42:39,505 [1688340]   INFO - STDOUT - CONNECTION (GRADLE_CALLBACK) #1:GOT [30]
2022-10-19 21:42:39,505 [1688340]   INFO - STDOUT - CONNECTION (GRADLE_CALLBACK) #1:CLOSING
2022-10-19 21:42:39,506 [1688341]   INFO - STDOUT - CONNECTION (GRADLE_CALLBACK) #1:CLOSED
2022-10-19 21:42:39,555 [1688390]   INFO - STDERR - Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Stream closed
2022-10-19 21:42:39,555 [1688390]   INFO - STDERR - 	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
2022-10-19 21:42:39,555 [1688390]   INFO - STDERR - 	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
2022-10-19 21:42:39,555 [1688390]   INFO - STDERR - 	at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:127)
2022-10-19 21:42:39,555 [1688390]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2022-10-19 21:42:39,555 [1688390]   INFO - STDERR - Caused by: java.io.IOException: Stream closed
2022-10-19 21:42:39,555 [1688390]   INFO - STDERR - 	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:168)
2022-10-19 21:42:39,555 [1688390]   INFO - STDERR - 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:334)
2022-10-19 21:42:39,556 [1688391]   INFO - STDERR - 	at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:98)
2022-10-19 21:42:39,556 [1688391]   INFO - STDERR - 	... 1 more
2022-10-19 21:42:40,258 [1689093]   INFO - STDOUT - CONNECTION (PREVIEW) #2:GOT COMMAND 'ATTACH 2'
2022-10-19 21:42:40,514 [1689349]   INFO - STDOUT - CONNECTION (PREVIEW) #2:SENT COMMAND 'PREVIEW_CLASSPATH'
2022-10-19 21:42:40,514 [1689349]   INFO - STDOUT - CONNECTION (PREVIEW) #2:SENT DATA [10779]
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2156">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
