### ISSUE TITLE
Disposable effect crashes when referring to MutableState in anonymous object inside effect (JS)

### ISSUE THREAD

**Issue by avwie** [JetBrains/compose-multiplatform#2177]
When I create a `DisposableEffect` the compiler crashes for Kotlin/JS:
```
DisposableEffect(Unit) {
        val handler : EventListener = object : EventListener {
            override fun handleEvent(event: Event) {
                if (event.target != null) {
                    //editMode = false <- compiler error when I uncomment this
                }
            }
        }

        document.body?.addEventListener("click", handler)
        onDispose {
            document.body?.removeEventListener("click", handler)
        }
    }
```

It works when i pass a lambda to `addEventListener`.

The last elements of the stack-trace are:
```
java.lang.IllegalStateException: Validation failed in file Components.kt <-- my file
	at org.jetbrains.kotlin.backend.common.IrValidator.error(IrValidator.kt:83)
	at org.jetbrains.kotlin.backend.common.IrValidator.access$error(IrValidator.kt:61)
```

I am using Kotlin MPP 1.6.10 and Compose 1.1.1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2177">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
