### ISSUE TITLE
Setting a modifier on the splitter makes it crash

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#2214]
If you set a modifier on a Splitter, it crashes with something like this:

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 1004.0 is less than minimum 1358.0.
	at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1263)
	at org.jetbrains.compose.splitpane.DesktopSplitPaneKt$SplitPane$5.measure-3p2s80s(DesktopSplitPane.kt:80)
        ...
```

You can repro with something like this:

```kotlin
@Composable
fun EntryPoint() {
    Row(Modifier.fillMaxSize()) {
        MyComposable(Modifier.weight(1f).fillMaxWidth())
    }
}

@Composable
fun MyComposable(modifier: Modifier = Modifier) {
    HorizontalSplitPane(modifier) {
        first(minSize = minSizeLeft) {
            Box(Modifier.fillMaxSize().background(Color.Blue))
        }
        second(minSize = minSizeLeft) {
            Box(Modifier.fillMaxSize().background(Color.Red))
        }
        splitter {
            handle {
                Box(
                    Modifier
                        .markAsHandle()
                        .pointerHoverIcon(PointerIcon(Cursor(Cursor.E_RESIZE_CURSOR)))
                        .width(10.dp)
                        .fillMaxHeight()
                )
            }
        }
    }
}
```

If you change the `HorizontalSplitPane` invocation dropping the `modifier`, it works fine.

**Comment by rock3r** [comment]
You can also make it work by removing the `fillMaxWidth()` modifier in `EntryPoint`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2214">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
