### ISSUE TITLE
libskiko-linux-arm64.so: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by lindeer** [JetBrains/compose-multiplatform#2279]
When I started to build compose template project on my laptop, error occurred as follow:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/wesley/.skiko/bdcaedf252aef6cf30ec5e4306d4e67047a18dac30272b23151ea287cd10e421/libskiko-linux-arm64.so: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/wesley/.skiko/bdcaedf252aef6cf30ec5e4306d4e67047a18dac30272b23151ea287cd10e421/libskiko-linux-arm64.so)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at org.jetbrains.skiko.Library.loadLibraryOrCopy(Library.kt:20)
	at org.jetbrains.skiko.Library.findAndLoad(Library.kt:113)
	at org.jetbrains.skiko.Library.load(Library.kt:59)
	at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
	at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose(ConfigureSwingGlobalsForCompose.desktop.kt:49)
	at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose$default(ConfigureSwingGlobalsForCompose.desktop.kt:38)
	at androidx.compose.ui.window.Application_desktopKt.application(Application.desktop.kt:111)
	at androidx.compose.ui.window.Application_desktopKt.application$default(Application.desktop.kt:105)
	at MainKt.main(main.kt:16)
```
 My laptop indeed not have GLIBC_2.29
```
$ uname -ar
Linux wesley-UOS 4.19.71-arm64-desktop #1 SMP PREEMPT Thu Jul 15 14:18:15 CST 2021 aarch64 GNU/Linux

$ strings /lib/aarch64-linux-gnu/libm.so.6 | grep 'GLIBC_'
GLIBC_2.17
GLIBC_2.18
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.27
GLIBC_2.28
GLIBC_PRIVATE
```
current glic is the latest package in apt source, I'm afraid upgrading system glibc privately would cause other issues, is there any safe way of upgrading glibc or make compose's glibc downgrade to make it work? Thanks a lot.

**Comment by VladRassokhin** [comment]
The actual problem is in skiko library, created [issue](https://github.com/JetBrains/skiko/issues/642) there.

**Comment by EzzPress** [comment]
Any progress on this issue?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2279">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
