### ISSUE TITLE
Webpack-cli error that occurs in the getting started with compose for web.

### ISSUE THREAD

**Issue by kota-shiokara** [JetBrains/compose-multiplatform#2319]
I tried to start compose for web that follow "[getting started with compose for web](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Web/Getting_Started)".
Since "[webpack-cli] Unable to load '@webpack-cli/serve' command" is known, I put [this](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Web/Getting_Started#common-issues-when-running-the-project) in my gradle file.

However, I got error described below when I run gradle process.
```
> Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.


> Task :kotlinNpmInstall
warning Ignored scripts due to flag.

> Task :jsBrowserDevelopmentRun FAILED
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (D:\atelier\kota-shiokara.github.io\build\js\node_modules\@webpack-cli\serve\lib\index.js:146:35)
    at async Promise.all (index 1)
    at async Command.<anonymous> (D:\atelier\kota-shiokara.github.io\build\js\node_modules\webpack-cli\lib\webpack-cli.js:1687:7)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jsBrowserDevelopmentRun'.
> [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
  [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
      at Command.<anonymous> (D:\atelier\kota-shiokara.github.io\build\js\node_modules\@webpack-cli\serve\lib\index.js:146:35)
      at async Promise.all (index 1)
      at async Command.<anonymous> (D:\atelier\kota-shiokara.github.io\build\js\node_modules\webpack-cli\lib\webpack-cli.js:1687:7)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
14 actionable tasks: 7 executed, 7 up-to-date
```
<br/>

I found that this error has been fixed in 4.10.0 of webpack-cli.  
[webpack issue#15951](https://github.com/webpack/webpack/issues/15951)
<br/>

I think need readme fixed.
```
        versions.webpackCli.version = "4.9.0"
```
to
```
        versions.webpackCli.version = "4.10.0"
```
https://github.com/JetBrains/compose-jb/blob/master/tutorials/Web/Getting_Started/README.md

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2319">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
