### ISSUE TITLE
NPE occurring in ComposeAccessibleComponent.getAccessibleParent

### ISSUE THREAD

**Issue by asapha** [JetBrains/compose-multiplatform#2435]
I sometimes see this error in the logs

```
java.lang.NullPointerException
	at androidx.compose.ui.platform.ComposeAccessible$ComposeAccessibleComponent.getAccessibleParent(ComposeAccessible.kt:203)
	at java.desktop/sun.lwawt.macosx.CAccessibility$15.call(CAccessibility.java:313)
	at java.desktop/sun.lwawt.macosx.CAccessibility$15.call(CAccessibility.java:309)
	at java.desktop/sun.lwawt.macosx.LWCToolkit$CallableWrapper.run(LWCToolkit.java:694)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

This one lead to a crash.
It occurred while changing focus via the tab key.

```
java.lang.NullPointerException
	at androidx.compose.ui.platform.ComposeAccessible$ComposeAccessibleComponent.getAccessibleParent(ComposeAccessible.kt:203)
	at java.desktop/sun.lwawt.macosx.CAccessible$AXChangeNotifier.propertyChange(CAccessible.java:155)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/javax.accessibility.AccessibleContext.firePropertyChange(AccessibleContext.java:790)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.fireChangedNodeEvent(Accessibility.desktop.kt:85)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes$findAllSemanticNodesRecursive(Accessibility.desktop.kt:151)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes$findAllSemanticNodesRecursive(Accessibility.desktop.kt:162)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes$findAllSemanticNodesRecursive(Accessibility.desktop.kt:162)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes$findAllSemanticNodesRecursive(Accessibility.desktop.kt:162)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes$findAllSemanticNodesRecursive(Accessibility.desktop.kt:162)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes(Accessibility.desktop.kt:166)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncLoop(Accessibility.desktop.kt:134)
	at androidx.compose.ui.platform.AccessibilityControllerImpl$syncLoop$1.invokeSuspend(Accessibility.desktop.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:56)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:51)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:85)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:33)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeLayer$coroutineExceptionHandler$1@e185a03, androidx.compose.runtime.BroadcastFrameClock@5ee0efe3, StandaloneCoroutine{Cancelling}@60880afb, FlushCoroutineDispatcher@468483b3]
```

compose-jb: 1.2.0
os: macOS 12.6 (21G115)

**Comment by igordmn** [comment]
Hi, thanks for the report!

1. Is this issue reproduced often?
2. Is it possible to write a small reproducer?
3. Is it reproduced before Compose 1.2.0?

**Comment by igordmn** [comment]
Closing, as it is not enough information to reproduce the crash, and there is no other reports.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2435">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
