### ISSUE TITLE
NPE: getLocalGraphicsEnvironment.defaultConfiguration must not be null

### ISSUE THREAD

**Issue by andreyfomenkov** [JetBrains/compose-multiplatform#2548]
Compose Desktop, macOS BigSur 11.7, **org.jetbrains.compose** version **1.1.0**
Exception on startup:
```
Exception in thread "main" java.lang.NullPointerException: getLocalGraphicsEnvironm… .defaultConfiguration must not be null 
at androidx.compose.ui.window.LayoutConfiguration_desktopKt.getGlobalDensity(LayoutConfiguration.desktop.kt:36) 
at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:225) 
at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:220) 
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107) 
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34) 
at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:72) 
at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2582) 
at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571) 
at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247) 
at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source) 
at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571) 
at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:2522) 
at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:478) 
at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:748) 
at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:433) 
at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:220) 
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) 
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776) 
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) 
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) 
at java.base/java.security.AccessController.doPrivileged(Native Method) 
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746) 
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by andreyfomenkov** [comment]
**Update:** looks like this crash happens when the second monitor is plugged in

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2548">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
