### ISSUE TITLE
KJS / Compose Web: "NoSuchMethodError: 'void org.gradle.api.internal.tasks.testing.TestResultProcessor.failure" when running jsNodeTest

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2610]
Moved from https://youtrack.jetbrains.com/issue/KT-55779

***What steps will reproduce the issue?***

Project attached

1. run `/gradlew jsNodeTest`

***What is the expected result?***

The Gradle test task passes or fails

***What happens instead?***

```stacktrace
> Task :jsNodeTest FAILED
Could not read standard output of command '/.../.local/share/gradle/nodejs/node-v16.13.0-darwin-x64/bin/node'.
java.lang.NoSuchMethodError: 'void org.gradle.api.internal.tasks.testing.TestResultProcessor.failure(java.lang.Object, java.lang.Throwable)'
        at org.jetbrains.kotlin.gradle.internal.testing.TCServiceMessagesClient.failure(TCServiceMessagesClient.kt:176)
        at org.jetbrains.kotlin.gradle.internal.testing.TCServiceMessagesClient.serviceMessage(TCServiceMessagesClient.kt:78)
        at jetbrains.buildServer.messages.serviceMessages.ServiceMessagesParser.parse(ServiceMessagesParser.java:54)
        at jetbrains.buildServer.messages.serviceMessages.ServiceMessage.parse(ServiceMessage.java:121)
        at org.jetbrains.kotlin.gradle.internal.testing.TCServiceMessageOutputStreamHandler.parse(TCServiceMessageOutputStreamHandler.kt:121)
        at org.jetbrains.kotlin.gradle.internal.testing.TCServiceMessageOutputStreamHandler.flushLine(TCServiceMessageOutputStreamHandler.kt:81)
        at org.jetbrains.kotlin.gradle.internal.testing.TCServiceMessageOutputStreamHandler.write(TCServiceMessageOutputStreamHandler.kt:61)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:67)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kotka-streams-site:jsNodeTest'.
> 'void org.gradle.api.internal.tasks.testing.TestResultProcessor.failure(java.lang.Object, java.lang.Throwable)'
```

**Comment by jillesvangurp** [comment]
Running into this as well with test failures with kotlin-js node.js tests (mocha). Works in gradle 7.5.1, broke in gradle 7.6.0. Looks like some internal gradle APIs changed?

**Comment by xuan-nguyen-swe** [comment]
I have exactly the issue with kotlin-react.
Downgrade to Gradle 7.5.1 fixed the error.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2610">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
