### ISSUE TITLE
IR transform fails on value class with private ctor and/or private val

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/compose-multiplatform#2613]
Jetpack Compose version:
- JetBrains Compose compiler 1.3.2.2
- JetBrains Compose runtime 1.2.2

Kotlin version: 1.7.20

Reproducing project attached to https://issuetracker.google.com/issues/251430194#comment6

The offending code:
```kotlin
value class Example private constructor(private val ordinal: Int)
```
or
```kotlin
value class Example(private val ordinal: Int)
```

If the constructor is private the stack is:
```
Caused by: java.lang.IllegalStateException: Expected a value parameter
        at androidx.compose.compiler.plugins.kotlin.lower.AbstractComposeLowering.unboxValueIfInline(AbstractComposeLowering.kt:324)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.irChanged(ComposableFunctionBodyTransformer.kt:2150)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.buildPreambleStatementsAndReturnIfSkippingPossible(ComposableFunctionBodyTransformer.kt:1450)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.visitRestartableComposableFunction(ComposableFunctionBodyTransformer.kt:1173)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.visitFunctionInScope(ComposableFunctionBodyTransformer.kt:768)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.visitFunction(ComposableFunctionBodyTransformer.kt:733)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:72)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:73)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:28)
        at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:24)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transformChildren(IrFile.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitPackageFragment(IrElementTransformerVoid.kt:41)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:47)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.visitFile(ComposableFunctionBodyTransformer.kt:1885)
        ... 168 more
```

If the constructor is public or internal but the val is private the stack is:
```
e: java.lang.AssertionError: Assertion failed
        at org.jetbrains.kotlin.ir.util.AdditionalIrUtilsKt.getPropertyGetter(AdditionalIrUtils.kt:250)
        at androidx.compose.compiler.plugins.kotlin.lower.AbstractComposeLowering.unboxValueIfInline(AbstractComposeLowering.kt:325)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.irChanged(ComposableFunctionBodyTransformer.kt:2150)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.buildPreambleStatementsAndReturnIfSkippingPossible(ComposableFunctionBodyTransformer.kt:1450)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.visitRestartableComposableFunction(ComposableFunctionBodyTransformer.kt:1173)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.visitFunctionInScope(ComposableFunctionBodyTransformer.kt:768)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.visitFunction(ComposableFunctionBodyTransformer.kt:733)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:72)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:73)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:28)
        at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:24)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transformChildren(IrFile.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitPackageFragment(IrElementTransformerVoid.kt:41)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:47)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.visitFile(ComposableFunctionBodyTransformer.kt:1885)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:48)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:22)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transform(IrFile.kt:25)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transform(IrFile.kt:14)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.transformChildren(IrModuleFragment.kt:40)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposableFunctionBodyTransformer.lower(ComposableFunctionBodyTransformer.kt:491)
        at androidx.compose.compiler.plugins.kotlin.ComposeIrGenerationExtension.generate(ComposeIrGenerationExtension.kt:176)
```

Keys:
- The value class is in a separate compilation unit than the composable function.
- There are **two** separate failures:
   1. If the `constructor` is private
   2. If the `constructor` is public and the `val` is private
- Only native and JS exhibit both failures. JVM only exhibits failure 1.
- It seems like you have to use the value in a `ComposeNode`'s `updater`, but that may not be required.

Filing issue upstream since you all maintain the JS & native bits of the compiler.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2613">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
