### ISSUE TITLE
How to create a box with a width greater than 256K

### ISSUE THREAD

**Issue by ShirasawaSama** [JetBrains/compose-multiplatform#2630]
For some reason, I need a box with width over 256000dp, but an error occurred when I tried the code below:

```kt
Box(Modifier.width(1000000000.dp))
```

Error:

```
java.lang.IllegalArgumentException: Can't represent a size of 1000000000 in Constraints
	at androidx.compose.ui.unit.Constraints$Companion.bitsNeedForSize(Constraints.kt:403)
	at androidx.compose.ui.unit.Constraints$Companion.createConstraints-Zbe2FdA$ui_unit(Constraints.kt:366)
	at androidx.compose.ui.unit.ConstraintsKt.Constraints(Constraints.kt:433)
	at androidx.compose.foundation.layout.SizeModifier.getTargetConstraints-OenEA2s(Size.kt:737)
	at androidx.compose.foundation.layout.SizeModifier.measure-3p2s80s(Size.kt:749)
	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:343)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1077)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1073)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2140)
```

Then I found that this is because the Constraints class uses a variable of type long to store four values.

I know that this is designed for performance and memory saving, but I think the value of only 18 bits allowed by compose is a little too small. CSS allows much more than this value.

_If there is no other way to solve it, I can only draw it manually through Canvas (calculate the display area manually). But I would rather use skiko to write programs._

**Comment by kirill-grouchnikov** [comment]
This is a design decision of core Compose, and it's quite unlikely to be changed in compose-jb

**Comment by ShirasawaSama** [comment]
> This is a design decision of core Compose, and it's quite unlikely to be changed in compose-jb

This is a pity. So there is no way to create such a wide box?

**Comment by pjBooms** [comment]
>This is a pity. So there is no way to create such a wide box?

It seems there is no way

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2630">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
