### ISSUE TITLE
ֵExample Todo doesn't run when install from dmg

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-multiplatform#2667]
Source Code: https://github.com/JetBrains/compose-jb/tree/update_versions_in_examples/examples/todoapp
Compose: 1.3.0-rc05
kotlin: 1.8.0

OS: Mac Os 12.5.1

Steps to reproduce:
- ./gradlew packageReleaseDmg
- try to install it and run it (it's in `/todoapp/desktop/build/compose/binaries/main-release/dmg/ComposeDesktopTodo-1.0.0.dmg`)
- or run the `todoapp/desktop/build/compose/binaries/main-release/app/ComposeDesktopTodo.app/Contents/MacOS/ComposeDesktopTodo`

Stacktrace:
```
Applications/ComposeDesktopTodo.app/Contents/MacOS/ComposeDesktopTodo ; exit;
Exception in thread "main" java.sql.SQLException: No suitable driver found for jdbc:sqlite:/var/folders/5s/l1n0y1pj1_14txws82__4fcm0000gn/T/ComposeTodoDatabase.db
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at com.squareup.sqldelight.sqlite.driver.ThreadedConnectionManager.getConnection(JdbcSqliteDriver.kt:65)
	at com.squareup.sqldelight.sqlite.driver.JdbcSqliteDriver.getConnection(JdbcSqliteDriver.kt)
	at com.squareup.sqldelight.sqlite.driver.JdbcDriver.connectionAndClose(JdbcDriver.kt:96)
	at com.squareup.sqldelight.sqlite.driver.JdbcDriver.execute$5d96a3e3(JdbcDriver.kt:107)
	at example.todo.database.database.TodoDatabaseImpl$Schema.create(TodoDatabaseImpl.kt:1052)
	at example.todo.common.ui.ShortcutHandlerKt.TodoDatabaseDriver(ShortcutHandler.kt:1012)
	at example.todo.desktop.MainKt.main(Main.kt:1052)
Failed to launch JVM
logout
```

Notes:
- Windows 11: installed from .msi - no issue when running the installed app.

**Comment by eymar** [comment]
Using other examples such as `issues` or `image-viewer` works when using
```
./gradlew packageDistributionForCurrentOS
``` 
But there is an issue with release distribution. I'll submit a separate issue.

**Comment by dima-avdeev-jb** [comment]
Relates to https://github.com/JetBrains/compose-jb/issues/2668

**Comment by muhammadyusuf-kurbonov** [comment]
Have the same with AppImage, Exe and Msi formats.

**Comment by dima-avdeev-jb** [comment]
Thanks, I add notice about your case in this issue: https://github.com/JetBrains/compose-jb/issues/2668
