### ISSUE TITLE
`rememberCursorPositionProvider` - get rid of the dependency on AWT

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2821]
Compose 1.3

When we use `Popup`, `TooltipPlacement.CursorPoint` or `rememberCursorPositionProvider`, and use it in an environment without AWT (tests, LWJGL), it should work as with the default configration with AWT:

```
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.TooltipArea
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.Button
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.*
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication

@OptIn(ExperimentalFoundationApi::class)
fun main() = singleWindowApplication {
    TooltipArea(
        tooltip = {
            // composable tooltip content
            Surface(
                modifier = Modifier.shadow(4.dp),
                color = Color(255, 255, 210),
                shape = RoundedCornerShape(4.dp)
            ) {
                Text(
                    text = "Tooltip",
                    modifier = Modifier.padding(10.dp)
                )
            }
        }
    ) {
        Button({}){}
    }
}
```

Now, it isn't supported if we run it in tests, and we can encounter a crash:
```
java.lang.IllegalStateException: CompositionLocal LayerContainer not provided
	at ???(Coroutine boundary.?(?)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:503)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$2.invokeSuspend(Recomposer.kt:883)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2.invokeSuspend(Recomposer.kt:882)
	at androidx.compose.ui.ComposeScene$6.invokeSuspend(ComposeScene.skiko.kt:242)
Caused by: java.lang.IllegalStateException: CompositionLocal LayerContainer not provided
	at androidx.compose.ui.awt.LocalLayerContainer_desktopKt$LocalLayerContainer$1.invoke(LocalLayerContainer.desktop.kt:23)
	at androidx.compose.ui.awt.LocalLayerContainer_desktopKt$LocalLayerContainer$1.invoke(LocalLayerContainer.desktop.kt:22)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
	at androidx.compose.runtime.ComposerImpl.resolveCompositionLocal(Composer.kt:1981)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:1949)
	at androidx.compose.ui.window.DesktopPopup_desktopKt.rememberCursorPositionProvider-B5uucgQ(DesktopPopup.desktop.kt:136)
	at androidx.compose.foundation.TooltipPlacement$CursorPoint.positionProvider(TooltipArea.desktop.kt:225)
	at androidx.compose.foundation.TooltipArea_desktopKt.TooltipArea(TooltipArea.desktop.kt:150)
	at androidx.compose.foundation.TooltipArea_desktopKt$TooltipArea$7.invoke(TooltipArea.desktop.kt)
	at androidx.compose.foundation.TooltipArea_desktopKt$TooltipArea$7.invoke(TooltipArea.desktop.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2375)
	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2666)
	at compose.components.MoreIconKt.MoreIcon(MoreIcon.kt:23)
	at compose.components.ToolVersionsGridKt$GridMenu$7.invoke(ToolVersionsGrid.kt:466)
	at compose.components.ToolVersionsGridKt$GridMenu$7.invoke(ToolVersionsGrid.kt:465)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at jewel.DropdownKt$Dropdown$7$1$1.invoke(Dropdown.kt:295)
	at jewel.DropdownKt$Dropdown$7$1$1.invoke(Dropdown.kt:295)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at jewel.DropdownKt.Dropdown-WSk2ftU(Dropdown.kt:293)
	at compose.jewel.MenuKt.Menu-7vwJh_E(Menu.kt:48)
	at compose.components.ToolVersionsGridKt.GridMenu(ToolVersionsGrid.kt:460)
	at compose.components.ToolVersionsGridKt.GridItem-DzVHIIc(ToolVersionsGrid.kt:339)
	at compose.components.ToolVersionsGridKt.access$GridItem-DzVHIIc(ToolVersionsGrid.kt:1)
	at compose.components.ToolVersionsGridKt$GridItem$10.invoke(ToolVersionsGrid.kt)
	at compose.components.ToolVersionsGridKt$GridItem$10.invoke(ToolVersionsGrid.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2375)
	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2666)
```

I wasn't able to reproduce it in tests, but the fix is to not use `LocalLayerContainer.current` in `rememberCursorPositionProvider`. 

For that, we either need to move to pure Compose implementation (using `Modifier.pointerInput`), or inject the global cursor provider via `Platform` class.

It is a part of 2 bigger works:
- moving all AWT dependencies from `ComposeScene` (the facade for Compose) into a higher level
- stabilizing `ui-test`

Reported [here](https://jetbrains.slack.com/archives/C01G87BMA2Z/p1677835531500279)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2821">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
