### ISSUE TITLE
Kotlin/JS + Compose: `java.lang.IllegalStateException: Validation failed in file` from task `compileDevelopmentExecutableKotlinJs`

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-multiplatform#3097]
```kotlin
// no error
key(Unit) {
    return@key
}
// error
// > Task :site:compileDevelopmentExecutableKotlinJs FAILED
// e: java.lang.IllegalStateException: Validation failed in file Test.kt
key(Unit) {
    if (true)
        return@key
}
```

**Comment by bitspittle** [comment]
```
java.lang.IllegalStateException: Validation failed in file Main.kt
	at org.jetbrains.kotlin.backend.common.IrValidator.error(IrValidator.kt:86)
	at org.jetbrains.kotlin.backend.common.IrValidator.access$error(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator$elementChecker$1.invoke(IrValidator.kt:90)
	at org.jetbrains.kotlin.backend.common.IrValidator$elementChecker$1.invoke(IrValidator.kt:90)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.ensureBound(CheckIrElementVisitor.kt:61)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.visitReturn(CheckIrElementVisitor.kt:242)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitReturn(IrElementVisitorVoid.kt:447)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.visitReturn(CheckIrElementVisitor.kt:24)
	at org.jetbrains.kotlin.backend.common.CheckIrElementVisitor.visitReturn(CheckIrElementVisitor.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrReturn.accept(IrReturn.kt:25)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:93)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitReturn(IrElementVisitorVoid.kt:449)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitReturn(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitReturn(IrElementVisitorVoid.kt:447)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitReturn(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitReturn(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrReturn.accept(IrReturn.kt:25)
	at org.jetbrains.kotlin.ir.expressions.IrContainerExpression.acceptChildren(IrContainerExpression.kt:28)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitContainerExpression(IrElementVisitorVoid.kt:270)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitContainerExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlock(IrElementVisitorVoid.kt:274)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlock(IrElementVisitorVoid.kt:272)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:22)
	at org.jetbrains.kotlin.ir.expressions.IrBranch.acceptChildren(IrBranch.kt:33)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBranch(IrElementVisitorVoid.kt:517)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBranch(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBranch(IrElementVisitorVoid.kt:515)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBranch(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBranch(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrBranch.accept(IrBranch.kt:26)
	at org.jetbrains.kotlin.ir.expressions.IrWhen.acceptChildren(IrWhen.kt:28)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitWhen(IrElementVisitorVoid.kt:513)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitWhen(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitWhen(IrElementVisitorVoid.kt:511)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitWhen(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitWhen(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrWhen.accept(IrWhen.kt:25)
	at org.jetbrains.kotlin.ir.expressions.IrContainerExpression.acceptChildren(IrContainerExpression.kt:28)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitContainerExpression(IrElementVisitorVoid.kt:270)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitContainerExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitComposite(IrElementVisitorVoid.kt:279)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitComposite(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitComposite(IrElementVisitorVoid.kt:277)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitComposite(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitComposite(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrComposite.accept(IrComposite.kt:22)
	at org.jetbrains.kotlin.ir.expressions.IrContainerExpression.acceptChildren(IrContainerExpression.kt:28)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitContainerExpression(IrElementVisitorVoid.kt:270)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitContainerExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlock(IrElementVisitorVoid.kt:274)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlock(IrElementVisitorVoid.kt:272)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:22)
	at org.jetbrains.kotlin.ir.expressions.IrContainerExpression.acceptChildren(IrContainerExpression.kt:28)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitContainerExpression(IrElementVisitorVoid.kt:270)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitContainerExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlock(IrElementVisitorVoid.kt:274)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlock(IrElementVisitorVoid.kt:272)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlock(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:22)
	at org.jetbrains.kotlin.ir.expressions.IrBranch.acceptChildren(IrBranch.kt:33)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBranch(IrElementVisitorVoid.kt:517)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBranch(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBranch(IrElementVisitorVoid.kt:515)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBranch(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBranch(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrBranch.accept(IrBranch.kt:26)
	at org.jetbrains.kotlin.ir.expressions.IrWhen.acceptChildren(IrWhen.kt:28)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitWhen(IrElementVisitorVoid.kt:513)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitWhen(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitWhen(IrElementVisitorVoid.kt:511)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitWhen(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitWhen(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrWhen.accept(IrWhen.kt:25)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.acceptChildren(IrBlockBody.kt:27)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBody(IrElementVisitorVoid.kt:209)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlockBody(IrElementVisitorVoid.kt:218)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlockBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlockBody(IrElementVisitorVoid.kt:216)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlockBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlockBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:24)
	at org.jetbrains.kotlin.ir.declarations.IrFunction.acceptChildren(IrFunction.kt:53)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:104)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitDeclaration(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunction(IrElementVisitorVoid.kt:129)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:175)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitSimpleFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:173)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitSimpleFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitSimpleFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:36)
	at org.jetbrains.kotlin.ir.expressions.IrFunctionExpression.acceptChildren(IrFunctionExpression.kt:28)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunctionExpression(IrElementVisitorVoid.kt:420)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunctionExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunctionExpression(IrElementVisitorVoid.kt:417)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunctionExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunctionExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrFunctionExpression.accept(IrFunctionExpression.kt:25)
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.acceptChildren(IrMemberAccessExpression.kt:73)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclarationReference(IrElementVisitorVoid.kt:224)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitDeclarationReference(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitMemberAccess(IrElementVisitorVoid.kt:230)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitMemberAccess(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunctionAccess(IrElementVisitorVoid.kt:236)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunctionAccess(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCall(IrElementVisitorVoid.kt:301)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitCall(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCall(IrElementVisitorVoid.kt:299)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitCall(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitCall(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:25)
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.acceptChildren(IrMemberAccessExpression.kt:70)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclarationReference(IrElementVisitorVoid.kt:224)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitDeclarationReference(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitMemberAccess(IrElementVisitorVoid.kt:230)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitMemberAccess(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCallableReference(IrElementVisitorVoid.kt:307)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitCallableReference(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunctionReference(IrElementVisitorVoid.kt:313)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunctionReference(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunctionReference(IrElementVisitorVoid.kt:310)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunctionReference(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunctionReference(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrFunctionReference.accept(IrFunctionReference.kt:22)
	at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.acceptChildren(IrMemberAccessExpression.kt:73)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclarationReference(IrElementVisitorVoid.kt:224)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitDeclarationReference(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitMemberAccess(IrElementVisitorVoid.kt:230)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitMemberAccess(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunctionAccess(IrElementVisitorVoid.kt:236)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunctionAccess(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCall(IrElementVisitorVoid.kt:301)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitCall(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitCall(IrElementVisitorVoid.kt:299)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitCall(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitCall(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:25)
	at org.jetbrains.kotlin.ir.expressions.IrTypeOperatorCall.acceptChildren(IrTypeOperatorCall.kt:33)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitExpression(IrElementVisitorVoid.kt:205)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitExpression(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitTypeOperator(IrElementVisitorVoid.kt:483)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitTypeOperator(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitTypeOperator(IrElementVisitorVoid.kt:481)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitTypeOperator(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitTypeOperator(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrTypeOperatorCall.accept(IrTypeOperatorCall.kt:30)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.acceptChildren(IrBlockBody.kt:27)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBody(IrElementVisitorVoid.kt:209)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlockBody(IrElementVisitorVoid.kt:218)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlockBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitBlockBody(IrElementVisitorVoid.kt:216)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlockBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitBlockBody(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:24)
	at org.jetbrains.kotlin.ir.declarations.IrFunction.acceptChildren(IrFunction.kt:53)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitDeclaration(IrElementVisitorVoid.kt:104)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitDeclaration(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFunction(IrElementVisitorVoid.kt:129)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:175)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitSimpleFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitSimpleFunction(IrElementVisitorVoid.kt:173)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitSimpleFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitSimpleFunction(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:36)
	at org.jetbrains.kotlin.ir.declarations.IrFile.acceptChildren(IrFile.kt:36)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:190)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitPackageFragment(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:200)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFile(IrValidator.kt:71)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:198)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFile(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitFile(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:30)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.acceptChildren(IrModuleFragment.kt:47)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitElement(IrValidator.kt:94)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:160)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitModuleFragment(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitModuleFragment(IrElementVisitorVoid.kt:158)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitModuleFragment(IrValidator.kt:64)
	at org.jetbrains.kotlin.backend.common.IrValidator.visitModuleFragment(IrValidator.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.accept(IrModuleFragment.kt:41)
	at org.jetbrains.kotlin.backend.common.phaser.DumperVerifierKt.validationCallback(DumperVerifier.kt:142)
	at org.jetbrains.kotlin.backend.common.phaser.DumperVerifierKt.validationCallback$default(DumperVerifier.kt:134)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$validateIrBeforeLowering$1.invoke(JsLoweringPhases.kt:119)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$validateIrBeforeLowering$1.invoke(JsLoweringPhases.kt:118)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeCustomJsModulePhase$1.invoke(JsLoweringPhases.kt:59)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeCustomJsModulePhase$1.invoke(JsLoweringPhases.kt:51)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
	at org.jetbrains.kotlin.ir.backend.js.CompilerWithICKt.lowerPreservingTags(compilerWithIC.kt:76)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compileIr(compiler.kt:148)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile(compiler.kt:68)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile$default(compiler.kt:49)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler$Ir2JsTransformer.lowerIr(K2JsIrCompiler.kt:99)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler$Ir2JsTransformer.makeJsCodeGeneratorAndDts(K2JsIrCompiler.kt:119)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler$Ir2JsTransformer.compileAndTransformIrNew(K2JsIrCompiler.kt:127)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:450)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:183)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImp
```

**Comment by bitspittle** [comment]
Originally filed at https://youtrack.jetbrains.com/issue/KT-58182
