### ISSUE TITLE
Crash on macOS: Library not loaded libharfbuzz.0.dylib

### ISSUE THREAD

**Issue by aivanovski** [JetBrains/compose-multiplatform#3107]
**Describe the bug**
macOS application crashes during startup, stacktrace is below. Jar file works fine.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.7.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): macOS Monterey 12.6,1
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): OpenJDK >= 17

**To Reproduce**
1. Checkout repo https://github.com/aivanovski/autokpass.git
2. Creaete package for macOS: `./gradlew packageDmg`
3. Run the application

**Additional context**
Stacktrace
```
Exception in thread "TimerQueue" java.lang.UnsatisfiedLinkError: /Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib: dlopen(/Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib, 0x0001): Library not loaded: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib'
  Referenced from: '/Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib'
  Reason: tried: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib' (no such file), '/usr/local/lib/libharfbuzz.0.dylib' (no such file), '/usr/lib/libharfbuzz.0.dylib' (no such file)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit$1.run(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit.<clinit>(Unknown Source)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getEventQueue(Unknown Source)
        at java.desktop/java.awt.EventQueue.invokeLater(Unknown Source)
        at java.desktop/javax.swing.SwingUtilities.invokeLater(Unknown Source)
        at java.desktop/javax.swing.Timer$1.run(Unknown Source)
        at java.desktop/javax.swing.Timer$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.desktop/javax.swing.Timer.post(Unknown Source)
        at java.desktop/javax.swing.TimerQueue.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.lwawt.macosx.LWCToolkit
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.desktop/javax.swing.UIManager.getSystemLookAndFeelClassName(Unknown Source)
        at org.jetbrains.skiko.Actuals_awtKt.setSystemLookAndFeel(Actuals.awt.kt:14)
        at org.jetbrains.skiko.Setup.init(Setup.kt:25)
        at org.jetbrains.skiko.Setup.init$default(Setup.kt:6)
        at org.jetbrains.skiko.Library.load(Library.kt:62)
        at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
        at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose(ConfigureSwingGlobalsForCompose.desktop.kt:49)
        at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose$default(ConfigureSwingGlobalsForCompose.desktop.kt:38)
        at androidx.compose.ui.window.Application_desktopKt.application(Application.desktop.kt:110)
        at androidx.compose.ui.window.Application_desktopKt.application$default(Application.desktop.kt:105)
        at com.github.ai.autokpass.MainKt.main(Main.kt:39)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib: dlopen(/Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib, 0x0001): Library not loaded: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib'
  Referenced from: '/Users/ivaali/Applications/autokpass-compose.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib'
  Reason: tried: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib' (no such file), '/usr/local/lib/libharfbuzz.0.dylib' (no such file), '/usr/lib/libharfbuzz.0.dylib' (no such file) [in thread "TimerQueue"]
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit$1.run(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit.<clinit>(Unknown Source)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getEventQueue(Unknown Source)
        at java.desktop/java.awt.EventQueue.invokeLater(Unknown Source)
        at java.desktop/javax.swing.SwingUtilities.invokeLater(Unknown Source)
        at java.desktop/javax.swing.Timer$1.run(Unknown Source)
        at java.desktop/javax.swing.Timer$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.desktop/javax.swing.Timer.post(Unknown Source)
        at java.desktop/javax.swing.TimerQueue.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Failed to launch JVM
```

**Comment by aivanovski** [comment]
> 

Nope. Sorry

**Comment by m-sasha** [comment]
Are you using harfbuzz in your app?

**Comment by aivanovski** [comment]
> Are you using harfbuzz in your app?

No, it is loaded by `sun.lwawt.macosx.LWCToolkit` and I don't have any idea why

**Comment by m-sasha** [comment]
@aivanovski Try making sure that the JVM you run gradle with when you run `./gradlew packageDmg` is the same JVM you run the jar with.

**Comment by aivanovski** [comment]
@m-sasha Check it, the result doesn't changed.

I've noticed that the file `libharfbuzz.dylib` is missing in the packaged application here: `autokpass-compose.app/Contents/runtime/Contents/Home/lib/`. Any ideas how to find the "code' responsible for that? Other libraries is there.

**Comment by aivanovski** [comment]
Tried to build this app [ScrcpyHub](https://github.com/kaleidot725/ScrcpyHub) and got similar stacktrace:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/ivaali/Applications/ScrcpyHub.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib: dlopen(/Users/ivaali/Applications/ScrcpyHub.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib, 0x0001): Library not loaded: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib'
  Referenced from: '/Users/ivaali/Applications/ScrcpyHub.app/Contents/runtime/Contents/Home/lib/libfontmanager.dylib'
  Reason: tried: '/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib' (no such file), '/usr/local/lib/libharfbuzz.0.dylib' (no such file), '/usr/lib/libharfbuzz.0.dylib' (no such file)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit$1.run(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.desktop/sun.lwawt.macosx.LWCToolkit.<clinit>(Unknown Source)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(Unknown Source)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.desktop/javax.swing.UIManager.getSystemLookAndFeelClassName(Unknown Source)
        at org.jetbrains.skiko.Actuals_awtKt.setSystemLookAndFeel(Actuals.awt.kt:14)
        at org.jetbrains.skiko.Setup.init(Setup.kt:25)
        at org.jetbrains.skiko.Setup.init$default(Setup.kt:6)
        at org.jetbrains.skiko.Library.load(Library.kt:62)
        at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
        at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose(ConfigureSwingGlobalsForCompose.desktop.kt:49)
        at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose$default(ConfigureSwingGlobalsForCompose.desktop.kt:38)
        at androidx.compose.ui.window.Application_desktopKt.application(Application.desktop.kt:110)
        at androidx.compose.ui.window.Application_desktopKt.application$default(Application.desktop.kt:105)
        at ScrcpyHubKt.main(ScrcpyHub.kt:24)
        at ScrcpyHubKt.main(ScrcpyHub.kt)
Failed to launch JVM
```

**Comment by m-sasha** [comment]
That seems to indicate that there's a problem with your setup. Maybe ask for assistance in our #compose-desktop slack channel? Someone may be familiar with this issue.

**Comment by aivanovski** [comment]
I checked applciation on regular macOS (without any enterprise restrictions) and it works. But looks like it still requires `libharfbuzz` installed as a dependency.

Application requires `libharfbuzz` located either in `/usr/local/opt/harfbuzz/lib'  or '/usr/local/lib` and it could be installed via brew. But in case if machine doesn't have root privileges brew installs it into `/usr/local/Homebrew/lib` and application will not be able to find it.

I assume none of Compose Desktop applications won't run without `libharfbuzz` preinstalled on the running machine, because it is not packaged into application by default. So, probably it is a bug.

**Comment by m-sasha** [comment]
I don't have `libharfbuzz` installed, and I can run Compose apps in Mac OS X just fine.

Either you're using an unusual JVM (or maybe functionality) that requires this library, or packaging works incorrectly on your system. It would really help if you could make a small example to reproduce the issue.

**Comment by aivanovski** [comment]
I use openjdk installed via brew. Could you please double check that `harfbuzz` is not installed on your machine?
```
$ brew list | grep harf
```

**Comment by m-sasha** [comment]
I don't have `harfbuzz` installed.

**Comment by aivanovski** [comment]
Could you tell me what JDK are you using then? I want to try the same version of JDK @m-sasha

**Comment by m-sasha** [comment]
I'm using corretto-17

**Comment by avently** [comment]
Are there any news about this problem? Wasn't really cool to receive stracktrace with this crash after release.

**Comment by AlexeyTsvetkov** [comment]
@avently "openjdk" from homebrew is a distribution built by homebrew people. They explicitly configured build to exclude a few libraries, so these libraries have to be provided by homebrew https://github.com/Homebrew/homebrew-core/blob/a90c3371e08e77f1e3ef788784fd517c7ff6478d/Formula/openjdk%4017.rb#L99

I'm not aware of any other OpenJDK distribution doing this on macOS.
I've just checked Amazon's Corretto, Eclipse Temurin (ex. AdoptOpenJDK), JetBrains Runtime, Azul OpenJDK. 
No one else except Homebrew distribution does this. The PR in Homebrew repo does not contain any reasoning https://github.com/Homebrew/homebrew-core/pull/117588

I'm not sure, what we can do except recommending to avoid Homebrew's distribution.

**Comment by avently** [comment]
@AlexeyTsvetkov ah, got it. Thank you for the answer! I'll just use another working JDK without worrying about openjdk@17 from homebrew.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3107">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
