### ISSUE TITLE
Unable to start project – Node error

### ISSUE THREAD

**Issue by xdevs23** [JetBrains/compose-multiplatform#3111]
**Describe the bug**
When starting a Compose for Web (Compose HTML) project, a Node error occurs, no matter what Node version I have installed.

**Affected platforms**
- Web (K/JS) - HTML based API

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Arch Linux (`Linux 6.3.0-nitrous-1 #1 SMP PREEMPT_DYNAMIC Thu Apr 27 22:58:15 CEST 2023 GNU/Linux`)
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 
```
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9)
OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode, sharing)
```

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a new Compose Multiplatform project in IntelliJ, selecting Web as platform.
2. Update to Kotlin 1.8.20 and Compose 1.4.0
3. Start the project (main fun)
4. See error: error:0308010C:digital envelope routines::unsupported

**Expected behavior**
I expected the dev server to start without issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/6959245/235303232-21252d28-591b-4b81-b39d-89c927ceaf44.png)
![image](https://user-images.githubusercontent.com/6959245/235303243-a99c1e75-92b0-4ab3-900e-8577fc40c803.png)

**Additional context**
It appears to be related to Webpack. Have you considered upgrading to Webpack 5? Webpack 4 seems pretty outdated.

```
Cause: node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/simao/workspace/website-2023/build/js/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/simao/workspace/website-2023/build/js/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/simao/workspace/website-2023/build/js/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/simao/workspace/website-2023/build/js/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/simao/workspace/website-2023/build/js/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/simao/workspace/website-2023/build/js/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/simao/workspace/website-2023/build/js/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/simao/workspace/website-2023/build/js/node_modules/loader-runner/lib/LoaderRunner.js:221:10) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

```
$ node --version
v19.9.0
```
```
openssl version  
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
```

build.gradle.kts:
```
plugins {
    kotlin("multiplatform")
    id("org.jetbrains.compose")
}

group = "dev.superboring"
version = "1.0-SNAPSHOT"

repositories {
    google()
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
}

kotlin {
    js(IR) {
        browser {
            testTask {
                testLogging.showStandardStreams = true
                useKarma {
                    useChromeHeadless()
                    useFirefox()
                }
            }
        }
        binaries.executable()
    }
    sourceSets {
        val jsMain by getting {
            dependencies {
                implementation(compose.html.core)
                implementation(compose.runtime)
            }
        }
        val jsTest by getting {
            dependencies {
                implementation(kotlin("test-js"))
            }
        }
    }
}
```

settings.gradle.kts:
```
pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }

    plugins {
        kotlin("multiplatform").version(extra["kotlin.version"] as String)
        id("org.jetbrains.compose").version(extra["compose.version"] as String)
    }
}

rootProject.name = "website-2023"
```

gradle.properties:
```
kotlin.code.style=official
kotlin.native.enableDependencyPropagation=false
kotlin.js.webpack.major.version=4
kotlin.version=1.8.20
agp.version=7.3.0
compose.version=1.4.0
```

IntelliJ version:
```
IntelliJ IDEA 2023.1 (Community Edition)
Build #IC-231.8109.175, built on March 29, 2023
Runtime version: 17.0.7+7 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 6.3.0-nitrous-1
GC: G1 Young Generation, G1 Old Generation
Memory: 1480M
Cores: 8
Registry:
    ide.intellij.laf.enable.animation=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.ideolog (203.0.30.0)
    dev.patrickpichler.darculaPitchBlackTheme (1.0.0)
    com.jgentil.theme.darcula_blacker (1.1)
    wu.seal.tool.jsontokotlin (3.7.4)
    com.mallowigi.idea (20.0.0)
    idea.plugin.protoeditor (231.8109.91)
    Docker (231.8109.150)
    tarn.gradle.dependencies (1.6.2)
    com.demonwav.minecraft-dev (2023.1-1.6.3)
    org.jetbrains.compose.desktop.ide (1.3.0)
    com.mallowigi (88.0.0)

Kotlin: 231-1.8.0-release-345-IJ8109.175
Current Desktop: GNOME
```

**Comment by CRamsan** [comment]
The problem does not seem to be Compose specific as I came across it on a project that had no compose code. The issue seems to be triggered when using Kotlin 1.8.20 and  webpack 4. I fixed this issue by setting webpack to 5 in  `gradle.properties`:
```kotlin.js.webpack.major.version=4```

**Comment by xdevs23** [comment]
Setting the version to 5 makes it incompatible with the compose setup.

**Comment by erikhuizinga** [comment]
Unless there is a stable workaround or fix, this is blocking me from upgrading to jb-compose 1.4 and probably newer.

**Comment by xdevs23** [comment]
I wanted to make a new project using Compose but am held back for over two months because of that.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3111">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
