### ISSUE TITLE
Web Canvas - NotImplementedError: AnnotatedString.transform

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#3139]
**Describe the bug**

When running my code in the browser, I get the following error:

```
"NotImplementedError: An operation is not implemented: implement native AnnotatedString.transform
    at transform (webpack-internal:///./kotlin/androidx-ui-text.js:15977:11)
    at toUpperCase (webpack-internal:///./kotlin/androidx-ui-text.js:1720:12)
    at sam$androidx_compose_ui_text_input_VisualTransformation$0.hexVisualTransformation$lambda [as function_1] (webpack-internal:///./kotlin/ht-material-shared.js:19048:33)
    at protoOf.filter_mummpk_k$ (webpack-internal:///./kotlin/ht-material-shared.js:19005:17)
    at filterWithValidation (webpack-internal:///./kotlin/androidx-foundation.js:28621:34)
    at CoreTextField$composable (webpack-internal:///./kotlin/androidx-foundation.js:21895:27)
    at BasicTextField$composable (webpack-internal:///./kotlin/androidx-foundation.js:20337:7)
    at eval (webpack-internal:///./kotlin/androidx-material3.js:19966:9)
    at protoOf.invoke_6harzl_k$ (webpack-internal:///./kotlin/androidx-runtime.js:35481:92)
    at eval (webpack-internal:///./kotlin/androidx-material3.js:19982:25)"
```

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.8.21
- Compose Multiplatform version*: 1.4.0

**Comment by eygraber** [comment]
Thank you, tested in 1.5.0-dev1043 and it works!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3139">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
