### ISSUE TITLE
Web Canvas - NotImplementedError: native atomic getAndIncrement

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#3143]
**Describe the bug**

When running my code in the browser, I get the following error:

```
"NotImplementedError: An operation is not implemented: Implement native atomic getAndIncrement
    at protoOf.getAndIncrement_alg4z6_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-foundation.js:34996:11)
    at protoOf.nextSelectableId_50rfx8_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-foundation.js:32056:33)
    at eval (webpack-internal:///./kotlin/compose-multiplatform-core-foundation.js:20110:34)
    at rememberSaveable$composable (webpack-internal:///./kotlin/compose-multiplatform-core-runtime-saveable.js:193:44)
    at BasicText$composable_0 (webpack-internal:///./kotlin/compose-multiplatform-core-foundation.js:19866:17)
    at Text$composable_0 (webpack-internal:///./kotlin/compose-multiplatform-core-material3.js:33295:7)
    at eval (webpack-internal:///./kotlin/ht-material-shared.js:16829:9)
    at protoOf.invoke_6harzl_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-runtime.js:35865:92)
    at eval (webpack-internal:///./kotlin/ht-material-shared.js:16845:25)
    at eval (webpack-internal:///./kotlin/compose-multiplatform-core-foundation.js:30106:9)"
```

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.8.21
- Compose Multiplatform version*: 1.5.0-dev1043

I can get this to happen by opening a Dialog from another Dialog.

**Comment by eymar** [comment]
https://github.com/JetBrains/compose-multiplatform-core/pull/570 
Should be fixed in the next build.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3143">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
