### ISSUE TITLE
NotImplementedError: operation is not implemented: implement native toLanguageTag

### ISSUE THREAD

**Issue by Him188** [JetBrains/compose-multiplatform#3250]
**Describe the bug**

```kotlin
onWasmReady {
    Window {
        AppTheme(useDarkTheme = isInDarkMode ?: isBrowserInDarkTheme()) {
            // ui code which I can't share, sorry.
        }
    }
}
```

When `isInDarkMode` changes (i.e. the whole page changes), the browser console logged this exception, and Compose went dead (no response).
```
"NotImplementedError: An operation is not implemented: implement native toLanguageTag
    at protoOf.toLanguageTag_xneel5_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui-text.js:16024:11)
    at protoOf.toLanguageTag_xneel5_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui-text.js:14844:34)
    at protoOf.equals (webpack-internal:///./kotlin/compose-multiplatform-core-ui-text.js:14853:17)
    at equals_1 (webpack-internal:///./kotlin/kotlin-kotlin-stdlib-js-ir.js:26373:19)
    at protoOf.orderedEquals_40uhas_k$ (webpack-internal:///./kotlin/kotlin-kotlin-stdlib-js-ir.js:4770:12)
    at protoOf.equals (webpack-internal:///./kotlin/kotlin-kotlin-stdlib-js-ir.js:19663:38)
    at equals_1 (webpack-internal:///./kotlin/kotlin-kotlin-stdlib-js-ir.js:26373:19)
    at protoOf.equals (webpack-internal:///./kotlin/compose-multiplatform-core-ui-text.js:14981:10)
    at equals_1 (webpack-internal:///./kotlin/kotlin-kotlin-stdlib-js-ir.js:26373:19)
    at protoOf.hasSameLayoutAffectingAttributes_h43d5o_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui-text.js:6753:10)"
```

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.5.0-dev1049
- OS version(s)* (required for Desktop and iOS issues): macOS
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

Sorry, the problem seemed hard for me to reproduce in a smaller project.

The page contains 1k lines of code and I did not see this error until some recent point.

**Expected behavior**

No Exception thrown.

**Screenshots**

<img width="474" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/12100985/6ff45106-457a-4000-8be4-007153e1b2e7">

**Additional context**

In `androidx.compose.ui.text.intl`:

```kotlin
package androidx.compose.ui.text.intl

internal class JsLocale(val locale: dynamic) : PlatformLocale {
    override val language: String
        get() = locale.languageCode!!

    override val script: String
        get() = locale.scriptCode!!

    override val region: String
        get() = locale.countryCode!!

    override fun toLanguageTag(): String = TODO("implement native toLanguageTag") // locale.toLanguageTag()
}

internal actual fun createPlatformLocaleDelegate(): PlatformLocaleDelegate =
    object : PlatformLocaleDelegate {
        override val current: LocaleList
            get() = LocaleList(listOf(Locale(JsLocale(Any()))))


        override fun parseLanguageTag(languageTag: String): PlatformLocale {
            return JsLocale(Any())
        }
    }

internal actual fun PlatformLocale.isRtl(): Boolean = false // TODO
```

`parseLanguageTag` always returns a new `JsLocale` regardless of what `languageTag` passed in. 
I think we should at least return some dummy value for `toLanguageTag` instaed of throwing an Error.

**Comment by MatkovIvan** [comment]
Already fixed in a separate branch (see https://github.com/JetBrains/compose-multiplatform-core/pull/561). Need to be merged to main

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3250">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
