### ISSUE TITLE
Prevent possible version mismatch between artifacts

### ISSUE THREAD

**Issue by MatkovIvan** [JetBrains/compose-multiplatform#3282]
Since compose is not a single artifact it's possible to face with non-obvious runtime errors when one part of libraries doesn't match another one.
For example:
1. clone https://github.com/JetBrains/compose-multiplatform-template
2. replace compose version in `shared/build.gradle.kts` but not in `desktopApp/build.gradle.kts` (`compose.desktop.currentOs`)
3. run desktop app
It will lead runtime crash because skiko binary/native jni code doesn't match kotlin code. It happens because it placed in different jars without guarantee of matching their versions.

```kt
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skiko.context.MetalContextHandler.makeMetalContext(long)'
	at org.jetbrains.skiko.context.MetalContextHandler.makeMetalContext(Native Method)
	at org.jetbrains.skiko.context.MetalContextHandler.makeContext(MetalContextHandler.kt:84)
	at org.jetbrains.skiko.context.MetalContextHandler.initContext(MetalContextHandler.kt:25)
```

Compose should enforce integrity here.

Try 1:
~~Use hard dependencies `[1.0]` syntax from [POM Reference](https://maven.apache.org/pom.html#dependency-version-requirement-specification)~~
- https://github.com/JetBrains/compose-multiplatform-core/pull/607 

It doesn't work because gradle ignores this rule.

Try 2:
Introduce dependency substitution rule in our plugin to dynamically replace common artifact to OS/arch specific.
- TBD

**Comment by igordmn** [comment]
> It will lead runtime crash
The crash:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skiko.context.MetalContextHandler.makeMetalContext(long)'
	at org.jetbrains.skiko.context.MetalContextHandler.makeMetalContext(Native Method)
	at org.jetbrains.skiko.context.MetalContextHandler.makeContext(MetalContextHandler.kt:84)
	at org.jetbrains.skiko.context.MetalContextHandler.initContext(MetalContextHandler.kt:25)
```

// Try 2:
After this we need to deprecate `compose.desktop.currentOs`, and can more easely resolve [this issue](https://github.com/JetBrains/compose-multiplatform/issues/497)

**Comment by igordmn** [comment]
> Introduce dependency substitution rule in our plugin to dynamically replace common artifact to OS/arch specific.

It is better to try to find a way, so it works without Compose Gradle plugin. Maybe default Gradle/Maven has something for this case.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3282">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
