### ISSUE TITLE
Exception that crashes application when PC was in idle for a while

### ISSUE THREAD

**Issue by Walingar** [JetBrains/compose-multiplatform#3296]
**Describe the bug**
After some time when PC was idle, an exception occurs.
![image](https://github.com/JetBrains/compose-multiplatform/assets/23081446/118bea64-218f-4156-8e52-320e80dc0b50)
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read the array length because "elementData" is null
	at java.base/java.util.ArrayList.add(ArrayList.java:453)
	at java.base/java.util.ArrayList.add(ArrayList.java:467)
	at androidx.compose.ui.CommandList.add(CommandList.desktop.kt:49)
	at androidx.compose.ui.ComposeScene$attach$4.invoke(ComposeScene.skiko.kt:279)
	at androidx.compose.ui.ComposeScene$attach$4.invoke(ComposeScene.skiko.kt:279)
        ....
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4f655745, SwingDispatcher@647b3f51]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "original" is null
	at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
	at java.base/java.util.ArrayList.toArray(ArrayList.java:369)
	at java.base/java.util.ArrayList.addAll(ArrayList.java:670)
	at androidx.compose.ui.CommandList.perform(CommandList.desktop.kt:62)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:709)
        ...
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1588d015, SwingDispatcher@647b3f51]
```

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*:  1.4.0
- OS version(s): Windows 11
- JDK (for desktop issues): JDK 17 adopt

**To Reproduce**
This is not really reproducible

**Comment by TanotiCoder** [comment]
Hey @Walingar , you should consider implementing null safety or incorporating default values.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3296">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
