### ISSUE TITLE
Make a guard when users call `ComposeScene(coroutineContext = UnconfinedTestDispatcher, invalidate = { scene.render() })`

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3352]
Compose ec499cca

Code:
```
    @Test
    @OptIn(ExperimentalCoroutinesApi::class)
    fun whenNotHoveredShouldNeverCommit() = runTest(UnconfinedTestDispatcher()) {
//    fun whenNotHoveredShouldNeverCommit() = kotlinx.coroutines.runBlocking(Dispatchers.Main) { // this works

        val component = IconPlatform()
        val surface = Surface.makeRasterN32Premul(100, 100)
        var scene: ComposeScene? = null

        scene = ComposeScene(platform = component, invalidate = {
            scene?.render(surface.canvas, 1)
        }, coroutineContext = coroutineContext)

        val iconState = mutableStateOf(PointerIcon.Text)

        val recomposeChannel = Channel<Int>(Channel.CONFLATED) // helps with waiting for recomposition
        var count = 0
        try {
            scene.constraints = Constraints(maxWidth = surface.width, maxHeight = surface.height)
            scene.setContent {
                Box(
                    modifier = Modifier.size(100.dp, 100.dp).pointerHoverIcon(PointerIcon.Default)
                ) {
                    Box(
                        modifier = Modifier.pointerHoverIcon(iconState.value).size(30.dp, 30.dp)
                    )
                }
                recomposeChannel.trySend(++count)
            }
            assertThat(recomposeChannel.receive()).isEqualTo(1)
            assertThat(component._pointerIcon).isEqualTo(null)

            // No move, not hovered. No pointer icon change expected
            iconState.value = PointerIcon.Crosshair
            assertThat(recomposeChannel.receive()).isEqualTo(2)
            assertThat(component._pointerIcon).isEqualTo(null)

            // Move, but not hovered. Pointer Icon should be Default
            scene.sendPointerEvent(PointerEventType.Move, Offset(90f, 95f))
            assertThat(component._pointerIcon).isEqualTo(PointerIcon.Default)
        } finally {
            val toClose = scene
            scene = null // otherwise, invalidate (scene?.render...) crashes
            toClose.close()
        }
    }


```

It crashes with:
```
Compose Runtime internal error. Unexpected or incorrect use of the Compose internal runtime API (Cannot start a writer when a reader is pending). Please report to Google or use https://goo.gle/compose-feedback
androidx.compose.runtime.ComposeRuntimeError: Compose Runtime internal error. Unexpected or incorrect use of the Compose internal runtime API (Cannot start a writer when a reader is pending). Please report to Google or use https://goo.gle/compose-feedback
	at app//androidx.compose.runtime.ComposerKt.composeRuntimeError(Composer.kt:4558)
	at app//androidx.compose.runtime.SlotTable.openWriter(SlotTable.kt:3479)
	at app//androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:1315)
	at app//androidx.compose.ui.ComposeScene.close(ComposeScene.skiko.kt:243)
	at app//androidx.compose.ui.input.pointer.PointerIconTest$whenNotHoveredShouldNeverCommit$1.invokeSuspend(PointerIconTest.kt:276)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
	at app//kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at app//kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at app//kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at app//kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:513)
	at app//kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive(AbstractChannel.kt:908)
	at app//kotlinx.coroutines.channels.ConflatedChannel.offerInternal(ConflatedChannel.kt:56)
	at app//kotlinx.coroutines.channels.AbstractSendChannel.trySend-JP2dKIU(AbstractChannel.kt:155)
	at app//androidx.compose.ui.input.pointer.PointerIconTest$whenNotHoveredShouldNeverCommit$1$2.invoke(PointerIconTest.kt:260)
	at app//androidx.compose.ui.input.pointer.PointerIconTest$whenNotHoveredShouldNeverCommit$1$2.invoke(PointerIconTest.kt:252)
	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at app//androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
	at app//androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2469)
	at app//androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2738)
	at app//androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3353)
	at app//androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3304)
	at app//androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
	at app//androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
	at app//androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
	at app//androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:569)
	at app//androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
	at app//androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at app//androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at app//androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:408)
	at app//androidx.compose.ui.input.pointer.PointerIconTest$whenNotHoveredShouldNeverCommit$1$1.invoke(PointerIconTest.kt:243)
	at app//androidx.compose.ui.input.pointer.PointerIconTest$whenNotHoveredShouldNeverCommit$1$1.invoke(PointerIconTest.kt:242)
	at app//androidx.compose.ui.ComposeScene.invalidateIfNeeded(ComposeScene.skiko.kt:135)
	at app//androidx.compose.ui.ComposeScene.access$invalidateIfNeeded(ComposeScene.skiko.kt:59)
	at app//androidx.compose.ui.ComposeScene$snapshotChanges$1.invoke(ComposeScene.skiko.kt:250)
	at app//androidx.compose.ui.ComposeScene$snapshotChanges$1.invoke(ComposeScene.skiko.kt:250)
	at app//androidx.compose.ui.CommandList.add(CommandList.desktop.kt:51)
	at app//androidx.compose.ui.ComposeScene$attach$4.invoke(ComposeScene.skiko.kt:266)
	at app//androidx.compose.ui.ComposeScene$attach$4.invoke(ComposeScene.skiko.kt:266)
	at app//androidx.compose.ui.platform.SkiaBasedOwner$snapshotObserver$1.invoke(SkiaBasedOwner.skiko.kt:154)
	at app//androidx.compose.ui.platform.SkiaBasedOwner$snapshotObserver$1.invoke(SkiaBasedOwner.skiko.kt:153)
	at app//androidx.compose.runtime.snapshots.SnapshotStateObserver.sendNotifications(SnapshotStateObserver.kt:81)
	at app//androidx.compose.runtime.snapshots.SnapshotStateObserver.access$sendNotifications(SnapshotStateObserver.kt:41)
	at app//androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke(SnapshotStateObserver.kt:48)
	at app//androidx.compose.runtime.snapshots.SnapshotStateObserver$applyObserver$1.invoke(SnapshotStateObserver.kt:46)
	at app//androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot(Snapshot.kt:1825)
	at app//androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot(Snapshot.kt:1840)
	at app//androidx.compose.runtime.snapshots.SnapshotKt.access$advanceGlobalSnapshot(Snapshot.kt:1)
	at app//androidx.compose.runtime.snapshots.Snapshot$Companion.sendApplyNotifications(Snapshot.kt:584)
	at app//androidx.compose.ui.platform.GlobalSnapshotManager$ensureStarted$1.invokeSuspend(GlobalSnapshotManager.desktop.kt:47)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop@17.0.6/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop@17.0.6/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop@17.0.6/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop@17.0.6/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base@17.0.6/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.6/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop@17.0.6/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop@17.0.6/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@17.0.6/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@17.0.6/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@17.0.6/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@17.0.6/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@17.0.6/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
https://teamcity.jetbrains.com/buildConfiguration/JetBrainsPublicProjects_Compose_DesktopTestsForPullRequests/4230148?expandPull+Request+Details=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true

Because of the race:
```
ui thread -> GlobalSnapshotManager -> scene.invalidate -> scene.render
test thread -> scene.render
```

We need inform users somehow, that there is a race.

One of the solutions - add a guard that prohibits calling render inside invalidate. But there can be valid cases, we need to investigate

**Comment by igordmn** [comment]
See the reason [here](https://github.com/JetBrains/compose-multiplatform-core/pull/675#issuecomment-1636228443).

Probably we need a guard that prohibits calling `render` inside `invalidate`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3352">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
