### ISSUE TITLE
Navigation stack with viewmodel

### ISSUE THREAD

**Issue by dQqAn** [JetBrains/compose-multiplatform#3398]
[Navigation stack](https://github.com/JetBrains/compose-multiplatform/blob/336ba2c7a1ed9c8bff484dd32730ff9b4b2785f4/examples/imageviewer/shared/src/commonMain/kotlin/example/imageviewer/ImageViewer.common.kt#L40)
I try to write this code with viewmodel but i have some errors. 

First scenario: 
```kotlin
val viewModel = LoginViewModel()
//         . u can check the navigation stack: https://github.com/JetBrains/compose-multiplatform/blob/336ba2c7a1ed9c8bff484dd32730ff9b4b2785f4/examples/imageviewer/shared/src/commonMain/kotlin/example/imageviewer/ImageViewer.common.kt#L40
//         .
    { (_, page) ->
        when (page) {

            is SignInPage -> {
                SignInContent(viewModel, onNavigationClick = { navigationStack.push(SignUpPage()) })
            }

            is SignUpPage -> {
                SignUpContent(onNavigationClick = { navigationStack.back() })
            }

        }
    }
``` 

This is the first error scenario :
in addition: According to the error we can't use remember/saveable with viewmodel.
```powershell
FATAL EXCEPTION: main
                 Process: com.example.android, PID: 6647
                 java.lang.IllegalArgumentException: Failed requirement.
                 	at androidx.compose.runtime.saveable.ListSaverKt$listSaver$1.invoke(ListSaver.kt:39)
                 	at androidx.compose.runtime.saveable.ListSaverKt$listSaver$1.invoke(ListSaver.kt:33)
                 	at androidx.compose.runtime.saveable.SaverKt$Saver$1.save(Saver.kt:66)
                 	at androidx.compose.runtime.saveable.RememberSaveableKt$rememberSaveable$1$valueProvider$1.invoke(RememberSaveable.kt:102)
                 	at androidx.compose.runtime.saveable.RememberSaveableKt$rememberSaveable$1.invoke(RememberSaveable.kt:105)
                 	at androidx.compose.runtime.saveable.RememberSaveableKt$rememberSaveable$1.invoke(RememberSaveable.kt:99)
                 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
                 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1105)
                 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:820)
                 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:842)
                 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:994)
                 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1099)
                 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
                 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:181)
                 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
                 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1174)
                 	at android.view.View.dispatchAttachedToWindow(View.java:20753)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2613)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
                 	at android.view.Choreographer.doFrame(Choreographer.java:780)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7839)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

The second scenario: 
```kotlin

viewModel.viewModelScope.launch {
        viewModel.page.collect {
            when(it){
                is Pages.SignIn->{
                    SignInContent(viewModel, onNavigationClick = { viewModel.setPage(Pages.SignUp)})
                }
                is Pages.SignUp->{
                    SignUpContent(onNavigationClick = { viewModel.setPage(Pages.SignIn) })
                }
            }
        }
    }
``` 

This is the second error scenario :
```powershell
@Composable invocations can only happen from the context of a @Composable function
``` 

How i can use navigation stack with viewmodel? Thanks in advance.
btw, what can i do instead of viewmodel? Do you have any suggestions?

**Comment by dQqAn** [comment]
I found the problem, sorry...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3398">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
