### ISSUE TITLE
 NavigationRail error in some devices 

### ISSUE THREAD

**Issue by helmysaeed** [JetBrains/compose-multiplatform#3399]
Exception in thread "AWT-EventQueue-0" kotlinx.coroutines.CompletionHandlerException: Exception in resume onCancellation handler for CancellableContinuation(DispatchedContinuation[FlushCoroutineDispatcher@232812c8, Continuation at androidx.compose.foundation.gestures.PressGestureScopeImpl.reset(TapGestureDetector.kt:365)@191ad5f]){Completed}@6fc20858
	at kotlinx.coroutines.CancellableContinuationImpl.callOnCancellation(CancellableContinuationImpl.kt:264)
	at kotlinx.coroutines.CompletedContinuation.invokeHandlers(CancellableContinuationImpl.kt:659)
	at kotlinx.coroutines.CancellableContinuationImpl.cancelCompletedResult$kotlinx_coroutines_core(CancellableContinuationImpl.kt:180)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:62)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:57)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:91)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:37)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeBridge$coroutineExceptionHandler$1@356afe9b, androidx.compose.runtime.BroadcastFrameClock@8c00ccc, StandaloneCoroutine{Cancelling}@27a2cd0, FlushCoroutineDispatcher@232812c8]
Caused by: java.lang.IllegalStateException: This mutex is not locked
	at kotlinx.coroutines.sync.MutexImpl.unlock(Mutex.kt:207)
	at kotlinx.coroutines.sync.MutexImpl$CancellableContinuationWithOwner$tryResume$token$1.invoke(Mutex.kt:255)
	at kotlinx.coroutines.sync.MutexImpl$CancellableContinuationWithOwner$tryResume$token$1.invoke(Mutex.kt:252)
	at kotlinx.coroutines.CancellableContinuationImpl.callOnCancellation(CancellableContinuationImpl.kt:259)
	... 23 more

- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*:  1.4 , 1.4.1 , 1.5.0-dev1114
windows 10 
- JDK (for desktop issues):  18.2

**Comment by pjBooms** [comment]
Can you provide a reproducible sample for this?

**Comment by helmysaeed** [comment]
> Can you provide a reproducible sample for this?

@Composable
fun navSide(
    department: (String) -> Unit,
    selectedIndexClick: (String) -> Unit,
    selectedIndex: String,
  //  selectedTab: (String)->Unit
)
{

       val item=  mutableListOf(Nav( localization.sales,docType.sales,icon = Icons.Outlined.PointOfSale)
           ,Nav( localization.salesReturn,docType.salesReturn,Icons.Outlined.SwapVert)
           , Nav( localization.purchases,docType.purches ,icon = Icons.Outlined.ShoppingBasket),
           Nav( localization.purchasesReturn,docType.purchesReturn,Icons.Outlined.SwapHoriz),
                   Nav( localization.items,docType.items,icon = Icons.Outlined.Inventory) ,Nav( localization.inventory,docType.inventory,icon = Icons.Outlined.Inventory2 ),
        Nav(localization.partner,docType.partner,Icons.Outlined.Groups),Nav( localization.finance,docType.finincial,Icons.Outlined.Analytics),
                   Nav( localization.security,docType.security ,icon = Icons.Outlined.Security))
    Column(modifier = Modifier ) {

        NavigationRail(

            containerColor = Color.Transparent,

            content = {

                item.forEachIndexed {index,it->
                    NavigationRailItem(

                        onClick = {
                     //   selectedTab("0")

                        selectedIndexClick(index.toString())

                        department(it.number)

                    } ,
                        enabled = true

                         ,
                        selected =  index.toString()==selectedIndex,

                        icon = { it.icon?.let { it1 -> Icon(imageVector = it1,contentDescription = "") } },

                        label = {Text(it.key)  },



                    )
                }
            }
        )

          //  Divider()


     /*   ModalNavigationDrawer(
            drawerState = drawerState,
            drawerContent = {
                Text("meedd")
           *//*     NavigationDrawerItem(label = { Text(text = "me")}, selected = true , onClick = {
                    scope.launch {
                        drawerState.close()

                    }
                })*//*
            }) {

        }*/


    }

}

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3399">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
