### ISSUE TITLE
`IdSignature` clash with Kotlin 1.9.0, serialization, and Compose compiler 1.5.0

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/compose-multiplatform#3418]
Upon upgrading to Kotlin 1.9 and JB Compose compiler 1.5.0, we get the following build failure:
`e: java.lang.IllegalStateException: IdSignature clash: app.cash.redwood.ui/Dp|null[0]; Existed declaration CLASS CLASS name:Dp modality:FINAL visibility:public superTypes:[kotlin.Any] clashed with new CLASS CLASS name:Dp modality:FINAL visibility:public superTypes:[kotlin.Any]`

<details>
<summary>Full stack trace</summary>
<pre>
e: java.lang.IllegalStateException: IdSignature clash: app.cash.redwood.ui/Dp|null[0]; Existed declaration CLASS CLASS name:Dp modality:FINAL visibility:public superTypes:[kotlin.Any] clashed with new CLASS CLASS name:Dp modality:FINAL visibility:public superTypes:[kotlin.Any]
        at org.jetbrains.kotlin.ir.backend.js.lower.serialization.ir.JsUniqIdClashTracker.commit(JsDeclarationTable.kt:27)
        at org.jetbrains.kotlin.backend.common.serialization.GlobalDeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:48)
        at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.computeSignatureByDeclaration(DeclarationTable.kt:83)
        at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.signatureByDeclaration(DeclarationTable.kt:92)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.protoIdSignature(IrFileSerializer.kt:293)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrSymbol(IrFileSerializer.kt:356)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeSimpleType(IrFileSerializer.kt:392)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrTypeData(IrFileSerializer.kt:429)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrType(IrFileSerializer.kt:495)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeExpression(IrFileSerializer.kt:1007)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrVariable(IrFileSerializer.kt:1228)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1327)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeStatement(IrFileSerializer.kt:1067)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeBlockBody(IrFileSerializer.kt:504)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeStatement(IrFileSerializer.kt:1073)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrStatementBody(IrFileSerializer.kt:181)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFunctionBase(IrFileSerializer.kt:1153)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFunction(IrFileSerializer.kt:1166)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1323)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrClass(IrFileSerializer.kt:1246)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1331)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrClass(IrFileSerializer.kt:1246)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeDeclaration(IrFileSerializer.kt:1331)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFileImpl(IrFileSerializer.kt:1432)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.access$serializeIrFileImpl(IrFileSerializer.kt:117)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer$serializeIrFile$1.invoke(IrFileSerializer.kt:1412)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer$serializeIrFile$1.invoke(IrFileSerializer.kt:1411)
        at org.jetbrains.kotlin.backend.common.serialization.signature.PublicIdSignatureComputer.inFile(IdSignatureSerializer.kt:45)
        at org.jetbrains.kotlin.backend.common.serialization.signature.IdSignatureSerializer.inFile(IdSignatureSerializer.kt:229)
        at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.inFile(DeclarationTable.kt:62)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileSerializer.serializeIrFile(IrFileSerializer.kt:1411)
        at org.jetbrains.kotlin.backend.common.serialization.IrModuleSerializer.serializeIrFile(IrModuleSerializer.kt:28)
        at org.jetbrains.kotlin.backend.common.serialization.IrModuleSerializer.serializedIrModule(IrModuleSerializer.kt:35)
        at org.jetbrains.kotlin.ir.backend.js.KlibKt.serializeModuleIntoKlib(klib.kt:655)
        at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib(klib.kt:138)
        at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib$default(klib.kt:121)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.processSourceModule(K2JsIrCompiler.kt:466)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:276)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:213)
        at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:84)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:476)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:399)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:280)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:124)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:106)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:569)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1689)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)
</pre>
</details>

The entirety of the Kotlin source code which causes this is:
```kotlin
@Serializable
class Dp

@Serializable
class Margin(val start: Dp)
```

Compilation will succeed if:
- `@Serializable` is removed from `Margin` type
- Compose plugin is removed from `build.gradle`

I'm not sure whether the Compose compiler or the Serialization plugin is to blame. I'm starting here with Compose.

A minimally-reproducing sample is available here: [compose-js-id-sig-clash.zip](https://github.com/JetBrains/compose-multiplatform/files/12184730/compose-js-id-sig-clash.zip). A simple `./gradlew assemble` will trigger the failure.

**Comment by dima-avdeev-jb** [comment]
Thanks!
Is it JS only problem ?

**Comment by eymar** [comment]
I believe this workaroudn could help:

```kotlin
tasks.withType<KotlinJsCompile>().configureEach {
            kotlinOptions.freeCompilerArgs += listOf(
                "-Xklib-enable-signature-clash-checks=false",
            )
        }
```

other target simply don't care about Signature clashes.

**Comment by JakeWharton** [comment]
> Thanks! Is it JS only problem ?

Yep. All other targets (JVM, bunch of native) succeed.

> I believe this workaroudn could help:

It does. Thanks!

For now this module can thankfully run without the Compose compiler applied to work around the problem as well. It only has types which are annotated as `@Stable` and `@Immutable` and does not contain actual `@Composable`s, at least for now.

**Comment by chrisnolet** [comment]
I had this issue with Kotlin 1.9.0 and Compose 1.5.0-dev1114.

It appears to be fixed with Compose 1.5.0-rc01.

**Comment by eymar** [comment]
It's fixed in 1.5.0-rc01 by adding a workaround (https://github.com/JetBrains/compose-multiplatform/issues/3418#issuecomment-1655953340) to Compose Gradle plugin.

But if the Compose gradle plugin is not used, than that workaround has to be added manually.

**Comment by Ayfri** [comment]
Thanks everyone, I was having a hard time figuring out what was the error !

**Comment by JakeWharton** [comment]
We ran into these IdSignature problems again while attempting the 1.6 upgrade. The workaround above does work, but I don't fully understand its implications. Are we are risk without these checks? Should I create a minimally-reproducing sample for the new clash and file a new bug?

**Comment by eymar** [comment]
> We ran into these IdSignature problems again while attempting the 1.6 upgrade (note: we do not use the JB Compose Gradle plugin). The workaround above does work, but I don't fully understand its implications. Are we are risk without these checks? Should I create a minimally-reproducing sample for the new clash and file a new bug?

JB Compose gradle plugin disables the signature clash checker under the hood. So you can disable it itoo.
If k/native and k/jvm had Signature Clash checker, they would fail too. Compose compiler plugin creates symbol duplicates (I guess it was more convenient to create a new (duplicate) symbol when needed than to find  an existing one).

**Comment by JakeWharton** [comment]
Ok, thanks. That's reassuring. I will disable it in our Gradle plugins that configure the Compose compiler!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3418">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
