### ISSUE TITLE
Compose Desktop is not running on Mac 10.13 again

### ISSUE THREAD

**Issue by mshdabiola** [JetBrains/compose-multiplatform#3460]
Exception in thread "main" java.lang.NullPointerException: Parameter specified as non-null is null: method org.jetbrains.skiko.MetalAdapter.<init>, parameter name
	at org.jetbrains.skiko.MetalAdapter.<init>(MetalApi.kt)
	at org.jetbrains.skiko.MetalApiKt.chooseMetalAdapter(MetalApi.kt:14)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.<init>(MetalRedrawer.kt:64)
	at org.jetbrains.skiko.Actuals_awtKt$makeDefaultRenderFactory$1.createRedrawer(Actuals.awt.kt:26)
	at org.jetbrains.skiko.SkiaLayer$redrawerManager$1.invoke(SkiaLayer.awt.kt:304)
	at org.jetbrains.skiko.SkiaLayer$redrawerManager$1.invoke(SkiaLayer.awt.kt:302)
	at org.jetbrains.skiko.redrawer.RedrawerManager.findNextWorkingRenderApi(RedrawerManager.kt:31)
	at org.jetbrains.skiko.SkiaLayer.init(SkiaLayer.awt.kt:334)
	at org.jetbrains.skiko.SkiaLayer.addNotify(SkiaLayer.awt.kt:161)
	at androidx.compose.ui.awt.WindowComposeBridge$component$1.addNotify(WindowComposeBridge.desktop.kt:45)
	at java.desktop/java.awt.Container.addNotify(Unknown Source)
	at java.desktop/javax.swing.JComponent.addNotify(Unknown Source)
	at androidx.compose.ui.awt.ComposeWindowDelegate$_pane$1.addNotify(ComposeWindowDelegate.desktop.kt:84)
	at java.desktop/java.awt.Container.addNotify(Unknown Source)
	at java.desktop/javax.swing.JComponent.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Unknown Source)
	at java.desktop/javax.swing.JComponent.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Unknown Source)
	at java.desktop/javax.swing.JComponent.addNotify(Unknown Source)
	at java.desktop/javax.swing.JRootPane.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Unknown Source)
	at java.desktop/java.awt.Window.addNotify(Unknown Source)
	at java.desktop/java.awt.Frame.lambda$addNotify$0(Unknown Source)
	at java.desktop/sun.awt.SunToolkit.lambda$performWithTreeLock$1(Unknown Source)
	at java.desktop/sun.awt.SunToolkit.performOnMainThreadIfNeeded(Unknown Source)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(Unknown Source)
	at java.desktop/java.awt.Frame.addNotify(Unknown Source)
	at java.desktop/java.awt.Window.lambda$pack$1(Unknown Source)
	at java.desktop/sun.awt.SunToolkit.performOnMainThreadIfNeeded(Unknown Source)
	at java.desktop/java.awt.Window.pack(Unknown Source)
	at androidx.compose.ui.util.Windows_desktopKt.setSizeImpl-6HolHcs(Windows.desktop.kt:115)
	at androidx.compose.ui.util.Windows_desktopKt.setSizeSafely-hQcJfNw(Windows.desktop.kt:54)
	at androidx.compose.ui.window.Window_desktopKt$Window$5.invoke(Window.desktop.kt:236)
	at androidx.compose.ui.window.Window_desktopKt$Window$5.invoke(Window.desktop.kt:173)
	at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Window.desktop.kt:422)
	at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Window.desktop.kt:416)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(AwtWindow.desktop.kt:82)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(AwtWindow.desktop.kt:80)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(UpdateEffect.desktop.kt:59)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(UpdateEffect.desktop.kt:55)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2300)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:466)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:234)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke$performUpdate(UpdateEffect.desktop.kt:55)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(UpdateEffect.desktop.kt:64)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(UpdateEffect.desktop.kt:47)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1041)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version 1.9.0 
- Compose Multiplatform version 1.4.3
- OS version(s) macOS 10.13
- OS architecture x86 
- JDK (for desktop issues):

**Comment by eymar** [comment]
You say: "Compose Desktop is not running on Mac 10.13 again". Did it work for you previously? With what versions (compose/kotlin/macos)?

What is your JDK version?
What hardware do you use to run the app?
Do you have a chance to try it with more recent macOs versions?

**Comment by eymar** [comment]
https://github.com/JetBrains/skiko/issues/784 - similar.
Do you run MacOs in a virtual machine?

**Comment by mshdabiola** [comment]
> https://github.com/JetBrains/skiko/issues/784 - similar.
> 
> Do you run MacOs in a virtual machine? 

No, am not

**Comment by mshdabiola** [comment]
> You say: "Compose Desktop is not running on Mac 10.13 again". Did it work for you previously? With what versions (compose/kotlin/macos)?
> 
> 
> 
> What is your JDK version?
> 
> What hardware do you use to run the app?
> 
> Do you have a chance to try it with more recent macOs versions? 
> 
> 

Jdk 17
MacBook Pro 10.13


Is working fine with compose 1.4.0/Kotlin 1.8.10

But crash when I upgrade to 1.4.3 /Kotlin 1.9.0

**Comment by elijah-semyonov** [comment]
Same as https://github.com/JetBrains/skiko/issues/784

**Comment by elijah-semyonov** [comment]
This change in skiko reproduces the issue.

```
JNIEXPORT jlong JNICALL Java_org_jetbrains_skiko_MetalApiKt_chooseAdapter(
    JNIEnv *env, jobject obj, jlong adapterPriority)
{
    @autoreleasepool {
        return 0;
    }
}
```

**Comment by elijah-semyonov** [comment]
[Fixed](https://github.com/JetBrains/skiko/pull/786)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3460">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
