### ISSUE TITLE
rememberSaveable mutableStateListOf problem in Android

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#3507]
**Describe the bug**
Hi
When I use `rememberSaveable` for `mutableStateListOf` in Android, I get the following error:

```
java.lang.IllegalArgumentException: androidx.compose.runtime.snapshots.SnapshotStateList@83e4398 cannot be saved using the current SaveableStateRegistry. The default implementation only supports types which can be stored inside the Bundle. Please consider implementing a custom Saver for this class and pass it to rememberSaveable().
                                                                                                    	at androidx.compose.runtime.saveable.RememberSaveableKt.requireCanBeSaved(RememberSaveable.kt:171)
                                                                                                    	at androidx.compose.runtime.saveable.RememberSaveableKt.access$requireCanBeSaved(RememberSaveable.kt:1)
                                                                                                    	at androidx.compose.runtime.saveable.RememberSaveableKt$rememberSaveable$1.invoke(RememberSaveable.kt:105)
                                                                                                    	at androidx.compose.runtime.saveable.RememberSaveableKt$rememberSaveable$1.invoke(RememberSaveable.kt:99)
                                                                                                    	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
                                                                                                    	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:625)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:792)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@b698ed4, androidx.compose.ui.platform.MotionDurationScaleImpl@16e987d, StandaloneCoroutine{Cancelling}@c3b3372, AndroidUiDispatcher@b0dd3c3]
```

**Affected platforms**
Select one of the platforms below:
- Android

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-Beta02
- JDK (for desktop issues): 17

**Comment by mazunin-v-jb** [comment]
Hello, thank you for submitting the issue.

We are not responsible for Android only issues, if you have any Android-only issues, please submit them [in the Jetpack Compose tracker.](https://issuetracker.google.com/issues/new?component=612128)

However, judging by the provided logs, I can assume that [you might find this helpful.](https://stackoverflow.com/questions/68885154/using-remembersaveable-with-mutablestatelistof)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3507">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
