### ISSUE TITLE
FocusRequester uninitialized in LazyColumn of BasicTextFields

### ISSUE THREAD

**Issue by Sydenth** [JetBrains/compose-multiplatform#3526]
**Describe the bug**
Compose 1.5.0-rc01 has a regression compared to 1.4.3:
A LazyColumn of BasicTextFields crashes when scrolling fast and wildly clicking on the BasicTextFields.

<details><summary>stack trace</summary>
<p>
    Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: 
       FocusRequester is not initialized. Here are some possible fixes:
    
       1. Remember the FocusRequester: val focusRequester = remember { FocusRequester() }
       2. Did you forget to add a Modifier.focusRequester() ?
       3. Are you attempting to request focus during composition? Focus requests should be made in
       response to some event. Eg Modifier.clickable { focusRequester.requestFocus() }
    
        at androidx.compose.ui.focus.FocusRequester.focus$ui(FocusRequester.kt:218)
        at androidx.compose.ui.focus.FocusRequester.requestFocus(FocusRequester.kt:63)
        at androidx.compose.foundation.text.selection.TextFieldSelectionManager$mouseSelectionObserver$1.onStart-3MmeM6k(TextFieldSelectionManager.kt:300)
        at androidx.compose.foundation.text.selection.TextSelectionMouseDetectorKt$mouseSelectionDetector$2.invokeSuspend(TextSelectionMouseDetector.kt:101)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:672)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:549)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:571)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:292)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:278)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:278)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:278)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:278)
        at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:156)
        at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:93)
        at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:97)
        at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui(SkiaBasedOwner.skiko.kt:362)
        at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui$default(SkiaBasedOwner.skiko.kt:355)
        at androidx.compose.ui.ComposeScene.processPress(ComposeScene.skiko.kt:635)
        at androidx.compose.ui.ComposeScene.processPointerInput(ComposeScene.skiko.kt:610)
        at androidx.compose.ui.ComposeScene.access$processPointerInput(ComposeScene.skiko.kt:68)
        at androidx.compose.ui.ComposeScene$syntheticEventSender$1.invoke(ComposeScene.skiko.kt:245)
        at androidx.compose.ui.ComposeScene$syntheticEventSender$1.invoke(ComposeScene.skiko.kt:245)
        at androidx.compose.ui.SyntheticEventSender.sendInternal(SyntheticEventSender.kt:157)
        at androidx.compose.ui.SyntheticEventSender.send(SyntheticEventSender.kt:64)
        at androidx.compose.ui.ComposeScene.sendPointerEvent-WlEVilQ(ComposeScene.skiko.kt:581)
        at androidx.compose.ui.ComposeScene.sendPointerEvent-BGSDPeU(ComposeScene.skiko.kt:523)
        at androidx.compose.ui.ComposeScene.sendPointerEvent-BGSDPeU$default(ComposeScene.skiko.kt:506)
        at androidx.compose.ui.awt.ComposeBridge_desktopKt.onMouseEvent(ComposeBridge.desktop.kt:405)
        at androidx.compose.ui.awt.ComposeBridge_desktopKt.access$onMouseEvent(ComposeBridge.desktop.kt:1)
        at androidx.compose.ui.awt.ComposeBridge$onMouseEvent$1.invoke(ComposeBridge.desktop.kt:245)
        at androidx.compose.ui.awt.ComposeBridge$onMouseEvent$1.invoke(ComposeBridge.desktop.kt:238)
        at androidx.compose.ui.awt.ComposeBridge.catchExceptions(ComposeBridge.desktop.kt:126)
        at androidx.compose.ui.awt.ComposeBridge.onMouseEvent(ComposeBridge.desktop.kt:238)
        at androidx.compose.ui.awt.ComposeBridge.access$onMouseEvent(ComposeBridge.desktop.kt:59)
        at androidx.compose.ui.awt.ComposeBridge$attachComposeToComponent$3.mousePressed(ComposeBridge.desktop.kt:218)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
        at java.desktop/java.awt.Component.processEvent(Component.java:6422)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeBridge$coroutineExceptionHandler$1@69157477, androidx.compose.runtime.BroadcastFrameClock@4eb483f1, StandaloneCoroutine{Cancelling}@42fc3495, FlushCoroutineDispatcher@26663e57]
</p>
</details> 

**Affected platforms**
- Desktop

**Versions**
- Kotlin version: 1.9.0
- Compose Multiplatform version: 1.5.0-rc01
- OS version: Windows 10 21H2
- OS architecture: x86
- JDK: jbr-17

**To Reproduce**
1. Clone reproducer repo: https://github.com/Sydenth/compose-focusrequester-bug
2. Start app.
3. Scroll around fast and click on text fields.
4. Eventually the app will crash with above mentioned stack trace.

**Screenshots**
![ReproFocusRequesterBug](https://github.com/JetBrains/compose-multiplatform/assets/8863174/01c5e438-2d83-436f-be31-d562056bbe2b)

**Additional context**
The 1.5.0 betas are affected as well. This bug does not happen with compose 1.4.3. 
Column works as expected.

**Comment by igordmn** [comment]
Reproduced in 1.5.0-dev1114, isn't reproducible in 1.5.0-dev1104

**Comment by igordmn** [comment]
Fixed in 1.5.0-rc04

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3526">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
