### ISSUE TITLE
Unable to use koin injected Factory method in compose web

### ISSUE THREAD

**Issue by sunildhiman90** [JetBrains/compose-multiplatform#3574]
**Describe the bug**
Getting this issue while trying to use one HomeComponent.Factory instance injected via koin DI to create component.
```
Uncaught TypeError: $this.homeComponentFactory_1.create_esiqto_k$ is not a function
    at child_2 (WebDesktopDefaultRootComponent.kt:234:38)
    at DefaultChildItemFactory.l [as childFactory_1] (Your-Flixer-shared.js:15326:14)
    at protoOf.invoke_9e5oyy_k$ (DefaultChildItemFactory.kt:32:13)
    at DefaultChildItemFactory.invoke$default [as invoke$default_bfpx9a_k$] (Decompose-decompose-js-ir.js:135:35)
    at protoOf.prepareNewItems_obvoel_k$ (Standard.kt:158:2001)
    at protoOf.switch_55pz6e_k$ (ChildrenNavigator.kt:117:24)
    at new ChildrenNavigator (ChildrenNavigator.kt:44:13)
    at children (ChildrenFactory.kt:80:13)
    at childStack_0 (ChildStackFactory.kt:91:5)
    at childStack (ChildStackFactory.kt:40:5)
```

In WebDesktopDefaultRootComponent class, i am trying to use homeComponentFactory passed via koin DI as parameter , an instance of HomeComponent.Factory , But it produces that error.

I am initializing koin above main method in main.js.kt, ANd i am passing the factory classes of components in root component(WebDesktopDefaultRootComponent), but while during some setup, it tries to create component, it shows that error.
But similar way working fine in desktop. Becoz for web and desktop i have one common kmm module webDesktopCommonMain, and common root component WebDesktopDefaultRootComponent.

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library

**Versions**
- Kotlin version*: latest
- Compose Multiplatform version*: latest

**Expected behavior**
It should not show that error, We should be able to use it successfully.

**Screenshots**

**Additional context**

**Comment by sunildhiman90** [comment]
Closing it, As it was due to same type definition for each Factory class, So now i used named injection, its working now.  
But its weird becoz i am wondering how it worked in other platforms then?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3574">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
