### ISSUE TITLE
Expected object 'MR' has no actual declaration in module MyApplication.shared.iosArm64Main for Native

### ISSUE THREAD

**Issue by wangzhigang1112** [JetBrains/compose-multiplatform#3603]
Has anyone encountered the following problem: using a third-party library and encountering compilation errors?

[ERROR INFO](https://github.com/icerockdev/moko-resources/issues/562)

**Comment by m-sasha** [comment]
Does this still occur with Compose 1.5.0?

**Comment by Moozart** [comment]
Same issue me too

**Comment by wangzhigang1112** [comment]
> Does this still occur with Compose 1.5.0?

<img width="1359" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/34496524/28727269-e581-47d5-8b07-90cabfca009c">
<img width="635" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/34496524/7ed009c7-dad1-4ec9-a50d-b6b03367d0f6">
After changing the Compose version to 1.5.0, the problem still exists.

**Comment by sunildhiman90** [comment]
I also have same issue for ios, and something similar for android as well:
```
Expected object 'MR' has no actual declaration in module <shared_debug> for JVM
```

and this one in web app:

```
java.lang.IllegalArgumentException: Cross module dependency resolution failed due to signature 'org.w3c.dom.events/EventListener|2833721539368120484[0]' redefinition
	at org.jetbrains.kotlin.ir.backend.js.transformers.irToJs.JsIrModuleCrossModuleReferenceBuilder.buildCrossModuleRefs(JsIrProgramFragment.kt:168)
	at org.jetbrains.kotlin.ir.backend.js.transformers.irToJs.CrossModuleDependenciesResolver.resolveCrossModuleDependencies(JsIrProgramFragment.kt:131)
	at org.jetbrains.kotlin.ir.backend.js.ic.JsExecutableProducer.buildMultiModuleExecutable(JsExecutableProducer.kt:56)
	at org.jetbrains.kotlin.ir.backend.js.ic.JsExecutableProducer.buildExecutable(JsExecutableProducer.kt:30)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:309)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1497)
```
Able to access resources by id but while building , facing these issues after adding moko-resources.

**Comment by m-sasha** [comment]
Waiting for reply from the moko-resources team...

**Comment by umesh0492** [comment]
Facing the same issue, any updates here?

**Comment by paskcountry** [comment]
Same issue to me. I have to migrate to Kotlin version 1.9.x to support compatibility with Xcode 15 and iOS 17. I'm not using compose for Android.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3603">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
