### ISSUE TITLE
SomeFunction.apply{} is not function in jsMain

### ISSUE THREAD

**Issue by dQqAn** [JetBrains/compose-multiplatform#3604]
**Describe the bug**
This is just the error in jsMain. You can check below error and my code.

**Affected platforms**
Select one of the platforms below:
- web
  
**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0 
- JDK (for desktop issues): 17

**To Reproduce**
```kotlin
loginViewModel.reloadUser().apply {
                    if (loginViewModel.isEmailVerified() == true) {
                        onNavigationClick()
                    }
                }
``` 
 
**Screenshots**
TypeError: $loginViewModel.reloadUser_km1at8_k$(...).runCatching is not a function
    at ClickablePointerInputNode.eval [as onClick_1] (Login.kt:80:41)
    at eval (Clickable.kt:898:36)
    at protoOf.doResume_5yljmg_k$ (TapGestureDetector.kt:258:17)
    at protoOf.resumeWith_7onugl_k$ (Standard.kt:55:40)
    at protoOf.resumeWith_s3a3yh_k$ (test.js:30302:17)
    at resume_0 (DispatchedTask.kt:179:26)
    at dispatch (DispatchedTask.kt:168:9)
    at dispatchResume (CancellableContinuationImpl.kt:474:9)
    at resumeImpl (CancellableContinuationImpl.kt:508:21)
    at resumeImpl$default (test.js:32125:12)

**Comment by m-sasha** [comment]
Can you provide a complete (but minimal) reproducer project?

Also, see the suggestions at the bottom of https://github.com/JetBrains/compose-multiplatform/issues/2697

**Comment by dQqAn** [comment]
I found the problem. The problem is 
```kotlin
internal fun reloadUser() = viewmodelScope.launch{ repository.reloadUser() }
``` 
and i change to
```kotlin
internal fun reloadUser() { viewmodelScope.launch{ repository.reloadUser() }}
``` 
for now, there is no error like "... is not a function". maybe it changes, i will open the issue... Thank you for reply.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3604">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
