### ISSUE TITLE
java.lang.UnsatisfiedLinkError org.jetbrains.skiko.AccessibilityKt.initializeCAccessible(javax.accessibility.Accessible)

### ISSUE THREAD

**Issue by sdzshn3** [JetBrains/compose-multiplatform#3699]
**Describe the bug**
Desktop app is crashing with the below shown exception. App seems to work for several seconds. after that, due to any of my actions like Clicking a button, typing in textfield, resizing the window.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.10-beta01
- OS version(s)* (required for Desktop and iOS issues): macOS Ventura 13.5.2
- OS architecture (x86 or arm64): Not sure
- JDK (for desktop issues): 17

**Additional context**
Crash logs:

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: 'void org.jetbrains.skiko.AccessibilityKt.initializeCAccessible(javax.accessibility.Accessible)'
	at org.jetbrains.skiko.AccessibilityKt.initializeCAccessible(Native Method)
	at org.jetbrains.skiko.HardwareLayerKt.nativeInitializeAccessible(HardwareLayer.kt:158)
	at androidx.compose.ui.platform.ComposeAccessible.getAccessibleContext(ComposeAccessible.kt:90)
	at java.desktop/sun.lwawt.macosx.CAccessibility.propertyChange(Unknown Source)
	at org.jetbrains.skiko.HardwareLayer.requestMacOSFocusOnAccessible(HardwareLayer.kt:103)
	at org.jetbrains.skiko.HardwareLayer.requestNativeFocusOnAccessible(HardwareLayer.kt:77)
	at org.jetbrains.skiko.SkiaLayer.requestNativeFocusOnAccessible(SkiaLayer.awt.kt:628)
	at androidx.compose.ui.awt.WindowComposeBridge.requestNativeFocusOnAccessible(WindowComposeBridge.desktop.kt:104)
	at androidx.compose.ui.awt.ComposeBridge$DesktopPlatform$accessibilityController$1.invoke(ComposeBridge.desktop.kt:346)
	at androidx.compose.ui.awt.ComposeBridge$DesktopPlatform$accessibilityController$1.invoke(ComposeBridge.desktop.kt:345)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.fireChangedNodeEvent(Accessibility.desktop.kt:99)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes$findAllSemanticNodesRecursive(Accessibility.desktop.kt:163)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes$findAllSemanticNodesRecursive(Accessibility.desktop.kt:174)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes$findAllSemanticNodesRecursive(Accessibility.desktop.kt:174)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes$findAllSemanticNodesRecursive(Accessibility.desktop.kt:174)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncNodes(Accessibility.desktop.kt:178)
	at androidx.compose.ui.platform.AccessibilityControllerImpl.syncLoop(Accessibility.desktop.kt:146)
	at androidx.compose.ui.platform.AccessibilityControllerImpl$syncLoop$1.invokeSuspend(Accessibility.desktop.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:62)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:57)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:91)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:37)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeBridge$coroutineExceptionHandler$1@34c2efba, androidx.compose.runtime.BroadcastFrameClock@36ce0ac1, StandaloneCoroutine{Cancelling}@57926a96, FlushCoroutineDispatcher@ba1705c]
Sept 17, 2023 10:16:38 PM sun.awt.AWTThreading$TrackedInvocationEvent lambda$new$2
INFO: InvocationEvent was disposed (awaiting 13 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getAccessibleIndexInParent(Unknown Source)
```

**Comment by MatkovIvan** [comment]
I see you're possibly using a different Skiko binary version in your application. Please ensure you have updated the Compose dependency for both the common and the current operating system using `compose.desktop.currentOs`. Let me know if this helps, or if you have more details to share (gradle dependency graph for example), to better help resolve your issue.

PS I opened [an issue](https://github.com/JetBrains/compose-multiplatform/issues/3282) previously to address situations like these.

**Comment by sdzshn3** [comment]
In common, I'm using `1.5.10-beta01` but in desktop gradle I'm using `compose.desktop.currentOs` which is now `1.5.1`
So, I understood there is a mismatch.

After changing the from 1.5.1 to 1.5.10-beta01 in Desktop App, It seems to be stable now.

Apologize for the overlook.

I also would like to know if there is a way to tell gradle to use a specific version of jetbrains compose? I need it because finding out which OS and arch and specifying the right dependency seems like some sort of work around because, compose.desktop.currentOs already takes care of it. I just want a way to specify a version manually.

**Comment by MatkovIvan** [comment]
> if there is a way to tell gradle to use a specific version of jetbrains compose?

Yes, sure - we publish the plugin (it handles things like `compose.desktop.currentOs`) for each version, so you can just update it. In our template project it's in `gradle.properties` - https://github.com/JetBrains/compose-multiplatform-template/blob/main/gradle.properties#L24

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3699">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
