### ISSUE TITLE
Crash when loading a particular svg

### ISSUE THREAD

**Issue by rosuH** [JetBrains/compose-multiplatform#3713]
**Describe the bug**
When loading the following svg file, a crash occurs.

[ic_refresh.svg.zip](https://github.com/JetBrains/compose-multiplatform/files/12672402/ic_refresh.svg.zip)

The svg file is placed in `compose-multiplatform-ios-android-template-main/shared/src/commonMain/resources/ic_refresh.svg`.

```kt
IconButton(
    modifier = Modifier.align(Alignment.BottomCenter).padding(0.dp, 0.dp, 0.dp, 16.dp),
    onClick = {
    }
) {
    Icon(
        painter = painterResource("ic_refresh.svg"),
        contentDescription = "Refresh"
    )
}
```

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.1
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

```
FATAL EXCEPTION: main
	Process: com.myapplication.MyApplication, PID: 7791
	java.lang.NullPointerException: decodeByteArray(this, 0, size) must not be null
		at org.jetbrains.compose.resources.ComposableResource_androidKt.toAndroidBitmap(ComposableResource.android.kt:17)
		at org.jetbrains.compose.resources.ComposableResource_androidKt.toImageBitmap(ComposableResource.android.kt:14)
		at org.jetbrains.compose.resources.ComposeResource_commonKt.rememberImageBitmapSync(ComposeResource.common.kt:82)
		at org.jetbrains.compose.resources.ComposeResource_commonKt.access$rememberImageBitmapSync(ComposeResource.common.kt:1)
		at org.jetbrains.compose.resources.ComposeResource_commonKt$painterResource$1.invoke(ComposeResource.common.kt:120)
		at org.jetbrains.compose.resources.ComposeResource_commonKt$painterResource$1.invoke(ComposeResource.common.kt:120)
		at org.jetbrains.compose.resources.ComposeResource_commonKt.painterResource(ComposeResource.common.kt:102)
		at org.jetbrains.compose.resources.ComposeResource_commonKt.painterResource(ComposeResource.common.kt:120)
		at com.example.kmp.ComposableSingletons$AppKt$lambda-2$1.invoke(App.kt:103)
		at com.example.kmp.ComposableSingletons$AppKt$lambda-2$1.invoke(App.kt:101)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
		at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
		at androidx.compose.material.IconButtonKt.IconButton(IconButton.kt:79)
		at com.example.kmp.AppKt.Content(App.kt:93)
		at com.example.kmp.AppKt.launchScreen(App.kt:77)
		at com.example.kmp.AppKt.access$launchScreen(App.kt:1)
		at com.example.kmp.ComposableSingletons$AppKt$lambda-1$1.invoke(App.kt:45)
		at com.example.kmp.ComposableSingletons$AppKt$lambda-1$1.invoke(App.kt:44)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
		at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:23)
		at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:82)
		at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:81)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
		at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
		at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:396)
		at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
		at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
		at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
		at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:72)
		at com.example.kmp.AppKt.App(App.kt:44)
		at com.example.kmp.Main_androidKt.MainView(main.android.kt:12)
		at com.myapplication.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:13)
		at com.myapplication.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:12)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
		at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
		at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
2023-09-20 19:14:17.659  7791-7791  AndroidRuntime                      com...ication.MyApplication  E  	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
		at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
		at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:195)
		at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
		at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
		at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
		at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
		at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:158)
		at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:157)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
		at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
		at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:157)
		at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:142)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
		at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
		at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
		at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3340)
		at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3273)
		at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:588)
		at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1013)
		at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
		at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
		at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
		at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1191)
		at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:133)
		at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:183)
		at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
		at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
		at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
		at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
		at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1266)
		at android.view.View.dispatchAttachedToWindow(View.java:21357)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
		at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
		at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2900)
		at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
		at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
		at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
		at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
		at android.view.Choreographer.doCallbacks(Choreographer.java:899)
		at android.view.Choreographer.doFrame(Choreographer.java:832)
		at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
		at android.os.Handler.handleCallback(Handler.java:942)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loopOnce(Looper.java:201)
		at android.os.Looper.loop(Looper.java:288)
		at android.app.ActivityThread.main(ActivityThread.java:7924)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Additional context**

**Comment by eric-ampire** [comment]
I was having the same issue, but I've convert the svg file to xml and the problem was solved

**Comment by dima-avdeev-jb** [comment]
@rosuH 
I can't reproduce your issue here: https://github.com/dima-avdeev-jb/issue-3713
Can you please check it in my repository too.

**Comment by rosuH** [comment]
Thank you for your reply, I have modified the code in order to reproduce the error.
You can check https://github.com/dima-avdeev-jb/issue-3713/pull/1/commits/5a797deded026c94ffe2bf926218b7bb57558106 to check the changes.
Also below is the project zip for easy and direct running.

[MyApplication.zip](https://github.com/JetBrains/compose-multiplatform/files/12706002/MyApplication.zip)

**Comment by dima-avdeev-jb** [comment]
For now resources library supports only xml vector drawables and other raster formats (png, jpg. webp)
You shoud convert svg to xml in AndroidStudio:


You can do so with AndroidStudio in androidApp res folder:

<img width="590" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/d1d24cd9-0daf-4035-bb28-1a59c0915023">

And choose Local file

<img width="698" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/636b2494-b8b8-4dc3-8d6e-e810777d4e70">

After that - copy xml file to **shared** module

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3713">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
