### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;

### ISSUE THREAD

**Issue by adelsaramii** [JetBrains/compose-multiplatform#3714]
Im using rememberScaffoldState() and i got error this error for this line

`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
                                                                                                    	at androidx.compose.material.AnchoredDraggableState.<init>(AnchoredDraggable.kt:248)
                                                                                                    	at androidx.compose.material.DrawerState.<init>(Drawer.kt:124)`
                                                                                                    	
here is the image for more perspective:
[https://imageupload.io/3qZPCGmmGszcNqo](url)

**Comment by ArbenMaloku** [comment]
I have the same issue, @adelsaramii did you find a workaround for this?

Using:
Kotlin: 1.9.0
AGP Version: 8.1.1
Compose: 1.5.2

**Comment by WilliamGates99** [comment]
It seems like the issue is caused by a change to **DrawerState** in [version **1.5.0** of **compose-material** dependency](https://developer.android.com/jetpack/androidx/releases/compose-material#1.5.0).</br></br>

You can use `compose.material3.Scaffold` instead.</br>
However since I needed to use Material 2 Scaffold to dock the FAB, I downgraded its version to **1.4.3** in order to fix the issue. But I had to remove the compose BoM to get it to work since BoM will override the newer version:
> implementation("androidx.compose.material:material:1.4.3")

**Comment by dima-avdeev-jb** [comment]
Can you please provide a minimal reproducible sample of this Issue?

What platform are you trying to run? Is it Desktop JVM ?

**Comment by dima-avdeev-jb** [comment]
> ModalBottomSheetLayout and BottomSheetScaffold and ... are not reusable as other components

What do you mean by "not reusable" ?
Can you please provide a code snippet and descrive expected behavior.
Or even better - create a project on GitHub

**Comment by Alexminator99** [comment]
> Same issue after updating versions:
> 
> kotlin: 1.8.10 -> 1.9.10 AGP: 7.3.1 -> 8.1.1 Gradle: 7.4 -> 8.1.1 Compose: 1.4.4 -> 1.5.3 Material3: 1.1.0-alpha8 -> 1.1.2
> 
> Stack trace: `java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt; at androidx.compose.ui.platform.MotionDurationScaleImpl.<init>(WindowRecomposer.android.kt:440) at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer.android.kt:341) at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer.android.kt:325) at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposer.android.kt:168) at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposer.android.kt:224) at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:300) at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:244) at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:251) at androidx.compose.ui.platform.AbstractComposeView.onAttachedToWindow(ComposeView.android.kt:283) at android.view.View.dispatchAttachedToWindow(View.java:21290) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2820) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239) at android.view.Choreographer.doCallbacks(Choreographer.java:899) at android.view.Choreographer.doFrame(Choreographer.java:832) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:7872) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.runtime.PrimitiveSnapshotStateKt" on path: DexPathList[[zip file "/data/app/~~iQmxxd_qAx9pqcQRE2_fAw==/com.meliopayments.app.dev-7UMnhpFCY2vRereRRKNZig==/base.apk"],nativeLibraryDirectories=[/data/app/~~iQmxxd_qAx9pqcQRE2_fAw==/com.meliopayments.app.dev-7UMnhpFCY2vRereRRKNZig==/lib/arm64, /system/lib64, /system_ext/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at androidx.compose.ui.platform.MotionDurationScaleImpl.<init>(WindowRecomposer.android.kt:440)  at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer.android.kt:341)  at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer.android.kt:325)  at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposer.android.kt:168)  at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposer.android.kt:224)  at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:300)  at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:244)  at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:251)  at androidx.compose.ui.platform.AbstractComposeView.onAttachedToWindow(ComposeView.android.kt:283)  at android.view.View.dispatchAttachedToWindow(View.java:21290)  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2820)  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)  at android.view.Choreographer.doCallbacks(Choreographer.java:899)  at android.view.Choreographer.doFrame(Choreographer.java:832)  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)  at android.os.Handler.handleCallback(Handler.java:942)  at android.os.Handler.dispatchMessage(Handler.java:99)  at android.os.Looper.loopOnce(Looper.java:201)  at android.os.Looper.loop(Looper.java:288)  at android.app.ActivityThread.main(ActivityThread.java:7872)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) `

I have the exact same issue with the same versions you have... Any solution?

**Comment by ArbenMaloku** [comment]
I had the same issues, I was using accompanist v0.33.2-alpha and was crashing. 

Switching to accompanist v0.32.0 did the job.

**Comment by Alexminator99** [comment]
> I had the same issues, I was using accompanist v0.33.2-alpha and was crashing.
> 
> Switching to accompanist v0.32.0 did the job.

Can you share your dependencies? I tried using v0.32.0 and no luck, same error... Im following the path of Now In Android and one of my other projects does not have this issue at all and it has the same things... Super weird...

**Comment by BaruchMelio** [comment]
So after looking at the stack trace I figured out that the reason must a mismatch between `compose.runtime` versions of some of the dependencies. After analyzing the actual resolved versions I found that a dependency on `androidx.compose.runtime:runtime-tracing:1.0.0-alpha04` made Gradle resolve the actual version of compose runtime from `1.5.3` to `1.6.0-alpha04`. I assume that the class `PrimitiveSnapshotState` was removed or renamed in this version and that's what causing the crash. In my case downgrading  `runtime-tracing` from `1.0.0-alpha04` to `1.0.0-alpha02` resolved the issue for me.
Running `./gradlew :app:dependencies` should help understand the issue.

**Comment by Dosssik** [comment]
Faced the same issue, thanks for the helpful explanation @BaruchMelio 👍🏼

Assuming dependencies conflicts will be different depending on the project setup - here is the one pretty useful page with officially compatible versions - [Jetpack Compose and Compose Multiplatform release cycles](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compatibility-and-versioning.html#jetpack-compose-and-compose-multiplatform-release-cycles). In my case the problem was caused by incompatible Jepack Compose and Compose Multiplatform versions.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3714">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
