### ISSUE TITLE
Accessibility. Crash on text hover on Windows

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3742]
Compose 1.5.0, OpenJDK 19

On 1.4.3 it works well

OpenJDK 19

1. Run this example:
```
import androidx.compose.material.Text
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    Text("Text")
}
```
2. [Enable Java Access bridge](https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Accessibility#windows), run NVDA 2023.2

3. Hover the text.

See the crash:
```
Exception in thread "Thread-1" java.lang.RuntimeException: java.lang.NullPointerException
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$InvocationUtils.invokeAndWait(AccessBridge.java:7278)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$InvocationUtils.invokeAndWait(AccessBridge.java:7253)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.getAccessibleTextLineLeftBoundsFromContext(AccessBridge.java:2073)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.runDLL(Native Method)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$dllRunner.run(AccessBridge.java:177)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException
	at androidx.compose.ui.platform.ComposeAccessible$ComposeAccessibleComponent$ComposeAccessibleText.getCharacterBounds(ComposeAccessible.kt:465)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$87.call(AccessBridge.java:2081)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$87.call(AccessBridge.java:2073)
	at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$InvocationUtils$CallableWrapper.run(AccessBridge.java:7334)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3742">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
