### ISSUE TITLE
NoClassDefFoundError proguard/optimize/gson/_OptimizedJsonWriter when the release is packaged

### ISSUE THREAD

**Issue by orelvis15** [JetBrains/compose-multiplatform#3765]
**Describe**
When I package the release and try to launch it, it returns this error, it only happens when I obfuscate it, I have tried various proGuard configurations but so far I have not been able to solve the problem.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*:  1.8.0
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues):  MAC Sonoma 14.0
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): 17.0.2

**Logs**

```
Exception in thread "main" java.lang.NoClassDefFoundError: proguard/optimize/gson/_OptimizedJsonWriter
	at androidx.compose.ui.window.Window_desktopKt$Window$5$1.invoke(Unknown Source)
	at androidx.compose.ui.window.Window_desktopKt$Window$5$1.invoke(Unknown Source)
	at androidx.compose.ui.util.ComponentUpdater.update(Unknown Source)
	at androidx.compose.ui.window.Window_desktopKt$Window$5.invoke(Unknown Source)
	at androidx.compose.ui.window.Window_desktopKt$Window$5.invoke(Unknown Source)
	at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Unknown Source)
	at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Unknown Source)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(Unknown Source)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(Unknown Source)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(Unknown Source)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(Unknown Source)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Unknown Source)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke$performUpdate(Unknown Source)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(Unknown Source)
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(Unknown Source)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Unknown Source)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Unknown Source)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Unknown Source)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Unknown Source)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Unknown Source)
	at androidx.compose.runtime.CompositionImpl.setContent(Unknown Source)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Unknown Source)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: proguard.optimize.gson._OptimizedJsonWriter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Failed to launch JVM
```

**Proguard configuration**

```
-ignorewarnings
-dontwarn kotlinx.datetime.**
-dontwarn org.slf4j.**

-keep class org.slf4j.** { *; }
-keep class com.sun.jna.* { *; }
-keep class * implements com.sun.jna.* { *; }

-keep class com.google.gson.** { *; }

-keep class models.** { *; }

-keep class androidx.compose.** { *; }
-keep class kotlinx.** { *; }
-keep class kotlin.** { *; }
-keep class io.ktor.** { *; }
```

**Comment by pjBooms** [comment]
May you provide a reproducible example so we could experiment with this?

**Comment by pjBooms** [comment]
You may try to disable Proguard optimizations, like

```
compose.desktop {
    application {
        buildTypes.release.proguard {
            optimize.set(false)
        }
    }
}
```

Or use [Gson config for Proguard](https://github.com/google/gson/blob/main/examples/android-proguard-example/proguard.cfg)

Does it work for you?

**Comment by pjBooms** [comment]
Have you solved your problem? May I close the issue? Honestly speaking I can't understand how we can help you regarding this issue

**Comment by orelvis15** [comment]
I have not solved it yet, but you can close it. I will continue testing configurations and if I find a solution I will tell you in this same issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3765">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
