### ISSUE TITLE
Error displaying .xml illustration on Web platform: Uncaught IllegalStateException - Size is unspecified

### ISSUE THREAD

**Issue by JoelKanyi** [JetBrains/compose-multiplatform#3871]
**Describe the bug**
 When I try displaying an illustration (`.xml` resource) on web platform, I get the following exception on the browser:
 
 ```
 Uncaught runtime errors:
×
ERROR
Size is unspecified
IllegalStateException: Size is unspecified
    at _Size___get_width__impl__58y75t (webpack-internal:///./kotlin/compose-multiplatform-core-ui-geometry.js:890:13)
    at protoOf.draw_j25tpb_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:3503:27)
    at protoOf.drawDirect_dh0hn_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:30248:14)
    at protoOf.draw_ntml17_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:30164:14)
    at drawContainedDrawModifiers (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:35290:17)
    at protoOf.draw_lhjy7e_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:36272:7)
    at protoOf.performDraw_1j48lz_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:27018:41)
    at drawContainedDrawModifiers (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:35287:13)
    at eval (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:35556:7)
    at protoOf.observe_3gku70_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-runtime.js:25319:25)
```

Here is the `Image` composable where I'm passing the image:
```kotlin
Image(
    painter = painterResource(illustration),
    contentDescription = illustration,
    modifier = Modifier.size(370.dp)
 )
```        

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*:  1.9.10
- Compose Multiplatform version*: 1.5.10-beta01

**Expected behavior**
I expect the image to be displayed, because it is being dispayed on Android, iOS, and Desktop

**Screenshots**
<img width="1503" alt="Screenshot 2023-10-27 at 09 35 58" src="https://github.com/JetBrains/compose-multiplatform/assets/50293753/c391af6a-cecf-4d5f-980d-79af1df04ad8">

**Comment by dima-avdeev-jb** [comment]
Hello! Thanks for Issue.
Can you please provide a minimal reproducible sample project on GitHub?

**Comment by JoelKanyi** [comment]
Here is a sample project, apparently, now I'm not getting anything on the browser screen:

https://github.com/JoelKanyi/ReproduceSample

**Comment by JoelKanyi** [comment]
Sorry, the repository was private, check now

**Comment by JoelKanyi** [comment]
Thank you, this worked 🎉

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3871">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
