### ISSUE TITLE
Crash On Android Release Build Only - Getting MissingResourceException: Missing resource with path Error

### ISSUE THREAD

**Issue by Mukuljangir372** [JetBrains/compose-multiplatform#3893]
**Describe the bug**
Compose Resource API throwing `MissingResourceException` while loading png image from resource package using painter resource API on Android release-build variant only. With the same code and resources, same code working fine on debug variant.

**Getting this Error-:**
`org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: res/drawable/ic_scogo_logo_dark.jpg
                                      	at org.jetbrains.compose.resources.AndroidResourceImpl.readBytes(Resource.android.kt:21)
                                      	at org.jetbrains.compose.resources.Resource_commonbutjsKt$readBytesSync$1.invokeSuspend(Resource.commonbutjs.kt:13)
                                      	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                      	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                      	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
                                      	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                                      	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                                      	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                                      	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                                      	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                                      	at org.jetbrains.compose.resources.Resource_commonbutjsKt.readBytesSync(Resource.commonbutjs.kt:13)
                                      	at org.jetbrains.compose.resources.ComposeResource_commonKt.rememberImageBitmapSync(ComposeResource.common.kt:82)
                                      	at org.jetbrains.compose.resources.ComposeResource_commonKt.access$rememberImageBitmapSync(ComposeResource.common.kt:1)
                                      	at org.jetbrains.compose.resources.ComposeResource_commonKt$painterResource$1.invoke(ComposeResource.common.kt:120)
                                      	at org.jetbrains.compose.resources.ComposeResource_commonKt$painterResource$1.invoke(ComposeResource.common.kt:120)
                                      	at org.jetbrains.compose.resources.ComposeResource_commonKt.painterResource(ComposeResource.common.kt:102)
                                      	at org.jetbrains.compose.resources.ComposeResource_commonKt.painterResource(ComposeResource.common.kt:120)`

**Affected platforms**
- Android

**Versions**
- Kotlin version: 1.9.10
- Compose Multiplatform version:  1.5.3
- AGP: 8.1.2

**To Reproduce**
1. Build release variant
2. Install & Launch
3. Crash/Error (see above)

**Screenshots**

Images In Resource Module/Package - 
<img width="338" alt="Screenshot 2023-11-03 at 1 21 04 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/64830777/d7f841c5-8555-4301-ad42-3689dff46cbc">

Getting error at Line 80:
<img width="932" alt="Screenshot 2023-11-03 at 1 29 30 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/64830777/c04b57fb-a657-4ede-8550-ad20dd5cd0cd">

**Additional context**
We've tried to change the value passing in painterResource with every possible solutions like `ic_scogo_logo_dark.jpg`, `drawable/ic_scogo_logo_dark.jpg` etc. But it's crashing on android release build, not on debug variant.

**Comment by eymar** [comment]
Could you please provide a project where this issue can be reproduced?

I tried to reproduce in this branch but it worked fine:
https://github.com/JetBrains/compose-multiplatform/tree/reproduce_resources_3893/components/resources/demo

```
./gradlew :resources:demo:androidApp:build``
adb install resources/demo/androidApp/build/outputs/apk/release/androidApp-release.apk
```

```kotlin
// .../compose-multiplatform/components/resources/demo/shared/src/commonMain/resources/drawable/img.png
Image(
            painter = painterResource("drawable/img.png"),
            contentDescription = null,
            modifier = Modifier.size(150.dp),
        )
 ```
 
 And it works fine in the release app.

**Comment by derynia** [comment]
Have the same issue. 
Everything worked fine. 
Everything still works on iOS but it doesn't work on Android. 
It crashes on debug variant.

**Comment by Mukuljangir372** [comment]
It has been resolved in latest versions.

**Comment by derynia** [comment]
> It has been resolved in latest version.

My problem was that I was using: 
    packaging {
        resources {
            excludes += "*/**"
        }
    }

because my project didn't build at all with other error message
So when I changed to this
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "/META-INF/versions/**"
        }
    }

It started working.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3893">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
