### ISSUE TITLE
Build fails when `org.jetbrains.compose` is applied from a script plugin

### ISSUE THREAD

**Issue by yevhenii-nadtochii** [JetBrains/compose-multiplatform#3933]
**Describe the bug**

Applying of `id("org.jetbrains.compose")` from a script plugin fails the build. But if stop Gradle daemon and re-run it again, the build passes. If stop Gradle daemon and clean temporary directories (`build` and `.gradle`), then the build fails.

So, it always fails from the begging (especially on CI). But you can make it work by re-running Gradle daemon with the previously generated cache.

I see such behavior only with Compose plugin. Downgrading Gradle doesn't change anything.

<details>
<summary>Thrown exception</summary>

```
Could not stop org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer@60251ed.
org.gradle.internal.snapshot.impl.IsolationException: Could not isolate value org.jetbrains.compose.internal.service.GradlePropertySnapshotService$Parameters_Decorated@85190fa of type GradlePropertySnapshotService.Parameters
        at org.gradle.internal.snapshot.impl.DefaultIsolatableFactory.isolate(DefaultIsolatableFactory.java:51)
        at org.gradle.api.services.internal.RegisteredBuildServiceProvider.instantiate(RegisteredBuildServiceProvider.java:127)
        at org.gradle.api.services.internal.RegisteredBuildServiceProvider.getInstance(RegisteredBuildServiceProvider.java:118)
        at org.gradle.api.services.internal.RegisteredBuildServiceProvider.calculateOwnValue(RegisteredBuildServiceProvider.java:111)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:80)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
        at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer.handle(DefaultBuildEventsListenerRegistry.java:261)
        at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer.handle(DefaultBuildEventsListenerRegistry.java:238)
        at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$AbstractListener.run(DefaultBuildEventsListenerRegistry.java:180)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: BuildScopeServices has been closed.
        at org.gradle.internal.service.DefaultServiceRegistry.serviceRequested(DefaultServiceRegistry.java:289)
        at org.gradle.internal.service.DefaultServiceRegistry.getService(DefaultServiceRegistry.java:328)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:323)
        at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:308)
        at org.gradle.internal.instantiation.generator.ManagedObjectFactory.getObjectFactory(ManagedObjectFactory.java:136)
        at org.gradle.internal.instantiation.generator.ManagedObjectFactory.newInstance(ManagedObjectFactory.java:111)
        at org.jetbrains.compose.internal.service.GradlePropertySnapshotService$Parameters_Decorated.getGradlePropertiesCacheKindSnapshot(Unknown Source)
        at org.jetbrains.compose.internal.service.GradlePropertySnapshotService$Parameters_Decorated.unpackState(Unknown Source)
        at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:134)
        at org.gradle.internal.snapshot.impl.DefaultIsolatableFactory.isolate(DefaultIsolatableFactory.java:49)
        ... 15 more
```
</details>

---

**Versions**

- Kotlin: 1.9.10
- Gradle: 8.4
- Compose Multiplatform: 1.5.10 (the same with 1.6.0-dev1265)
- OS architecture (x86 or arm64): x86
- JDK: Zulu11.68+17-CA (build 11.0.21+9-LTS)

---

**To Reproduce**

1. Generate an empty Gradle project: `gradle init`.
2. Put Compose plugin on the classpath of `buildSrc`: `implementation("org.jetbrains.compose:compose-gradle-plugin:1.5.10")`.
3. Create a script plugin: `compose.gradle.kts`.
4. Apply Compose plugin from it: `id("org.jetbrains.compose")`.

Please take a look on [reproducer.zip](https://github.com/JetBrains/compose-multiplatform/files/13379977/reproducer.zip).

Using the reproducer:

1. Unzip the archive.
2. Make sure all Gradle daemons are stopped by `./gradlew --stop`.
3. Build the reproducer `./gradlew clean build`.
4. See **fail**.
5. Stop daemons again `./gradlew --stop`.
6. Build it `./gradlew clean build`.
7. See **success**.
8. Remove `build`, `.gradle`, `buildSrc/build`, `buildSrc/.gradle` directories, stop daemon `./gradlew --stop`.
9. Build it `./gradlew clean build`.
10. It **fails** again.

I believe in all cases we should have seen success. Doesn't matter whether it is built upon cache or with new/old daemons.

**Comment by dima-avdeev-jb** [comment]
Related to Issue: https://github.com/gradle/gradle/issues/27099

**Comment by dima-avdeev-jb** [comment]
Done, fix of this bug will be available in next 1.6.0-dev version of Compose Multiplatform
https://github.com/JetBrains/compose-multiplatform/releases

**Comment by dima-avdeev-jb** [comment]
Fixed in version 1.6.0-dev1334

**Comment by svenjacobs** [comment]
Hello @dima-avdeev-jb, could the fix please be backported to 1.5? I'm an author of a library that uses Compose Multiplatform and I don't want to depend on a dev version, imposing that version on the users of the library.

**Comment by dima-avdeev-jb** [comment]
@svenjacobs 
Sorry, we don't have enough time to do this in the near future. As a workaround you can use compose plugin right in your root build.gradle.kts instead of buildSrc/...

**Comment by iruizmar** [comment]
Hey! I see this one re-appearing on 1.6.10-rc03, not happening in 1.6.10-rc02. Is that known?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3933">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
