### ISSUE TITLE
[BUG] [Windows] java.nio.file.AccessDeniedException for font file mid-execution

### ISSUE THREAD

**Issue by mitch3ls** [JetBrains/compose-multiplatform#394]
# Summary:
 java.nio.file.AccessDeniedException is thrown after a long chain of other exceptions mid-execution. This only happens on Windows and I haven't been able to recreate it in a minimal code base.

# Environment:
OS: Windows 10 Pro 1901 18363.900

# Steps to Reproduce:

1. Clone Repository [https://github.com/mitch3ls/jb-compose-issue-394-demo](https://github.com/mitch3ls/jb-compose-issue-394-demo)
2. Run on Windows with `gradle run`
![image](https://user-images.githubusercontent.com/19824704/108075151-52078180-706a-11eb-9759-db182401d0b5.png)
3. Click "Add source file" and load any JSON file ([./src/test/resources/MOCK_DATA.json](https://raw.githubusercontent.com/mitch3ls/jb-compose-issue-394-demo/master/src/test/resources/MOCK_DATA.json)  provided as suggestion)
![image](https://user-images.githubusercontent.com/19824704/108075251-72cfd700-706a-11eb-88dc-fbb989f55d80.png)
4. Click the magnifying glass icon
5. Now click the plus icon in the dialog that has opened

# Expected Results:

An element should appear like in this screenshot from macOS

![image](https://user-images.githubusercontent.com/19824704/108075569-cf32f680-706a-11eb-8ac5-257d602ea751.png)

# Actual Results:

The dialog freezes and a long list of exceptions is thrown with java.nio.file.AccessDeniedException at the top of the stack trace
![image](https://user-images.githubusercontent.com/19824704/108074940-0ead1300-706a-11eb-92b1-4e10eef953f1.png)

<details>
  <summary>Click to expand stack trace</summary>
<code>
Exception in thread "AWT-EventQueue-0 @coroutine#5956" java.nio.file.AccessDeniedException: C:\Users\Michael\AppData\Local\Temp\compose\font\Segoe UI.ttf
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1185)
	at java.base/java.nio.file.Files.copy(Files.java:3132)
	at androidx.compose.ui.text.platform.DesktopFontKt.getFontPathAsString(DesktopFont.kt:109)
	at androidx.compose.ui.text.platform.DesktopFontKt.typefaceResource(DesktopFont.kt:92)
	at androidx.compose.ui.text.platform.DesktopFontKt.access$typefaceResource(DesktopFont.kt)
	at androidx.compose.ui.text.platform.FontLoader.load(DesktopFont.kt:67)
	at androidx.compose.ui.text.platform.FontLoader.ensureRegistered(DesktopFont.kt:56)
	at androidx.compose.ui.text.platform.ParagraphBuilder.ensureFontsAreRegistered(DesktopParagraph.kt:594)
	at androidx.compose.ui.text.platform.ParagraphBuilder.build(DesktopParagraph.kt:560)
	at androidx.compose.ui.text.platform.DesktopParagraphIntrinsics.<init>(DesktopParagraphIntrinsics.kt:67)
	at androidx.compose.ui.text.platform.DesktopParagraphIntrinsicsKt.ActualParagraphIntrinsics(DesktopParagraphIntrinsics.kt:37)
	at androidx.compose.ui.text.ParagraphIntrinsicsKt.ParagraphIntrinsics(ParagraphIntrinsics.kt:54)
	at androidx.compose.ui.text.MultiParagraphIntrinsics.<init>(MultiParagraphIntrinsics.kt:76)
	at androidx.compose.ui.text.TextDelegate.layoutIntrinsics(TextDelegate.kt:117)
	at androidx.compose.ui.text.TextDelegate.layoutText-urungq4(TextDelegate.kt:141)
	at androidx.compose.ui.text.TextDelegate.layout-BAnaFRY(TextDelegate.kt:218)
	at androidx.compose.foundation.text.TextController$measure$1.invoke(CoreText.kt:268)
	at androidx.compose.foundation.text.TextController$measure$1.invoke(CoreText.kt)
	at androidx.compose.ui.layout.LayoutKt$measureBlocksOf$1.measure-8A2P9vY(Layout.kt:146)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:45)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-za8Wrwc(GraphicsLayerModifier.kt:201)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1245)
	at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt:107)
	at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt)
	at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:394)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:45)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.material.TextFieldImplKt$iconPadding$1.measure-za8Wrwc(TextFieldImpl.kt:324)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1245)
	at androidx.compose.material.TextFieldKt$IconsWithTextFieldLayout$2$1.invoke(TextField.kt:434)
	at androidx.compose.material.TextFieldKt$IconsWithTextFieldLayout$2$1.invoke(TextField.kt)
	at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:394)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:45)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.foundation.layout.SizeModifier.measure-za8Wrwc(LayoutSize.kt:711)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1245)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt:148)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt)
	at androidx.compose.ui.layout.LayoutKt$measureBlocksOf$1.measure-8A2P9vY(Layout.kt:146)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:45)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.foundation.layout.PaddingModifier.measure-za8Wrwc(LayoutPadding.kt:210)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(LayoutSize.kt:645)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1245)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt:90)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt)
	at androidx.compose.ui.layout.LayoutKt$measureBlocksOf$1.measure-8A2P9vY(Layout.kt:146)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:45)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(LayoutSize.kt:645)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.foundation.ScrollingLayoutModifier.measure-za8Wrwc(Scroll.kt:462)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-za8Wrwc(GraphicsLayerModifier.kt:201)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1245)
	at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt:129)
	at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt)
	at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:394)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:45)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:106)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(LayoutSize.kt:645)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:66)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1245)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt:148)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt)
	at androidx.compose.ui.layout.LayoutKt$measureBlocksOf$1.measure-8A2P9vY(Layout.kt:146)
	at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:45)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(LayoutSize.kt:645)
	at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:148)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1721)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:93)
	at androidx.compose.ui.node.LayoutNode.remeasure-BRTryo0$ui(LayoutNode.kt:1252)
	at androidx.compose.ui.node.LayoutNode.remeasure-BRTryo0$default(LayoutNode.kt:1250)
	at androidx.compose.ui.node.LayoutNode.onBeforeLayoutChildren(LayoutNode.kt:1066)
	at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:955)
	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui(LayoutNode.kt:950)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-rMeLuDI(InnerPlaceable.kt:120)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeApparentToRealOffset-pOgwPa8(Placeable.kt:324)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-z2mxYZE(Placeable.kt:215)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-z2mxYZE$default(Placeable.kt:214)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:113)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-rMeLuDI(DelegatingLayoutNodeWrapper.kt:101)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeApparentToRealOffset-pOgwPa8(Placeable.kt:324)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-z2mxYZE(Placeable.kt:215)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-z2mxYZE$default(Placeable.kt:214)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$performMeasure$1.placeChildren(DelegatingLayoutNodeWrapper.kt:113)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-rMeLuDI(DelegatingLayoutNodeWrapper.kt:101)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeApparentToRealOffset-pOgwPa8(Placeable.kt:324)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-muyPCdA(Placeable.kt:301)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-rMeLuDI(OuterMeasurablePlaceable.kt:127)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.replace(OuterMeasurablePlaceable.kt:136)
	at androidx.compose.ui.node.LayoutNode.replace$ui(LayoutNode.kt:831)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:220)
	at androidx.compose.ui.platform.DesktopOwner.measureAndLayout(DesktopOwner.kt:163)
	at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.kt:85)
	at androidx.compose.ui.platform.DesktopOwners$onFrame$1.invokeSuspend(DesktopOwners.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0 @coroutine#5955" java.lang.IllegalArgumentException: Failed requirement.
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:195)
	at androidx.compose.ui.platform.DesktopOwner.measureAndLayout(DesktopOwner.kt:163)
	at androidx.compose.ui.platform.DesktopOwner.onPointerMove-k-4lQ0M$ui(DesktopOwner.kt:239)
	at androidx.compose.ui.platform.DesktopOwners.onMouseMoved(DesktopOwners.kt:137)
	at androidx.compose.desktop.ComposeLayer$initCanvas$3$mouseMoved$1.invoke(ComposeLayer.kt:179)
	at androidx.compose.desktop.ComposeLayer$initCanvas$3$mouseMoved$1.invoke(ComposeLayer.kt)
	at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</code>
</details>

Notes:
This bug ONLY happens on Windows. I haven't been able to reproduce it in a simpler environment

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5505">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
