### ISSUE TITLE
Add bottom border to box, the programme crashes.

### ISSUE THREAD

**Issue by guiyanakuang** [JetBrains/compose-multiplatform#3975]
**Describe the bug**
Add bottom border to box, the programme crashes.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version: 1.9.20
- Compose Multiplatform version: 1.5.4 
- JDK (for desktop issues): zulu 17.0.9

**To Reproduce**
```kotlin
@Composable
@Preview
fun BottomBorderBox() {
    val bottomBorderShape = GenericShape { size, _ ->
        moveTo(0f, size.height)
        lineTo(size.width, size.height)
    }

    Box(
        modifier = Modifier
            .size(100.dp, 100.dp)
            .border(2.dp, Color.Black, bottomBorderShape)
    ) {
        // Box content here
    }
}
```

**Expected behavior**
Rendering ui correctly.

**Screenshots**
<img width="318" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/4069905/ebaca644-9865-4840-98fc-ac4b3bb38860">

```log
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.renderFrame(RemotePreviewHost.kt:161)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.renderFrame(RemotePreviewHost.kt:129)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost.access$renderFrame(RemotePreviewHost.kt:47)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost$senderThread$1.invoke(RemotePreviewHost.kt:63)
	at org.jetbrains.compose.desktop.ui.tooling.preview.rpc.PreviewHost$senderThread$1.invoke(RemotePreviewHost.kt:56)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.lang.RuntimeException: Failed to Image::makeFromBitmap Bitmap(_ptr=0x600003f3a880)
	at org.jetbrains.skia.Image$Companion.makeFromBitmap(Image.kt:114)
	at androidx.compose.ui.graphics.SkiaBackedCanvas.drawImageRect-cI72Soc(SkiaBackedCanvas.skiko.kt:217)
	at androidx.compose.ui.graphics.SkiaBackedCanvas.drawImageRect-HPBpro0(SkiaBackedCanvas.skiko.kt:192)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawImage-AZ2fEMs(CanvasDrawScope.kt:263)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawImage-AZ2fEMs(LayoutNodeDrawScope.kt)
	at androidx.compose.ui.graphics.drawscope.DrawScope.drawImage-AZ2fEMs$default(DrawScope.kt:510)
	at androidx.compose.foundation.BorderModifierNode$drawGenericBorder$3.invoke(Border.kt:291)
	at androidx.compose.foundation.BorderModifierNode$drawGenericBorder$3.invoke(Border.kt:288)
	at androidx.compose.ui.draw.CacheDrawModifierNodeImpl.draw(DrawModifier.kt:221)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui(LayoutNodeDrawScope.kt:105)
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui(LayoutNodeDrawScope.kt:86)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:369)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:358)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:182)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:366)
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:54)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:388)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:387)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2300)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:471)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:234)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:387)
	at androidx.compose.ui.node.NodeCoordinator$invokeOnCanvasInstance$1.invoke(NodeCoordinator.kt:204)
	at androidx.compose.ui.node.NodeCoordinator$invokeOnCanvasInstance$1.invoke(NodeCoordinator.kt:204)
	at androidx.compose.ui.platform.RenderNodeLayer.performDrawLayer(RenderNodeLayer.skiko.kt:274)
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.skiko.kt:218)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:922)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:366)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:358)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:922)
	at androidx.compose.ui.platform.SkiaBasedOwner.draw(SkiaBasedOwner.skiko.kt:352)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:550)
	at androidx.compose.ui.ImageComposeScene.render(ImageComposeScene.skikoMain.kt:203)
	at androidx.compose.ui.ImageComposeScene.render$default(ImageComposeScene.skikoMain.kt:201)
	at androidx.compose.ui.ImageComposeScene_skikoMainKt.renderComposeScene(ImageComposeScene.skikoMain.kt:65)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade$Companion.render(NonInteractivePreviewFacade.kt:53)
	at androidx.compose.desktop.ui.tooling.preview.runtime.NonInteractivePreviewFacade.render(NonInteractivePreviewFacade.kt)
	... 10 more
```

**Comment by dima-avdeev-jb** [comment]
Usefull log is:
`java.lang.IllegalArgumentException: width and height must be > 0`

That means you can write your code in this way:
```Kotlin
val bottomBorderShape = GenericShape { size, _ ->
        moveTo(0f, size.height)
        lineTo(size.width, size.height)
        lineTo(size.width, size.height - 1)
        lineTo(0f, size.height - 1)
        close()
    }
    Box {
        Box(
            modifier = Modifier
                .size(100.dp, 100.dp)
                .border(5.dp, Color.Black, bottomBorderShape)
                .background(Color.LightGray)
        ) {
            // Box content here
        }
    }
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3975">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
