### ISSUE TITLE
kotlin.NotImplementedError: Generation of stubs for class org.jetbrains.kotlin.ir.symbols.impl.IrValueParameterSymbolImpl is not supported yet

### ISSUE THREAD

**Issue by colinrtwhite** [JetBrains/compose-multiplatform#4003]
**Describe the bug**
I'm running into a JS Compose compiler error when calling a specific function in [Coil](https://github.com/coil-kt/coil)'s Compose integration. The function compiles successfully, but any module that tries to call the function fails to compile. [Here's the function definition](https://github.com/coil-kt/coil/blob/colin/compose_multiplatform_js_bug/coil-compose-base/src/commonMain/kotlin/coil3/compose/SubcomposeAsyncImage.kt#L52), [here's an example call site where the Compose compiler fails](https://github.com/coil-kt/coil/blob/colin/compose_multiplatform_js_bug/coil-compose-singleton/src/commonMain/kotlin/coil3/compose/ComposeBugReproduction.kt#L7), and here's the compiler stacktrace:

<details>

```
    e: kotlin.NotImplementedError: Generation of stubs for class org.jetbrains.kotlin.ir.symbols.impl.IrValueParameterSymbolImpl is not supported yet
        at org.jetbrains.kotlin.backend.common.linkage.partial.MissingDeclarationStubGenerator.getDeclaration(MissingDeclarationStubGenerator.kt:63)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.checkReferencedDeclaration(PartiallyLinkedIrTreePatcher.kt:582)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.checkReferencedDeclaration$default(PartiallyLinkedIrTreePatcher.kt:574)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitDeclarationReference(PartiallyLinkedIrTreePatcher.kt:488)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitValueAccess(IrElementTransformerVoid.kt:190)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitGetValue(IrElementTransformerVoid.kt:193)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitGetValue(IrElementTransformerVoid.kt:194)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitGetValue(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrGetValue.accept(IrGetValue.kt:20)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.transformChildren(IrMemberAccessExpression.kt:48)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitCall(PartiallyLinkedIrTreePatcher.kt:1322)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:215)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:26)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrSetValue.transformChildren(IrSetValue.kt:30)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitDeclarationReference(PartiallyLinkedIrTreePatcher.kt:1226)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitValueAccess(IrElementTransformerVoid.kt:190)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSetValue(IrElementTransformerVoid.kt:196)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSetValue(IrElementTransformerVoid.kt:197)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSetValue(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrSetValue.accept(IrSetValue.kt:23)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.expressions.IrContainerExpression.transformChildren(IrContainerExpression.kt:31)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitBlock(PartiallyLinkedIrTreePatcher.kt:1177)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:170)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:20)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.transformChildren(IrBranch.kt:39)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:267)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:271)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.accept(IrBranch.kt:27)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.transform(IrBranch.kt:30)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.transform(IrBranch.kt:21)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.expressions.IrWhen.transformChildren(IrWhen.kt:33)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitExpression(PartiallyLinkedIrTreePatcher.kt:1822)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:263)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:264)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrWhen.accept(IrWhen.kt:26)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.expressions.IrContainerExpression.transformChildren(IrContainerExpression.kt:31)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitExpression(PartiallyLinkedIrTreePatcher.kt:1822)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitContainerExpression(IrElementTransformerVoid.kt:166)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:172)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:173)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrComposite.accept(IrComposite.kt:20)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.transformChildren(IrBranch.kt:39)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:267)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:271)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.accept(IrBranch.kt:27)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.transform(IrBranch.kt:30)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.transform(IrBranch.kt:21)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.expressions.IrWhen.transformChildren(IrWhen.kt:33)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitExpression(PartiallyLinkedIrTreePatcher.kt:1822)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:263)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:264)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrWhen.accept(IrWhen.kt:26)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.expressions.IrContainerExpression.transformChildren(IrContainerExpression.kt:31)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitBlock(PartiallyLinkedIrTreePatcher.kt:1177)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:170)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:20)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.transformChildren(IrBranch.kt:39)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:267)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:271)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.accept(IrBranch.kt:27)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.transform(IrBranch.kt:30)
        at org.jetbrains.kotlin.ir.expressions.IrBranch.transform(IrBranch.kt:21)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.expressions.IrWhen.transformChildren(IrWhen.kt:33)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitExpression(PartiallyLinkedIrTreePatcher.kt:1822)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:263)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:264)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrWhen.accept(IrWhen.kt:26)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.expressions.IrBlockBody.transformChildren(IrBlockBody.kt:32)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBody(IrElementTransformerVoid.kt:108)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:117)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitBlockBody(PartiallyLinkedIrTreePatcher.kt:467)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:118)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:25)
        at org.jetbrains.kotlin.ir.expressions.IrBody.transform(IrBody.kt:22)
        at org.jetbrains.kotlin.ir.declarations.IrFunction.transformChildren(IrFunction.kt:62)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:57)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitDeclaration(PartiallyLinkedIrTreePatcher.kt:462)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFunction(IrElementTransformerVoid.kt:69)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:72)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:73)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:37)
        at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:24)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transformChildren(IrFile.kt:41)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitPackageFragment(IrElementTransformerVoid.kt:41)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$ExpressionTransformer.visitPackageFragment(PartiallyLinkedIrTreePatcher.kt:453)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:47)
        at org.jetbrains.kotlin.backend.common.linkage.partial.FileAwareIrElementTransformerVoid.access$visitFile$s-1784493990(PartialLinkageUtils.kt:82)
        at org.jetbrains.kotlin.backend.common.linkage.partial.FileAwareIrElementTransformerVoid$visitFile$1.invoke(PartialLinkageUtils.kt:97)
        at org.jetbrains.kotlin.backend.common.linkage.partial.FileAwareIrElementTransformerVoid$visitFile$1.invoke(PartialLinkageUtils.kt:96)
        at org.jetbrains.kotlin.backend.common.linkage.partial.FileAwareIrElementTransformerVoid.runInFile(PartialLinkageUtils.kt:90)
        at org.jetbrains.kotlin.backend.common.linkage.partial.FileAwareIrElementTransformerVoid.visitFile(PartialLinkageUtils.kt:96)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:48)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFile(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:31)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transform(IrFile.kt:34)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transform(IrFile.kt:22)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.transformChildren(IrModuleFragment.kt:52)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitModuleFragment(IrElementTransformerVoid.kt:33)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitModuleFragment(IrElementTransformerVoid.kt:38)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitModuleFragment(IrElementTransformerVoid.kt:24)
        at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.accept(IrModuleFragment.kt:42)
        at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.transform(IrModuleFragment.kt:45)
        at org.jetbrains.kotlin.ir.declarations.IrModuleFragment.transform(IrModuleFragment.kt:26)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher.transformVoid(PartiallyLinkedIrTreePatcher.kt:87)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher.patchModuleFragments(PartiallyLinkedIrTreePatcher.kt:68)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartialLinkageSupportForLinkerImpl$generateStubsAndPatchUsages$1.invoke(PartialLinkageSupportForLinkerImpl.kt:62)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartialLinkageSupportForLinkerImpl$generateStubsAndPatchUsages$1.invoke(PartialLinkageSupportForLinkerImpl.kt:62)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartialLinkageSupportForLinkerImpl.generateStubsAndPatchUsagesInternal(PartialLinkageSupportForLinkerImpl.kt:80)
        at org.jetbrains.kotlin.backend.common.linkage.partial.PartialLinkageSupportForLinkerImpl.generateStubsAndPatchUsages(PartialLinkageSupportForLinkerImpl.kt:62)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.postProcess(KotlinIrLinker.kt:231)
        at org.jetbrains.kotlin.ir.backend.js.KlibKt.getIrModuleInfoForKlib(klib.kt:305)
        at org.jetbrains.kotlin.ir.backend.js.KlibKt.loadIr(klib.kt:242)
        at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile(compiler.kt:54)
        at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile$default(compiler.kt:39)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler$Ir2JsTransformer.lowerIr(K2JsIrCompiler.kt:103)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler$Ir2JsTransformer.makeJsCodeGenerator(K2JsIrCompiler.kt:125)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler$Ir2JsTransformer.compileAndTransformIrNew(K2JsIrCompiler.kt:133)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:391)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
        at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11 (compiler 1.5.4)
- OS version(s)* (required for Desktop and iOS issues): macOS 13.6.2
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): openjdk version "17.0.6" 2023-01-17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. `git clone https://github.com/coil-kt/coil.git`
2. `cd coil`
3. `git checkout colin/compose_multiplatform_js_bug`
4. `./gradlew coil-compose-singleton:assemble`
5. See error

**Expected behavior**
The module compiles without error.

**Comment by m-sasha** [comment]
HI, thanks for the report. Could you reduce it to a small reproducer?

@eymar Are you familiar with this issue?

**Comment by eymar** [comment]
This one doesn't look familiar to me.
I'll need to investigate. Perhaps later this week.

**Comment by eymar** [comment]
Hi @colinrtwhite ! I'm trying to reproduce the problem using your project and the branch you mentioned.

I see several errors like this:
`Could not resolve io.coil-kt.coil3:coil-gif:3.0.0-SNAPSHOT for :coil-sample-common:androidInstrumentedTest`

In what maven repository is it to be found?

**Comment by eymar** [comment]
Also, could you please try CM 1.6.0-alpha01?

It disables so-called decoys generation for k/js targets, aligning it with other targets which never had it enabled.
But it's possible only if you don't have any dependencies on third-party Compose libraries with k/js targets (unless they're rebuilt with 1.6.0-alpha01).

**Comment by colinrtwhite** [comment]
@eymar Hmm `coil-gif` and other projects should be resolved from inside the root project. They can also be published to `mavenLocal` using `./publish_local.sh`, though that shouldn't be required.

Fortunately I tried out `1.6.0-alpha01` and that fixes the issue! The library doesn't have any 3rd party Compose libraries so that fix works for me.

**Comment by alexzhirkevich** [comment]
Same here  k/1.9.21,  compose/1.5.11

**Comment by colinrtwhite** [comment]
@m-sasha Closing sounds good to me. My sample no longer repro's on `1.6.0-alpha01`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4003">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
