### ISSUE TITLE
An exception occurred applying plugin request [id: 'org.jetbrains.compose', version: '1.6.0-dev1350'] > Failed to apply plugin 'org.jetbrains.compose'

### ISSUE THREAD

**Issue by serbelga** [JetBrains/compose-multiplatform#4082]
**Describe the bug**

Following exception is thrown when I use dev version `1.6.0-dev1350` of Compose Multiplatform

```
An exception occurred applying plugin request [id: 'org.jetbrains.compose', version: '1.6.0-dev1350']
> Failed to apply plugin 'org.jetbrains.compose'.
   > Extension of type 'KotlinProjectExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, LibrariesForLibs, VersionCatalogsExtension, RootProjectAccessor, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaToolchainService, JavaPluginExtension, BaseAppModuleExtension, ApplicationAndroidComponentsExtension, NamedDomainObjectContainer<BaseVariantOutput>, ComposeExtension]

* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'org.jetbrains.compose', version: '1.6.0-dev1350']
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:260)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:238)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyLegacyPlugin(DefaultPluginRequestApplicator.java:190)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$300(DefaultPluginRequestApplicator.java:63)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1$1.lambda$addLegacy$0(DefaultPluginRequestApplicator.java:150)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyPlugins$0(DefaultPluginRequestApplicator.java:108)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:108)
	at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:44)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:216)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:385)
```

I'm using plugin as follows: 

```kotlin
plugins {
    alias(libs.plugins.composeMultiplatform)
```

in `libs.versions.toml`

```toml
[versions]
composeMultiplatform = "1.6.0-dev1350"

[plugins]
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
```

**Affected platforms**
- All

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.6.0-dev1350
- OS version(s)* (required for Desktop and iOS issues): macOS 14.1.1
- OS architecture (x86 or arm64): arm64 
- JDK (for desktop issues): 17

**Project**

https://github.com/serbelga/Todometer-KMP

**Comment by igordmn** [comment]
Thanks! As a workaround, place `alias(libs.plugins.composeMultiplatform)` after `alias(libs.plugins.kotlinMultiplatform)`.

A reproducer:
1. `git clone https://github.com/JetBrains/compose-multiplatform-template`
2. replace Compose version in `./gradle.properties`:
```
compose.version=1.6.0-dev1354
```
3. place `id("org.jetbrains.compose")` before `id("org.jetbrains.compose")` in `desktopApp/build.gradle.kts`

4. `./gradlew run`

@terrakok, can we place `project.configureResourceGenerator()` in `project.afterEvaluate {`?

**Comment by serbelga** [comment]
Thanks!! now it works 👌

**Comment by terrakok** [comment]
@igordmn `afterEvaluate` is a dirty hack 😉 
I will fix it a correct way: wrap it into 
`pluginManager.withPlugin(KOTLIN_MPP_PLUGIN_ID) {...}`

**Comment by terrakok** [comment]
fixed by https://github.com/JetBrains/compose-multiplatform/pull/4079/commits/5d19551e015276861ab9627320441485f20febac

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4082">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
