### ISSUE TITLE
`ComposeRuntimeError` when using `assertThrows()` in Composable tests

### ISSUE THREAD

**Issue by yevhenii-nadtochii** [JetBrains/compose-multiplatform#4110]
**Describe the bug**

I've created `rememberMyState()` util function. This is a composable function that uses the coroutine scope and a composition local variable. It initializes a state, remembers it and **returns the created state**. 

Looks like something well-established in Compose world. If my function can't initialize, it throws. And I wanted to test this scenario with Compose test lib (`compose.desktop.uiTestJUnit4`).

The test code looks like the following:

```kotlin
    @Test
    fun testFails() {
        rule.setContent {
            val exception = assertThrows<IllegalStateException> {
                val state = rememberMyState()
            }
            val expectedMsg = "Couldn't initialize something ...."
            exception.message shouldStartWith expectedMsg
        }
    }
```

Running of this test leads to the following exception: 

>>androidx.compose.runtime.ComposeRuntimeError: Compose Runtime internal error. Unexpected or incorrect use of the Compose internal runtime API (Start/end imbalance). Please report to Google or use https://goo.gle/compose-feedback

<details>
<summary>Full stack trace</summary>

```
androidx.compose.runtime.ComposeRuntimeError: Compose Runtime internal error. Unexpected or incorrect use of the Compose internal runtime API (Start/end imbalance). Please report to Google or use https://goo.gle/compose-feedback
	at androidx.compose.runtime.ComposerKt.composeRuntimeError(Composer.kt:4558)
	at androidx.compose.runtime.ComposerImpl.finalizeCompose(Composer.kt:4744)
	at androidx.compose.runtime.ComposerImpl.endRoot(Composer.kt:1457)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3356)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3274)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:588)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1013)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
	at androidx.compose.ui.platform.Wrapper_skikoKt.setContent(Wrapper.skiko.kt:46)
	at androidx.compose.ui.scene.MultiLayerComposeSceneImpl.createComposition(MultiLayerComposeScene.skiko.kt:201)
	at androidx.compose.ui.scene.BaseComposeScene.setContent(BaseComposeScene.skiko.kt:137)
	at androidx.compose.ui.test.SkikoComposeUiTest$setContent$1.invoke(ComposeUiTest.skikoMain.kt:287)
	at androidx.compose.ui.test.SkikoComposeUiTest$setContent$1.invoke(ComposeUiTest.skikoMain.kt:286)
	at androidx.compose.ui.test.junit4.DesktopSynchronization_desktopKt.runOnUiThread$lambda$0(DesktopSynchronization.desktop.kt:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.6.0-dev1334
- OS version(s)* (required for Desktop and iOS issues): macOS
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): openjdk 17.0.9 LTS

**Expected behavior**
The test can use `assertThrows` assertions.

As far as I understand, It is illegal to `return` and `throw` in Compose functions that emit UI (name starts with an uppercase letter). But it seems OK for util composable functions (name starts with a lowercase letter).

**Comment by MatkovIvan** [comment]
Long story short: `Try catch is not supported around composable function invocations.`
`assertThrows` here just hides the real intent from the compiler, so I'd expect here that it should not compile at all.

> It is illegal to return and throw in Compose functions that emit UI (name starts with an uppercase letter). But it seems OK for util composable functions (name starts with a lowercase letter).

It doesn't really matter if it's "util" or "ui", since the root of it is the ability to be called independently during recomposition. BTW return a value from compose function is a valid scenario.

**Comment by yevhenii-nadtochii** [comment]
To be honest, I'm a bit unclear with this. 

1. In general, `return` and `throw` are **both valid** within a composable?
2. `try-catch` is invalid. Thus, we can't test `throw` scenario because composables are tested within another composable (`rule.setContent { ... }`)?

If (1) is true, then this is unusual that a valid scenario can't be tested. Is this a well-known restriction in Compose testing?

**Comment by MatkovIvan** [comment]
1. No, in general throwing exceptions is invalid inside composable function.
2. Yes. But it's not about testing, it's about compose runtime - you cannot catch what you are throwing because composable functions might be called independently during recomposition. Also, please note that this  `try`/`catch` restriction is about wrapping composable functions, but you still can use it around regular function calls inside composable function.

**Comment by yevhenii-nadtochii** [comment]
@MatkovIvan got it. Thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4110">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
