### ISSUE TITLE
`java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge` when executing `runDistributable` or exe

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#4126]
**Describe the bug**

When I try to :runDistributable or execute the app exe after it has been installed on the system I get the following error:

```
Task :runDistributable
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
	at java.desktop/java.awt.Toolkit.newAWTError(Unknown Source)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
	at java.desktop/javax.swing.UIManager.<clinit>(Unknown Source)
	at org.jetbrains.skiko.Actuals_awtKt.setSystemLookAndFeel(Actuals.awt.kt:14)
	at org.jetbrains.skiko.Setup.init(Setup.kt:25)
	at org.jetbrains.skiko.Setup.init$default(Setup.kt:6)
	at org.jetbrains.skiko.Library.load(Library.kt:62)
	at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
	at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose(ConfigureSwingGlobalsForCompose.desktop.kt:49)
	at androidx.compose.ui.ConfigureSwingGlobalsForCompose_desktopKt.configureSwingGlobalsForCompose$default(ConfigureSwingGlobalsForCompose.desktop.kt:38)
	at androidx.compose.ui.window.Application_desktopKt.application(Application.desktop.kt:110)
	at androidx.compose.ui.window.Application_desktopKt.application$default(Application.desktop.kt:105)
	at ...MainKt.main(Main.kt:20)
	at ...MainKt.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	... 24 more
Failed to launch JVM
```

**Affected platforms**
- Desktop

**Versions**
- Kotlin version: 1.9.21
- Compose Multiplatform version: 1.5.11
- OS version(s): Windows 11
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): Oracle OpenJDK 17.0.9

**To Reproduce**
It was in a new project (with some modifications).

**Expected behavior**
The app should run successfully without showing error dialog and terminating.

**Additional context**
See https://stackoverflow.com/q/15260989

**Comment by pjBooms** [comment]
>I think I didn't have this problem in one of my other compose multiplatform projects.

That is because you either had a static dependency on accessibility or it was not triggered at runtime. Closing the issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4126">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
