### ISSUE TITLE
NoSuchMethodError: No virtual method `androidx/compose/animation/core/KeyframesSpec` on Compose Multiplatform 1.6.0-beta01

### ISSUE THREAD

**Issue by serbelga** [JetBrains/compose-multiplatform#4175]
When I updated to Compose Multiplatform `1.6.0-beta01` the following exception is thrown when I use a `androidx.compose.material3.LinearProgressIndicator`:

`java.lang.NoSuchMethodError: No virtual method at(Ljava/lang/Object;I)Landroidx/compose/animation/core/KeyframesSpec$KeyframeEntity; in class Landroidx/compose/animation/core/KeyframesSpec$KeyframesSpecConfig`

```
java.lang.NoSuchMethodError: No virtual method at(Ljava/lang/Object;I)Landroidx/compose/animation/core/KeyframesSpec$KeyframeEntity; in class Landroidx/compose/animation/core/KeyframesSpec$KeyframesSpecConfig; or its super classes (declaration of 'androidx.compose.animation.core.KeyframesSpec$KeyframesSpecConfig' appears in /data/app/~~cEzi7ic26QhD9_ogtOxoAQ==/dev.sergiobelda.todometer-NVVBt-ZhVlGzT-rH8Qzr4g==/base.apk)
                                                                                                    	at androidx.compose.material3.ProgressIndicatorKt$CircularProgressIndicator$endAngle$1.invoke(ProgressIndicator.kt:371)
                                                                                                    	at androidx.compose.material3.ProgressIndicatorKt$CircularProgressIndicator$endAngle$1.invoke(ProgressIndicator.kt:369)
                                                                                                    	at androidx.compose.animation.core.AnimationSpecKt.keyframes(AnimationSpec.kt:649)
                                                                                                    	at androidx.compose.material3.ProgressIndicatorKt.CircularProgressIndicator-LxG7B9w(ProgressIndicator.kt:369)
                                                                                                    	at dev.sergiobelda.todometer.app.common.ui.loading.ContentLoadingProgressKt.ContentLoadingProgress(ContentLoadingProgress.kt:29)
                                                                                                    	at dev.sergiobelda.todometer.app.feature.home.ui.HomeScreenKt$HomeScreen$3$4.invoke(HomeScreen.kt:234)
                                                                                                    	at dev.sergiobelda.todometer.app.feature.home.ui.HomeScreenKt$HomeScreen$3$4.invoke(HomeScreen.kt:203)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:239)
                                                                                                    	at androidx.compose.material3.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:221)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:989)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:476)
```

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version: 1.9.22
- Compose Multiplatform version: 1.6.0-beta01
- JDK: 17 

**Sample**
https://github.com/serbelga/Todometer-KMP

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4175">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
