### ISSUE TITLE
NPE in WindowDraggableArea.desktop.kt in java.awt.PointerInfo.getLocation()

### ISSUE THREAD

**Issue by Nohus** [JetBrains/compose-multiplatform#4179]
**Describe the bug**
NullPointerException in `WindowsDraggableArea.desktop.kt`

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Windows 10, 10.0.19044.1889
- OS architecture (x86 or arm64): amd64
- JDK (for desktop issues): Oracle Corporation 17.0.2

**To Reproduce**
Unknown, received in automated crash report

**Expected behavior**
App does not crash

**Additional context**
Stack trace:
```
java.lang.NullPointerException: Cannot invoke "java.awt.PointerInfo.getLocation()" because the return value of "java.awt.MouseInfo.getPointerInfo()" is null
    at androidx.compose.foundation.window.DragHandler.drag(WindowDraggableArea.desktop.kt:82)
    at androidx.compose.foundation.window.DragHandler.access$drag(WindowDraggableArea.desktop.kt:60)
    at androidx.compose.foundation.window.DragHandler$dragListener$1.mouseDragged(WindowDraggableArea.desktop.kt:65)
    at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:328)
    at java.awt.Component.processMouseMotionEvent(Component.java:6674)
    at java.awt.Component.processEvent(Component.java:6395)
    at java.awt.Component.dispatchEventImpl(Component.java:5001)
    at java.awt.Component.dispatchEvent(Component.java:4833)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.awt.EventQueue$4.run(EventQueue.java:716)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
    at java.awt.EventQueue$5.run(EventQueue.java:746)
    at java.awt.EventQueue$5.run(EventQueue.java:744)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by kirill-grouchnikov** [comment]
Was this done as a test in a headless environment?

**Comment by Nohus** [comment]
Slack conversation: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1706218564739489

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4179">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
