### ISSUE TITLE
Compilation fails with ~200 items in strings.xml (MethodTooLargeException)

### ISSUE THREAD

**Issue by asapha** [JetBrains/compose-multiplatform#4194]
## Description

I'm not sure what should be considered as a reasonable amount of strings in a `strings.xml` file but, when trying to replace moko-resources in an existing project, it failed to compile with this error:

```java
exception: exception: java.lang.RuntimeException: Error generating class file components/resources/demo/shared/generated/resources/Res$string.class (compiled from [compose-multiplatform/components/resources/demo/shared/build/generated/compose/resourceGenerator/kotlin/components/resources/demo/shared/generated/resources/Res.kt]): Method too large: components/resources/demo/shared/generated/resources/Res$string.<clinit> ()V
exception: 	at org.jetbrains.kotlin.codegen.ClassFileFactory$OutputClassFile.asByteArray(ClassFileFactory.java:310)
exception: 	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:33)
exception: 	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAllTo(outputUtils.kt:47)
exception: 	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:52)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.CliCompilerUtilsKt.writeOutput(cliCompilerUtils.kt:134)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.CliCompilerUtilsKt$createOutputFilesFlushingCallbackIfPossible$1.invoke(cliCompilerUtils.kt:95)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.CliCompilerUtilsKt$createOutputFilesFlushingCallbackIfPossible$1.invoke(cliCompilerUtils.kt:93)
exception: 	at org.jetbrains.kotlin.codegen.state.GenerationStateKt$GenerationStateEventCallback$1.invoke(GenerationState.kt:412)
exception: 	at org.jetbrains.kotlin.codegen.state.GenerationStateKt$GenerationStateEventCallback$1.invoke(GenerationState.kt:411)
exception: 	at org.jetbrains.kotlin.codegen.state.GenerationState.afterIndependentPart(GenerationState.kt:363)
exception: 	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.invokeCodegen(JvmIrCodegenFactory.kt:366)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.runCodegen(KotlinToJVMBytecodeCompiler.kt:347)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:122)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
exception: 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
exception: 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
exception: 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
exception: 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:79)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:43)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:180)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit$default(CLITool.kt:175)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:167)
exception: 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler$Companion.main(K2JVMCompiler.kt:250)
exception: 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.main(K2JVMCompiler.kt)
exception: caused by: org.jetbrains.org.objectweb.asm.MethodTooLargeException: Method too large: components/resources/demo/shared/generated/resources/Res$string.<clinit> ()V
exception: 	at org.jetbrains.org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
exception: 	at org.jetbrains.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:489)
exception: 	at org.jetbrains.kotlin.codegen.ClassBuilderFactories$2.asBytes(ClassBuilderFactories.java:118)
exception: 	at org.jetbrains.kotlin.codegen.DelegatingClassBuilderFactory.asBytes(DelegatingClassBuilderFactory.kt:36)
exception: 	at org.jetbrains.kotlin.codegen.DelegatingClassBuilderFactory.asBytes(DelegatingClassBuilderFactory.kt:36)
exception: 	at org.jetbrains.kotlin.codegen.ClassFileFactory$ClassBuilderAndSourceFileList.asBytes(ClassFileFactory.java:343)
exception: 	at org.jetbrains.kotlin.codegen.ClassFileFactory$OutputClassFile.asByteArray(ClassFileFactory.java:307)
exception: 	... 25 more
exception: 
```

## Repro

In order to reproduce it, you can add the following code to `components/resources/demo/shared/build.gradle.kts`

<details>

<summary>generateStringFiles task</summary>

```kotlin
val template = """
    <resources>
        <string name="app_name">Compose Resources App</string>
        <string name="hello">😊 Hello world!</string>
        <string name="multi_line">Lorem ipsum dolor sit amet,
            consectetur adipiscing elit.
            Donec eget turpis ac sem ultricies consequat.</string>
        <string name="str_template">Hello, %1${"$"}s! You have %2${"$"}d new messages.</string>
        <string-array name="str_arr">
            <item>item 1</item>
            <item>item 2</item>
            <item>item 3</item>
        </string-array>
        [ADDITIONAL_STRINGS]
    </resources>    
""".trimIndent()

val generateStringFiles = tasks.register("generateStringFiles") {
    val numberOfLanguages = 15
    val numberOfStrings = 200
    val langs = Locale.getAvailableLocales()
        .map { it.language }
        .filter { it.count() == 2 }
        .sorted()
        .distinct()
        .take(numberOfLanguages)
        .toList()

    val resourcesFolder = project.file("src/commonMain/composeResources")

    doLast {
        // THIS REMOVES THE `values` FOLDER IN `composeResources`
        // THIS REMOVES THE `values` FOLDER IN `composeResources`
        // Necessary when reducing the number of languages.
        resourcesFolder.listFiles()?.filter { it.name.startsWith("values") }?.forEach {
            it.deleteRecursively()
        }

        langs.forEachIndexed { langIndex, lang ->
            val additionalStrings =
                (0 until numberOfStrings).joinToString(System.lineSeparator()) { index ->
                    """
                    <string name="string_${index.toString().padStart(4, '0')}">String $index in lang $lang</string>
                    """.trimIndent()
                }

            val langFile = if (langIndex == 0) {
                File(resourcesFolder, "values/strings.xml")
            } else {
                File(resourcesFolder, "values-$lang/strings.xml")
            }
            langFile.parentFile.mkdirs()
            langFile.writeText(template.replace("[ADDITIONAL_STRINGS]", additionalStrings))
        }
    }
}

tasks.named("generateComposeResClass") {
    dependsOn(generateStringFiles)
}
```

</details>

It'll create multiple `values-XXX/strings.xml` files, each filled with the requested amount of strings when you run `./gradlew :resources:demo:desktopApp:run`.
With the default values (200 strings, 15 languages), the `Res.kt` file will have 14k lines.

Tested with `compose.version=1.6.0-beta01`

## Workaround

Maintain different string files in multiple modules.

**Comment by tipapro** [comment]
The same problem occurs if we use a huge icon pack. [This pack](https://github.com/microsoft/fluentui-system-icons/tree/main/android/library/src/main/res/drawable) is for example.

**Comment by asapha** [comment]
Fixed for me, thanks!

@tipapro I'm closing the issue since it was specific to strings. I think you should open another one if the problem persists for your use case.

**Comment by terrakok** [comment]
@asapha Hi! It looks strange. there is even a test for the case: https://github.com/JetBrains/compose-multiplatform/blob/f833fa9945f0420fd9c0c0a5a03d45f196d231ec/gradle-plugins/compose/src/test/test-projects/misc/hugeResources/build.gradle.kts#L22

could you provide a small reproducer?

**Comment by asapha** [comment]
@terrakok I did a git pull on the compose repo, updated the gradle properties file with 1.6.0, and did the same repro steps as above.

I'll see if the test fails on my end.

**Comment by asapha** [comment]
@terrakok We can make the test fail if we add back qualifiers into the mix. 

You can replace `gradle-plugins/compose/src/test/test-projects/misc/hugeResources/build.gradle.kts` with this to repro:
```kotlin
import java.util.Locale

plugins {
    kotlin("multiplatform")
    id("org.jetbrains.compose")
}

group = "app.group"

kotlin {
    jvm("desktop")

    sourceSets {
        commonMain {
            dependencies {
                implementation(compose.runtime)
                implementation(compose.material)
                implementation(compose.components.resources)
            }
        }
    }
}

val generateResourceFiles = tasks.register("generateResourceFiles") {
    val resourcesFolder = project.file("src/commonMain/composeResources")
    val count = 25_000
    val numberOfLanguages = 5

    val langs = Locale.getAvailableLocales()
        .map { it.language }
        .filter { it.count() == 2 }
        .sorted()
        .distinct()
        .take(numberOfLanguages)
        .toList()

    doLast {
        langs.forEachIndexed { langIndex, lang ->
            val txt = buildString {
                appendLine("<resources>")
                repeat(count) {
                    appendLine("    <string name=\"str_${it}\">str_${it}</string>")
                }
                appendLine("</resources>")
            }

            val fileName = if (langIndex == 0) {
                "values/strings.xml"
            } else {
                "values-$lang/strings.xml"
            }

            File(resourcesFolder, fileName).apply {
                parentFile.mkdirs()
                writeText(txt)
            }
        }
    }
    doLast {
        repeat(count) {
            File(resourcesFolder, "drawable/icon_$it.xml").apply {
                parentFile.mkdirs()
                createNewFile() //empty file
            }
        }
    }
}

tasks.named("generateComposeResClass") {
    dependsOn(generateResourceFiles)
}
```

I tested with `val count = 1000`. I guess the qualifiers could also be added to the drawable part.

**Comment by terrakok** [comment]
thank you! will fix it today

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4194">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
