### ISSUE TITLE
Using painterResource(:DrawableResource) outside desktop Window can produce UnsatisfiedLinkError

### ISSUE THREAD

**Issue by vinceglb** [JetBrains/compose-multiplatform#4208]
**Describe the bug**
Using the new painterResource(:DrawableResource) from 1.6.0-beta01 outside desktop Window Composable produce an exception when launching the JVM app version packaged from Conveyor.

It's useful to display an icon in the Tray for example.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-beta01
- OS version(s)* (required for Desktop and iOS issues): macOS 14.2.1 (23C71)
- OS architecture (x86 or arm64): Apple M1 Pro
- JDK (for desktop issues): 
```shell
> java --version
openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode)
```

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add Conveyor to a project containing JVM target

gradle/libs.versions.toml
```toml
[versions]
conveyor = "1.8"

[plugins]
conveyor = { id = "dev.hydraulic.conveyor", version.ref = "conveyor" }
```

build.gradle.kts
```kotlin
plugins {
    ...
    alias(libs.plugins.conveyor) apply false
}
```

composeApp/build.gradle.kts

> Note you need to use `jvm()` with Conveyor and not `jvm("desktop")`: https://github.com/hydraulic-software/conveyor/discussions/97#discussion-6151837

```kotlin
plugins {
    ...
    alias(libs.plugins.conveyor)
}

version = 0.1.0

kotlin {
    ...

    jvm()
    jvmToolchain(17)

    ...
}

dependencies {
    linuxAmd64(compose.desktop.linux_x64)
    macAmd64(compose.desktop.macos_x64)
    macAarch64(compose.desktop.macos_arm64)
    windowsAmd64(compose.desktop.windows_x64)
}

configurations.all {
    attributes {
        attribute(Attribute.of("ui", String::class.java), "awt")
    }
}
```

2. Add an image to commonMain/composeResources/drawable like `compose-multiplatform.xml`

3. Update jvmMain/kotlin/main.kt with this code:

```kotlin
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.size
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import kotlinproject.composeapp.generated.resources.Res
import org.jetbrains.compose.resources.ExperimentalResourceApi
import org.jetbrains.compose.resources.painterResource

@OptIn(ExperimentalResourceApi::class)
fun main() = application {
    val painter = painterResource(Res.drawable.compose_multiplatform) // androidx.compose.ui.res.painterResource("drawable/compose-multiplatform.xml")

    Window(
        title = "Kotlin",
        onCloseRequest = ::exitApplication,
    ) {
        Column {
            Image(
                painter = painter,
                contentDescription = null,
                modifier = Modifier.size(50.dp)
            )
        }
    }
}
```

4. Run `./gradlew jvmJar`

5. Build app with something like `conveyor -Kapp.machines=mac.amd64 make mac-app`. See here for more details: https://conveyor.hydraulic.dev/13.1/tutorial/tortoise/4-build-unpackaged

6. Open the app in the `output` folder. See screenshot for result.

**Reproduction repository**
https://github.com/vinceglb/ComposeMultiplatformUnsatisfiedLinkError
- Run `./gradlew jvmJar`
- Run `conveyor -Kapp.machines=mac.amd64 make mac-app` if you are using ARM Mac
- Open app in the output directory

**Expected behavior**
Launch the app normally.

**Screenshots**
![CleanShot 2024-01-30 at 22 35 21@2x](https://github.com/JetBrains/compose-multiplatform/assets/24540801/29bdf796-79a2-40b8-8c3b-b28e61cad68a)

**Additional context**
The code is working fine in debug mode. Also, I do not reproduce using `packageDmg` for example. It only happens when using `conveyor` command.

Finally, if we replace `painterResource(Res.drawable.compose_multiplatform)` by the old method: `painterResource(Res.drawable.compose_multiplatform)`, it will work.

Here is the modal log:
```
The application has experienced an internal error and must quit.

java.lang.UnsatisfiedLinkError: 'int org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme()'   @ org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme(Native Method)
```

**Comment by m-sasha** [comment]
I've encountered this issue in a different situation. It seems we're not loading skiko from `getCurrentSystemTheme()`, so if that function is called before skiko has been loaded by something else, it will fail.

**Comment by m-sasha** [comment]
@vinceglb is this specific to Conveyor? If you run the same code without Conveyor, does it also crash?

**Comment by vinceglb** [comment]
I tried to replicate the crash without Conveyor, but I didn't succeed. I can run the app in debug, and it's also working by using `packageDmg`.

I'm not sure if it's 100% related to Conveyor because everything is working except using this new method `painterResource()` outside of Window 🤷‍♂️

By running `conveyor run`, I got the whole stack:

```
❌ /Users/vincent/Library/Caches/Hydraulic/Conveyor/entries/21/ec/21eca544cfe8dca8/content/app/My Amazing Project.app/Contents/MacOS/My Amazing Project: Returned non-zero exit code 1
   java.lang.UnsatisfiedLinkError: 'int org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme()'                                                                                
           at org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme(Native Method)                                                                                              
           at org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme(SystemTheme.awt.kt:4)                                                                                       
           at androidx.compose.ui.SystemThemeKt$LocalSystemTheme$1.invoke(SystemTheme.kt:30)                                                                                          
           at androidx.compose.ui.SystemThemeKt$LocalSystemTheme$1.invoke(SystemTheme.kt:29)                                                                                          
           at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)                                                                                                                     
           at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)                                                                                                 
           at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)                                                                                                   
           at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:90)                                                                                          
           at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:2136)                                                                                                         
           at androidx.compose.foundation.DarkTheme_skikoKt._isSystemInDarkTheme(DarkTheme.skiko.kt:53)                                                                               
           at androidx.compose.foundation.DarkThemeKt.isSystemInDarkTheme(DarkTheme.kt:41)                                                                                            
           at org.jetbrains.compose.resources.ResourceEnvironmentKt$DefaultComposeEnvironment$1.rememberEnvironment(ResourceEnvironment.kt:26)                                        
           at org.jetbrains.compose.resources.ImageResourcesKt.painterResource(ImageResources.kt:52)                                                                                  
           at ComposableSingletons$MainKt$lambda-1$1.invoke(main.kt:14)                                                                                                               
           at ComposableSingletons$MainKt$lambda-1$1.invoke(main.kt:13)                                                                                                               
           at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)                                                                               
           at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)                                                                                
           at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:115)                                                                     
           at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:114)                                                                     
           at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)                                                                               
           at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)                                                                                
           at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:227)                                                          
           at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:226)                                                          
           at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)                                                                               
           at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)                                                                                
           at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)                                                                           
           at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:221)                                                            
           at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:219)                                                            
           at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)                                                                               
           at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)                                                                                
           at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:33)                                                                                          
           at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3303)                                                                                                       
           at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3236)                                                                                          
           at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:723)                                                                                             
           at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1071)                                                                                          
           at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:631)                                                                                             
           at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:617)                                                                                                 
           at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)                                                       
           at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                                  
           at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)                                                                                                            
           at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)                                                                                          
           at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)                                                                                                 
           at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)                                                                                                             
           at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)                                                                                                             
           at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)                                                                                        
           at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)                                                       
           at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)                                                                                                     
           at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)                                                                          
           at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)                                                                             
           at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)                                                                          
           at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)                                                                                      
           at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)                                                                                      
           at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)    
```

Here is the reproduction repository: https://github.com/vinceglb/ComposeMultiplatformUnsatisfiedLinkError

**Comment by m-sasha** [comment]
This should be fixed in the next release that upgrades Skiko. Please reopen the issue if it doesn't.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4208">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
