### ISSUE TITLE
MethodTooLargeException with huge icon pack

### ISSUE THREAD

**Issue by tipapro** [JetBrains/compose-multiplatform#4285]
**Describe the bug**
The build crashes despite fixed a similar bug https://github.com/JetBrains/compose-multiplatform/issues/4194

```kotlin
exception: exception: java.lang.RuntimeException: Error generating class file kotlinproject/composeapp/generated/resources/Res$drawable.class (compiled from [C:\Users\tipapro\Desktop\KotlinProject\composeApp\build\generated\compose\resourceGenerator\kotlin\kotlinproject\composeapp\generated\resources\Res.kt]): Method too large: kotlinproject/composeapp/generated/resources/Res$drawable.<clinit> ()V
exception: 	at org.jetbrains.kotlin.codegen.ClassFileFactory$OutputClassFile.asByteArray(ClassFileFactory.java:310)
exception: 	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:33)
exception: 	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAllTo(outputUtils.kt:47)
exception: 	at org.jetbrains.kotlin.cli.common.output.OutputUtilsKt.writeAll(outputUtils.kt:52)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.CliCompilerUtilsKt.writeOutput(cliCompilerUtils.kt:134)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.CliCompilerUtilsKt$createOutputFilesFlushingCallbackIfPossible$1.invoke(cliCompilerUtils.kt:95)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.CliCompilerUtilsKt$createOutputFilesFlushingCallbackIfPossible$1.invoke(cliCompilerUtils.kt:93)
exception: 	at org.jetbrains.kotlin.codegen.state.GenerationStateKt$GenerationStateEventCallback$1.invoke(GenerationState.kt:412)
exception: 	at org.jetbrains.kotlin.codegen.state.GenerationStateKt$GenerationStateEventCallback$1.invoke(GenerationState.kt:411)
exception: 	at org.jetbrains.kotlin.codegen.state.GenerationState.afterIndependentPart(GenerationState.kt:363)
exception: 	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.invokeCodegen(JvmIrCodegenFactory.kt:366)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.runCodegen(KotlinToJVMBytecodeCompiler.kt:347)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:122)
exception: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
exception: 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
exception: 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
exception: 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
exception: 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:79)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:43)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:180)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit$default(CLITool.kt:175)
exception: 	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:167)
exception: 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler$Companion.main(K2JVMCompiler.kt:250)
exception: 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.main(K2JVMCompiler.kt)
exception: caused by: org.jetbrains.org.objectweb.asm.MethodTooLargeException: Method too large: kotlinproject/composeapp/generated/resources/Res$drawable.<clinit> ()V
exception: 	at org.jetbrains.org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2087)
exception: 	at org.jetbrains.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:489)
exception: 	at org.jetbrains.kotlin.codegen.ClassBuilderFactories$2.asBytes(ClassBuilderFactories.java:118)
exception: 	at org.jetbrains.kotlin.codegen.DelegatingClassBuilderFactory.asBytes(DelegatingClassBuilderFactory.kt:36)
exception: 	at org.jetbrains.kotlin.codegen.DelegatingClassBuilderFactory.asBytes(DelegatingClassBuilderFactory.kt:36)
exception: 	at org.jetbrains.kotlin.codegen.ClassFileFactory$ClassBuilderAndSourceFileList.asBytes(ClassFileFactory.java:343)
exception: 	at org.jetbrains.kotlin.codegen.ClassFileFactory$OutputClassFile.asByteArray(ClassFileFactory.java:307)
exception: 	... 25 more
exception: 
```

**Versions**
- Compose Multiplatform version: 1.6.0-beta02

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create template KMP project
2. Add all icons from [there](https://github.com/microsoft/fluentui-system-icons/tree/main/android/library/src/main/res/drawable)

**Comment by terrakok** [comment]
<img width="1084" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/3532155/a99e4abf-0380-4293-ab06-eb2dc1ca483c">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4285">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
