### ISSUE TITLE
[1.6.0] Could not load font

### ISSUE THREAD

**Issue by dhng22** [JetBrains/compose-multiplatform#4387]
Happened on the new composeResources system:

`FATAL EXCEPTION: main
                                                                                                    Process: , PID: 14880
                                                                                                    java.lang.IllegalStateException: Could not load font
                                                                                                    	at androidx.compose.ui.text.font.TypefaceRequestCache.runCached(FontFamilyResolver.kt:207)
                                                                                                    	at androidx.compose.ui.text.font.FontFamilyResolverImpl.resolve(FontFamilyResolver.kt:92)
                                                                                                    	at androidx.compose.ui.text.font.FontFamilyResolverImpl.resolve-DPcqOEQ(FontFamilyResolver.kt:79)
                                                                                                    	at androidx.compose.foundation.text.TextFieldSizeKt$textFieldMinSize$1.invoke(TextFieldSize.kt:47)
                                                                                                    	at androidx.compose.foundation.text.TextFieldSizeKt$textFieldMinSize$1.invoke(TextFieldSize.kt:38)
                                                                                                    	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:270)
                                                                                                    	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:265)
                                                                                                    	at androidx.compose.ui.Modifier$Element.foldIn(Modifier.kt:136)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:396)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:396)
                                                                                                    	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:396)
                                                                                                    	at androidx.compose.ui.ComposedModifierKt.materializeModifier(ComposedModifier.kt:265)
                                                                                                    	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke-Deg8D_g(Layout.kt:205)
                                                                                                    	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke(Layout.kt:203)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.foundation.text.selection.SimpleLayoutKt.SimpleLayout(SimpleLayout.kt:79)
                                                                                                    	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$5$1.invoke(CoreTextField.kt:668)
                                                                                                    	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$5$1.invoke(CoreTextField.kt:643)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.TextFieldKt.TextFieldLayout(TextField.kt:617)
                                                                                                    	at androidx.compose.material3.TextFieldImplKt$CommonDecorationBox$3.invoke-eopBjH0(TextFieldImpl.kt:205)
                                                                                                    	at androidx.compose.material3.TextFieldImplKt$CommonDecorationBox$3.invoke(TextFieldImpl.kt:113)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:228)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.TextFieldTransitionScope.Transition-DTcfvLk(TextFieldImpl.kt:382)
                                                                                                    	at androidx.compose.material3.TextFieldImplKt.CommonDecorationBox(TextFieldImpl.kt:103)
                                                                                                    	at androidx.compose.material3.TextFieldDefaults.DecorationBox(TextFieldDefaults.kt:500)
                                                                                                    	at androidx.compose.material3.TextFieldKt$TextField$2$1.invoke(TextField.kt:223)
                                                                                                    	at androidx.compose.material3.TextFieldKt$TextField$2$1.invoke(TextField.kt:221)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$5.invoke(CoreTextField.kt:643)
                                                                                                    	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$5.invoke(CoreTextField.kt:642)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.foundation.text.CoreTextFieldKt.CoreTextFieldRootBox(CoreTextField.kt:1305)
                                                                                                    	at androidx.compose.foundation.text.CoreTextFieldKt.CoreTextField(CoreTextField.kt:642)
                                                                                                    	at androidx.compose.foundation.text.BasicTextFieldKt.BasicTextField(BasicTextField.kt:166)
                                                                                                    	at androidx.compose.material3.TextFieldKt$TextField$2.invoke(TextField.kt:201)
                                                                                                    	at androidx.compose.material3.TextFieldKt$TextField$2.invoke(TextField.kt:200)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)`

**To Reproduce**
Put google font inside composeResources(.tff extension):
![image](https://github.com/JetBrains/compose-multiplatform/assets/86188270/f564610b-5698-4e1b-84dc-7f367bdb1cb5)

then call it with FontResource
![image](https://github.com/JetBrains/compose-multiplatform/assets/86188270/0f2ca586-55f9-44ad-a875-420a88a9d0f0)

then use created font with Typography
![image](https://github.com/JetBrains/compose-multiplatform/assets/86188270/18c74c50-9d5f-4e4f-acfd-6d9979a45b65)

Typography then used with MaterialTheme
![image](https://github.com/JetBrains/compose-multiplatform/assets/86188270/6a83254b-4eb0-4020-b348-7755636bc724)

**Expected behavior**
Font load and works

**Comment by dhng22** [comment]
Nevermind, I've just read the updated doc that multimodule is not supported yet. These font are indeed loaded from another module beside **shared**. Please tell me if i'm correct

**Comment by MatkovIvan** [comment]
> multimodule is not supported yet

Yep, that's correct

**Comment by MatkovIvan** [comment]
Issue to track #4229

**Comment by sereden** [comment]
I'm facing the same issue when using `@Preview` (due to limitations of KMM we create Previews in the Android part).
I also created a regular `res` folder and moved fonts over there but the issue persist. Are there any workarounds for this?
I'm considering using a default (Roboto) font for the preview as the last call but it doesn't provide the same Look and Fill as the real fonts

**Comment by dhng22** [comment]
@MatkovIvan Is multi-module resource supported in **1.6.10-dev1523**?

**Comment by parfenovedyard** [comment]
I had the same issue.
Updating compose plugin from 1.6.0 to 1.6.1 helped.

**Comment by dhng22** [comment]
@parfenovedyard I thought they said multimodule requires Kotlin 2.0.0-Beta5 minimum? What kotlin version are you using

**Comment by terrakok** [comment]
You could try [1.6.10-dev1557](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-dev1557) 
But it is under active development and there is no guaranties

**Comment by parfenovedyard** [comment]
> @parfenovedyard I thought they said multimodule requires Kotlin 2.0.0-Beta5 minimum? What kotlin version are you using

1.9.23

**Comment by quan7794** [comment]
> I had the same issue. Updating compose plugin from 1.6.0 to 1.6.1 helped.

I'm using 1.6.2 version, and the issue happened. After downgraded to 16.1, the issue gone. Thanks

I don't know why it's happing on newest version of Compose Plugin when it's fixed on 1.6.1. Look like they do not verify it enough.

**Comment by dhng22** [comment]
@quan7794 Can you contact me with the email I provided in my bio? I have some issue hope you can resolve

**Comment by rishabhsingh2002** [comment]
Changing from 1.6.1 to 1.6.2 works for me

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4387">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by radbobdad** [comment]
I am using Compose Plugin 1.5.1. Changing to 1.5.0+sync+run and back to 1.5.1 did not resolve this issue for me.
When I try 1.6.1 or 1.6.2 it says it can't find it. Running Koala 2024.1.1 Patch 1.
