### ISSUE TITLE
Common Preview does not render with string resources

### ISSUE THREAD

**Issue by michalguspiel** [JetBrains/compose-multiplatform#4400]
**Describe the bug**
Preview doesn't render when composable contains string resource. Yes, application builds and run.

**Affected platforms**

- [ ] Desktop (Windows, Linux, macOS)
- [ ] iOS
- [ ] Web (K/Wasm) - Canvas based API
- [ ] Web (K/JS) - Canvas based API
- [ ] Web (K/JS) - HTML library
- [x] Across Platforms - Common Module

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64):
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a Preview of Composable that uses Improved resources API (compose.components.resources)

**Expected behavior**
Preview should render

**Additional context**
```
@OptIn(ExperimentalResourceApi::class)
@Composable
fun EmptyContent(modifier: Modifier = Modifier) {
  Box(modifier, contentAlignment = Alignment.Center) {
    Text(stringResource(Res.string.no_data_available))
  }
}

@Preview
@Composable
fun PreviewEmptyContent(){
  EmptyContent()
}
```

```
Caused by: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: values/strings.xml
	at org.jetbrains.compose.resources.ResourceReader_desktopKt.readResourceBytes(ResourceReader.desktop.kt:9)
	at org.jetbrains.compose.resources.ResourceReaderKt$DefaultResourceReader$1.read(ResourceReader.kt:23)
	at org.jetbrains.compose.resources.StringResourcesKt.parseStringXml(StringResources.kt:54)
	at org.jetbrains.compose.resources.StringResourcesKt.access$parseStringXml(StringResources.kt:1)
	at org.jetbrains.compose.resources.StringResourcesKt$getParsedStrings$2$deferred$1$1$1.invokeSuspend(StringResources.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.jetbrains.compose.resources.ResourceState_blockingKt.rememberResourceState(ResourceState.blocking.kt:15)
	at org.jetbrains.compose.resources.StringResourcesKt.stringResource(StringResources.kt:81)
	at fi.solita.hrnd.designSystem.EmptyContentKt.EmptyContent(EmptyContent.kt:18)
	at fi.solita.hrnd.designSystem.EmptyContentKt.PreviewEmptyContent(EmptyContent.kt:25)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 48 more
```

**Comment by MatkovIvan** [comment]
Tracking it here: #4338

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4400">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
