### ISSUE TITLE
[examples/chat] Android run gives java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by SamuelMarks** [JetBrains/compose-multiplatform#4429]
**Describe the bug**
No edits. Ran from e8e7afa in Android Studio Iguana | 2023.2.1/

**Affected platforms**
- [ ] Desktop (Windows, Linux, macOS)
- [ ] iOS
- [ ] Web (K/Wasm) - Canvas based API
- [ ] Web (K/JS) - Canvas based API
- [ ] Web (K/JS) - HTML library

**Versions**
- Kotlin version*:  Stable - 232-1.9.0-release-358-AS10227.8.2321.11479570
- Compose Multiplatform version*: 
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 23.10 with 6.7.7 kernel
- OS architecture (x86 or arm64): x86_64
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 19.0.2

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Execute `studio 'examples/chat'`
2. Press ▶ for androidApp
3. See logcat error and no app opens

**Expected behavior**
No error

**Screenshots**

**Additional context**
````
I  Late-enabling -Xcheck:jni
2024-03-04 20:05:40.985  8682-8682  .jetbrains.Chat         org.jetbrains.Chat                   I  Using CollectorTypeCC GC.
2024-03-04 20:05:40.986  8682-8682  .jetbrains.Chat         org.jetbrains.Chat                   W  Unexpected CPU variant for x86: x86_64.
                                                                                                    Known variants: atom, sandybridge, silvermont, goldmont, goldmont-plus, tremont, kabylake, default
2024-03-04 20:05:41.052  8682-8682  Compatibil...geReporter org.jetbrains.Chat                   D  Compat change id reported: 171979766; UID 10192; state: ENABLED
2024-03-04 20:05:41.053  8682-8682  Compatibil...geReporter org.jetbrains.Chat                   D  Compat change id reported: 242716250; UID 10192; state: ENABLED
2024-03-04 20:05:41.061  8682-8682  ziparchive              org.jetbrains.Chat                   W  Unable to open '/data/app/~~jzr6MpLJ13k5aGwZsJSOqQ==/org.jetbrains.Chat-9u-bJ4AIVUM_v0_ECiEyKQ==/base.dm': No such file or directory
2024-03-04 20:05:41.061  8682-8682  ziparchive              org.jetbrains.Chat                   W  Unable to open '/data/app/~~jzr6MpLJ13k5aGwZsJSOqQ==/org.jetbrains.Chat-9u-bJ4AIVUM_v0_ECiEyKQ==/base.dm': No such file or directory
2024-03-04 20:05:41.270  8682-8682  nativeloader            org.jetbrains.Chat                   D  Configuring clns-6 for other apk /data/app/~~jzr6MpLJ13k5aGwZsJSOqQ==/org.jetbrains.Chat-9u-bJ4AIVUM_v0_ECiEyKQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~jzr6MpLJ13k5aGwZsJSOqQ==/org.jetbrains.Chat-9u-bJ4AIVUM_v0_ECiEyKQ==/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/org.jetbrains.Chat
2024-03-04 20:05:41.283  8682-8682  GraphicsEnvironment     org.jetbrains.Chat                   V  Currently set values for:
2024-03-04 20:05:41.284  8682-8682  GraphicsEnvironment     org.jetbrains.Chat                   V    angle_gl_driver_selection_pkgs=[]
2024-03-04 20:05:41.284  8682-8682  GraphicsEnvironment     org.jetbrains.Chat                   V    angle_gl_driver_selection_values=[]
2024-03-04 20:05:41.284  8682-8682  GraphicsEnvironment     org.jetbrains.Chat                   V  ANGLE GameManagerService for org.jetbrains.Chat: false
2024-03-04 20:05:41.284  8682-8682  GraphicsEnvironment     org.jetbrains.Chat                   V  org.jetbrains.Chat is not listed in per-application setting
2024-03-04 20:05:41.284  8682-8682  GraphicsEnvironment     org.jetbrains.Chat                   V  Neither updatable production driver nor prerelease driver is supported.
2024-03-04 20:05:41.314  8682-8722  libEGL                  org.jetbrains.Chat                   D  loaded /vendor/lib64/egl/libEGL_emulation.so
2024-03-04 20:05:41.315  8682-8722  libEGL                  org.jetbrains.Chat                   D  loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
2024-03-04 20:05:41.317  8682-8722  libEGL                  org.jetbrains.Chat                   D  loaded /vendor/lib64/egl/libGLESv2_emulation.so
2024-03-04 20:05:41.341  8682-8682  AppCompatDelegate       org.jetbrains.Chat                   D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
2024-03-04 20:05:41.414  8682-8682  .jetbrains.Chat         org.jetbrains.Chat                   W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2024-03-04 20:05:41.414  8682-8682  .jetbrains.Chat         org.jetbrains.Chat                   W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2024-03-04 20:05:41.432  8682-8682  Compatibil...geReporter org.jetbrains.Chat                   D  Compat change id reported: 237531167; UID 10192; state: DISABLED
2024-03-04 20:05:41.433  8682-8682  OpenGLRenderer          org.jetbrains.Chat                   W  Unknown dataspace 0
--------- beginning of crash
2024-03-04 20:05:41.621  8682-8682  AndroidRuntime          org.jetbrains.Chat                   D  Shutting down VM
2024-03-04 20:05:41.633  8682-8682  AndroidRuntime          org.jetbrains.Chat                   E  FATAL EXCEPTION: main
                                                                                                    Process: org.jetbrains.Chat, PID: 8682
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:562)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
                                                                                                    Caused by: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: drawable/background.jpg
                                                                                                    	at org.jetbrains.compose.resources.ResourceReader_androidKt.readResourceBytes(ResourceReader.android.kt:16)
                                                                                                    	at org.jetbrains.compose.resources.ResourceReaderKt$DefaultResourceReader$1.read(ResourceReader.kt:23)
                                                                                                    	at org.jetbrains.compose.resources.ImageResourcesKt$loadImage$2$deferred$1$1$1.invokeSuspend(ImageResources.kt:134)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
                                                                                                    	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                                                                                                    	at org.jetbrains.compose.resources.ResourceState_blockingKt.rememberResourceState(ResourceState.blocking.kt:15)
                                                                                                    	at org.jetbrains.compose.resources.ImageResourcesKt.imageResource(ImageResources.kt:74)
                                                                                                    	at org.jetbrains.compose.resources.ImageResourcesKt.painterResource(ImageResources.kt:58)
                                                                                                    	at ChatAppKt$ChatApp$1$1.invoke(ChatApp.kt:72)
                                                                                                    	at ChatAppKt$ChatApp$1$1.invoke(ChatApp.kt:70)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:138)
                                                                                                    	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:115)
                                                                                                    	at ChatAppKt$ChatApp$1.invoke(ChatApp.kt:70)
                                                                                                    	at ChatAppKt$ChatApp$1.invoke(ChatApp.kt:69)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at ChatAppKt$Theme$1$1.invoke(ChatApp.kt:124)
                                                                                                    	at ChatAppKt$Theme$1$1.invoke(ChatApp.kt:123)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
                                                                                                    	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:396)
                                                                                                    	at ChatAppKt$Theme$1.invoke(ChatApp.kt:123)
                                                                                                    	at ChatAppKt$Theme$1.invoke(ChatApp.kt:122)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:23)
                                                                                                    	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:82)
                                                                                                    	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:81)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
2024-03-04 20:05:41.636  8682-8682  AndroidRuntime          org.jetbrains.Chat                   E  	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
                                                                                                    	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:396)
                                                                                                    	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
                                                                                                    	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:72)
                                                                                                    	at ChatAppKt.Theme(ChatApp.kt:117)
                                                                                                    	at ChatAppKt.ChatApp(ChatApp.kt:69)
                                                                                                    	at ChatAppKt$ChatAppWithScaffold$1$1.invoke(ChatApp.kt:60)
                                                                                                    	at ChatAppKt$ChatAppWithScaffold$1$1.invoke(ChatApp.kt:59)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:587)
                                                                                                    	at androidx.compose.material.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:569)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:991)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:477)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3599)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:500)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:472)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:463)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:447)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:872)
                                                                                                    	at androidx.compose.material.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1.invoke-0kLqBqw(Scaffold.kt:569)
                                                                                                    	at androidx.compose.material.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1.invoke(Scaffold.kt:451)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:709)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
2024-03-04 20:05:41.638  8682-8682  AndroidRuntime          org.jetbrains.Chat                   E  	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1617)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:596)
                                                                                                    	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(Box.kt:122)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
                                                                                                    	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:646)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1617)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:596)
                                                                                                    	at androidx.compose.ui.layout.RootMeasurePolicy.measure-3p2s80s(RootMeasurePolicy.kt:38)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1617)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1145)
2024-03-04 20:05:41.640  8682-8682  AndroidRuntime          org.jetbrains.Chat                   E  	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:354)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureOnly(MeasureAndLayoutDelegate.kt:562)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureOnly(MeasureAndLayoutDelegate.kt:407)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.android.kt:1058)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(ComposeView.android.kt:302)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:289)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
                                                                                                    	at android.view.View.measure(View.java:27122)
                                                                                                    	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4182)
                                                                                                    	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2759)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3086)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:882)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	... 3 more
2024-03-04 20:05:41.652  8682-8682  Process                 org.jetbrains.Chat                   I  Sending signal. PID: 8682 SIG: 9
```

**Comment by igordmn** [comment]
@terrakok, could you, please look? I reproduced it on the latest `master` - android crashes with:
```
Caused by: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: drawable/background.jpg
```

**Comment by terrakok** [comment]
Yes, I see the problem. It should be fixed in 1.6.1 by f683673b7ed1bd9c8ec26d5f421b207af9a7561f
For now just run the build twice it will help

**Comment by terrakok** [comment]
I checked it with [1.6.10-dev1493](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-dev1493) and the bug is gone

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4429">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
