### ISSUE TITLE
StackOverflow with Compose Compiler 1.5.10

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#4455]
**Describe the bug**
Updating the Compose Compiler to 1.5.10 and Kotlin to 1.9.23 results in a StackOverflowError when building

```
e: java.lang.StackOverflowError

	at org.jetbrains.kotlin.types.StarProjectionImpl.<init>(StarProjectionImpl.kt:34)
> Task :samples:kotlin-inject:shared:compileReleaseKotlinAndroid FAILED
	at org.jetbrains.kotlin.types.TypeUtils.makeStarProjection(TypeUtils.java:482)
	at org.jetbrains.kotlin.types.StarProjectionImplKt$buildStarProjectionTypeByTypeParameters$1.get(StarProjectionImpl.kt:56)
	at org.jetbrains.kotlin.types.TypeConstructorSubstitution.get(TypeSubstitution.kt:64)
	at org.jetbrains.kotlin.types.TypeSubstitutor.unsafeSubstitute(TypeSubstitutor.java:206)
	at org.jetbrains.kotlin.types.TypeSubstitutor.substituteTypeArguments(TypeSubstitutor.java:373)
	at org.jetbrains.kotlin.types.TypeSubstitutor.substituteCompoundType(TypeSubstitutor.java:352)
	at org.jetbrains.kotlin.types.TypeSubstitutor.unsafeSubstitute(TypeSubstitutor.java:287)
	at org.jetbrains.kotlin.types.TypeSubstitutor.substituteWithoutApproximation(TypeSubstitutor.java:164)
	at org.jetbrains.kotlin.types.TypeSubstitutor.substitute(TypeSubstitutor.java:149)
	at org.jetbrains.kotlin.types.TypeSubstitutor.substitute(TypeSubstitutor.java:143)
	at org.jetbrains.kotlin.types.StarProjectionImplKt.buildStarProjectionTypeByTypeParameters(StarProjectionImpl.kt:60)
	at org.jetbrains.kotlin.types.StarProjectionImplKt.starProjectionType(StarProjectionImpl.kt:65)
	at org.jetbrains.kotlin.types.StarProjectionImpl$_type$2.invoke(StarProjectionImpl.kt:35)
	at org.jetbrains.kotlin.types.StarProjectionImpl$_type$2.invoke(StarProjectionImpl.kt:34)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.jetbrains.kotlin.types.StarProjectionImpl.get_type(StarProjectionImpl.kt:34)
	at org.jetbrains.kotlin.types.StarProjectionImpl.getType(StarProjectionImpl.kt:38)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
	at androidx.compose.compiler.plugins.kotlin.lower.ComposableSymbolRemapper$1.containsComposable(ComposableSymbolRemapper.kt:92)
```

**Comment by noook** [comment]
As per the documentation <https://developer.android.com/jetpack/androidx/releases/compose-kotlin> Compose compiler is compatible with kotlin `1.9.22`, maybe stick to this version while they update the compatibility map

**Comment by eymar** [comment]
> As per the documentation https://developer.android.com/jetpack/androidx/releases/compose-kotlin Compose compiler is compatible with kotlin `1.9.22`, maybe stick to this version while they update the compatibility map

In this case, it's about Compose Multiplatform compiler plugin 1.5.10 (not Jetpack Compose).
CM compiler 1.5.10 supports 1.9.23

**Comment by eygraber** [comment]
There's kind of a circular generic reference [here]( https://github.com/eygraber/portal/blob/master/samples/kotlin-inject/shared/src/commonMain/kotlin/com/eygraber/portal/samples/kotlin/inject/home/HomePortal.kt#L16) where `HomePortal` is a `InjectablePortal<HomeComponent>` and `HomeComponent` is a `PortalComponent<HomePortal>`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4455">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
