### ISSUE TITLE
Crash when restoring a hidden app in the tray in 1.6

### ISSUE THREAD

**Issue by hichamboushaba** [JetBrains/compose-multiplatform#4552]
**Describe the bug**
After upgrading to Compose 1.6, I noticed a weird crash that occurs when restoring a previously hidden app to the tray, I'll try to share more details below.
In my app, I have a main screen that shows a stack of different screens, and on the tray, there are shortcuts to some other screens, when an item in the tray is clicked and the app is hidden, the app switches to the shortcut screen, which removes the main screen from composition. This was working fine before, but now, when the shortcut screen is shown, any attempt to click on any clickable item would crash the app with an exception: `IllegalStateException: This node does not have an owner`

**Affected platforms**
- Desktop (Tested only on MacOS, but not sure this would have any impact)

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0
- OS version(s)* (required for Desktop and iOS issues): MacOS Sonoma 14.4
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): JDK 17 (Embedded JDK of Intellij Idea)

**To Reproduce**
1. Check the sample below (`Compose 1.6`)
2. Open the app.
3. Click on "Push"
4. Close the app (this will hide the app).
5. Right-click on the tray icon.
6. Click on "Dismiss" 
7. Notice the crash.

The other sample `Compose 1.5` shows that the crash doesn't occur on previous versions.

[Compose 1.6.zip](https://github.com/JetBrains/compose-multiplatform/files/14782500/Compose.1.6.zip)
[Compose 1.5.zip](https://github.com/JetBrains/compose-multiplatform/files/14782502/Compose.1.5.zip)

**Expected behavior**
The app shouldn't crash.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/1657201/0e9fa0f2-1ec3-4013-bc4c-10fc6646ce8e

**Additional context**
<details>
<summary>
Full Stack Trace
</summary>

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: This node does not have an owner.
	at androidx.compose.ui.node.DelegatableNodeKt.requireOwner(DelegatableNode.kt:314)
	at androidx.compose.ui.focus.FocusTargetNodeKt.requireTransactionManager(FocusTargetNode.kt:222)
	at androidx.compose.ui.focus.FocusTargetNode.commitFocusState$ui(FocusTargetNode.kt:160)
	at androidx.compose.ui.focus.FocusTransactionManager.commitTransaction(FocusTransactionManager.kt:87)
	at androidx.compose.ui.focus.FocusTransactionManager.access$commitTransaction(FocusTransactionManager.kt:27)
	at androidx.compose.ui.focus.FocusTransactionsKt.requestFocus(FocusTransactions.kt:321)
	at androidx.compose.ui.focus.FocusRequesterModifierNodeKt.requestFocus(FocusRequesterModifierNode.kt:43)
	at androidx.compose.foundation.ClickableKt.requestFocusWhenInMouseInputMode(Clickable.kt:1078)
	at androidx.compose.foundation.ClickableKt.access$requestFocusWhenInMouseInputMode(Clickable.kt:1)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$2.invokeSuspend(Clickable.kt:987)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$2.invoke-d-4ec7I(Clickable.kt)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$2.invoke(Clickable.kt)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$2.invokeSuspend(TapGestureDetector.kt:244)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:62)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:57)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:99)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:37)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

</details>

**Comment by Nohus** [comment]
I am also hitting this issue since updating to 1.6, and I can confirm it also happens on Windows.

**Comment by m-sasha** [comment]
The issue seems to be that `ComposeSceneFocusManagerImpl.requestFocus` and `ComposeSceneFocusManagerImpl.releaseFocus` request and release the focus without a `FocusTransactionManager` transaction. So the requests (the focus nodes) end up in (uncommitted) `FocusTransactionManager.states`. When the window is hidden and then re-shown, and at the same time the hierarchy changes such that some of the focus nodes become detached, the next `FocusTransactionManager` transaction will attempt to commit the requests, but the nodes are no longer attached.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4552">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
