### ISSUE TITLE
MACOS signing  java.nio.file.NoSuchFileException: picking

### ISSUE THREAD

**Issue by codaman** [JetBrains/compose-multiplatform#4578]
When signing kotlin compose Multiplatform application on macOS with M1 MacBook Air I got this error:

`14:32:07.419] java.nio.file.NoSuchFileException: picking
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:56)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1858)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2784)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2862)
        at jdk.jpackage/jdk.jpackage.internal.IOUtils.copyRecursive(IOUtils.java:126)
        at jdk.jpackage/jdk.jpackage.internal.IOUtils.copyRecursive(IOUtils.java:120)
        at jdk.jpackage/jdk.jpackage.internal.AbstractAppImageBuilder.copyApplication(AbstractAppImageBuilder.java:84)
        at jdk.jpackage/jdk.jpackage.internal.MacAppImageBuilder.prepareApplicationFiles(MacAppImageBuilder.java:340)
        at jdk.jpackage/jdk.jpackage.internal.AppImageBundler.createAppBundle(AppImageBundler.java:189)
        at jdk.jpackage/jdk.jpackage.internal.AppImageBundler.execute(AppImageBundler.java:93)
        at jdk.jpackage/jdk.jpackage.internal.Arguments.generateBundle(Arguments.java:714)
        at jdk.jpackage/jdk.jpackage.internal.Arguments.processArguments(Arguments.java:561)
        at jdk.jpackage/jdk.jpackage.main.Main.execute(Main.java:92)
        at jdk.jpackage/jdk.jpackage.main.Main.main(Main.java:53)
[14:32:07.421] jdk.jpackage.internal.PackagerException: java.nio.file.NoSuchFileException: picking
        at jdk.jpackage/jdk.jpackage.internal.AppImageBundler.execute(AppImageBundler.java:98)
        at jdk.jpackage/jdk.jpackage.internal.Arguments.generateBundle(Arguments.java:714)
        at jdk.jpackage/jdk.jpackage.internal.Arguments.processArguments(Arguments.java:561)
        at jdk.jpackage/jdk.jpackage.main.Main.execute(Main.java:92)
        at jdk.jpackage/jdk.jpackage.main.Main.main(Main.java:53)
Caused by: java.nio.file.NoSuchFileException: picking
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:56)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1858)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2784)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2862)
        at jdk.jpackage/jdk.jpackage.internal.IOUtils.copyRecursive(IOUtils.java:126)
        at jdk.jpackage/jdk.jpackage.internal.IOUtils.copyRecursive(IOUtils.java:120)
        at jdk.jpackage/jdk.jpackage.internal.AbstractAppImageBuilder.copyApplication(AbstractAppImageBuilder.java:84)
        at jdk.jpackage/jdk.jpackage.internal.MacAppImageBuilder.prepareApplicationFiles(MacAppImageBuilder.java:340)
        at jdk.jpackage/jdk.jpackage.internal.AppImageBundler.createAppBundle(AppImageBundler.java:189)
        at jdk.jpackage/jdk.jpackage.internal.AppImageBundler.execute(AppImageBundler.java:93)
        ... 4 more

> Task :createDistributable FAILED
`

I followed all these instructions in this tutorial
https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Signing_and_notarization_on_macOS

kotlin.version=1.8.0
agp.version=7.3.0
compose.version=1.5.10-beta02

This is my build.gradle.kts codes

`compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg,TargetFormat.Exe, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "packing_terminal"
            packageVersion = "1.0.0"

            windows{
                packageVersion = "1.0.0"
                msiPackageVersion = "1.0.0"
                exePackageVersion = "1.0.0"
            }
            macOS{

                bundleID = "XXXXXXXXXXXX"
                //iconFile.set(project.file("icon.icns"))
                entitlementsFile.set(project.file("macos/entitlement.plist"))

                runtimeEntitlementsFile.set(project.file("macos/runtime-entitlement.plist"))

                infoPlist {
                    extraKeysRawXml = project.file("macos/info.plist").readText()
                }

                signing{
                    sign.set(true)

                    identity.set("XXXXXXXX")
                    keychain.set("/Library/Keychains/System.keychain")
                }

                appStore = false

                notarization {
                    appleID.set("XXXXXXXX")
                    password.set("@keychain:NOTARIZATION_PackingTerminal")
                }
                val configRoot = project.file("macos/")
                provisioningProfile.set(configRoot.resolve("PackingTerminalProvision.provisionprofile"))
                runtimeProvisioningProfile.set(configRoot.resolve("PackingTerminalProvisionRuntime.provisionprofile"))

                // a version for all macOS distributables
                packageVersion = "1.0.0"
                // a version only for the dmg package
                dmgPackageVersion = "1.0.0"
                // a version only for the pkg package
                pkgPackageVersion = "1.0.0"

                // a build version for all macOS distributables
                packageBuildVersion = "1.0.0"
                // a build version only for the dmg package
                dmgPackageBuildVersion = "1.0.0"
                // a build version only for the pkg package
                pkgPackageBuildVersion = "1.0.0"
            }
        }
    }
}`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4578">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
