### ISSUE TITLE
org.jetbrains.skiko.SystemThemeHelper.getCurrentSystemTheme() crash

### ISSUE THREAD

**Issue by JagadishaIncture** [JetBrains/compose-multiplatform#4627]
Iam facing some issue with Desktop version while running

`@Composable
fun AppTheme(
    useDarkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit
) {
    MaterialTheme(
        colorScheme = if (useDarkTheme) {
            darkColorScheme()
        } else {
          lightColorScheme()
        },
        content = content
    )
}
`

Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: 'int org.jetbrains.skiko.SystemThemeHelper.getCurrentSystemTheme()'
	at org.jetbrains.skiko.SystemThemeHelper.getCurrentSystemTheme(Native Method)
	at org.jetbrains.skiko.SystemTheme_awtKt.getCurrentSystemTheme(SystemTheme.awt.kt:4)
	at androidx.compose.ui.SystemThemeKt$LocalSystemTheme$1.invoke(SystemTheme.kt:30)
	at androidx.compose.ui.SystemThemeKt$LocalSystemTheme$1.invoke(SystemTheme.kt:29)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
	at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:90)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:2136)
	at androidx.compose.foundation.DarkTheme_skikoKt._isSystemInDarkTheme(DarkTheme.skiko.kt:53)
	at androidx.compose.foundation.DarkThemeKt.isSystemInDarkTheme(DarkTheme.kt:41)

<img width="869" alt="Screenshot 2024-04-16 at 5 11 03 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/55983819/5a75d1a7-24cc-4233-bd08-77fbbfbee86c">

**Comment by terrakok** [comment]
Could you provide a little more information? A reproduser, your system and jvm info, gradle/kotlin/compose versions etc

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4627">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
