### ISSUE TITLE
Unable to run desktop (Vanilla project downloaded via KMP wizard): Exception in thread "main" java.lang.NoClassDefFoundError: androidx/collection/ScatterMapKt

### ISSUE THREAD

**Issue by slickorange** [JetBrains/compose-multiplatform#4666]
**Describe the bug**
I have created a new compose multiplatform project using the KMP wizard.
When trying to run the desktopMain/main.kt file I get an error:
Exception in thread "main" java.lang.NoClassDefFoundError: androidx/collection/ScatterMapKt

**Affected platforms**
- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 
- Compose Multiplatform version*: 
- OS version(s)* (required for Desktop and iOS issues):  MacOs Sonoma 14.2.1
- OS architecture (x86 or arm64): arm64 (M1)
- Device (model or simulator for iOS issues):  Macbook Pro
- JDK (for desktop issues): jbr 17.08

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Download project from KMP wizard with desktop selected as one of the options
2. Right click on composeApp/src/desktopMain/kotlin/main.kt -> Run
3. Error

**Expected behavior**
I expect the desktop app to run

**Additional context**
Why does running the desktop version give an AndroidX error?

Exception in thread "main" java.lang.NoClassDefFoundError: androidx/collection/ScatterMapKt
	at androidx.compose.runtime.collection.ScopeMap.<init>(ScopeMap.kt:26)
	at androidx.compose.runtime.CompositionImpl.<init>(Composition.kt:479)
	at androidx.compose.runtime.CompositionImpl.<init>(Composition.kt:434)
	at androidx.compose.runtime.CompositionKt.Composition(Composition.kt:335)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:217)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: androidx.collection.ScatterMapKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)

**Comment by slickorange** [comment]
I missed this part in the documentation (https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-multiplatform-create-first-app.html#next-step)

Run your application on desktop﻿

You can create a run configuration for running the desktop application as follows:

    Select the Run | Edit Configurations menu item.

    Click the plus button and choose Gradle from the dropdown list.

    In the Tasks and arguments field, paste this command:

    desktopRun -DmainClass=MainKt --quiet

Click OK.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4666">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by balanka** [comment]
Please do provide the full qualified main class name desktopRun -DmainClass=**YOUR.PACKAGE.NAME.Name**.MainKt --
