### ISSUE TITLE
Gradle error with 1.6.10-beta01 and `jvm { withJava() }`

### ISSUE THREAD

**Issue by rjaros** [JetBrains/compose-multiplatform#4669]
**Describe the bug**
When using compose gradle plugin in a KMP project with a JVM target containing `withJava()` option Gradle fails with the following error:

```
Cannot query the value of this provider because it has no value available.
The value of this provider is derived from:
  - task ':jvmCopyHierarchicalMultiplatformResources' property 'outputDirectory'
```

Full stacktrace:
```
* Exception is:
org.gradle.api.internal.provider.MissingValueException: Cannot query the value of this provider because it has no value available.
The value of this provider is derived from:
  - task ':examples:ssr-jooby:jvmCopyHierarchicalMultiplatformResources' property 'outputDirectory'
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:82)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
        at org.gradle.api.internal.provider.ProviderResolutionStrategy$2.resolve(ProviderResolutionStrategy.java:33)
        at org.gradle.api.internal.file.collections.ProviderBackedFileCollection.visitChildren(ProviderBackedFileCollection.java:64)
        at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:113)
        at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:361)
        at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:113)
        at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:77)
        at org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection.visitChildren(DefaultFileCollectionFactory.java:285)
        at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:113)
        at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:124)
        at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:165)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSourceTrees(DefaultSourceDirectorySet.java:251)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet_Decorated.getSourceTrees(Unknown Source)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSrcDirTrees(DefaultSourceDirectorySet.java:236)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet_Decorated.getSrcDirTrees(Unknown Source)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSrcDirs(DefaultSourceDirectorySet.java:130)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet_Decorated.getSrcDirs(Unknown Source)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet$SourceDirectories.getFiles(DefaultSourceDirectorySet.java:318)
        at org.gradle.api.internal.file.collections.FileCollectionAdapter.getIntrinsicFiles(FileCollectionAdapter.java:55)
        at org.gradle.api.internal.file.AbstractOpaqueFileCollection.iterator(AbstractOpaqueFileCollection.java:55)
        at org.gradle.util.internal.GUtil.addToCollection(GUtil.java:170)
        at org.gradle.util.internal.GUtil.addToCollection(GUtil.java:180)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet.setSrcDirs(DefaultSourceDirectorySet.java:300)
        at org.gradle.api.internal.file.DefaultSourceDirectorySet_Decorated.setSrcDirs(Unknown Source)
        at org.jetbrains.kotlin.gradle.targets.jvm.KotlinJvmTarget.setupJavaSourceSetSourcesAndResources(KotlinJvmTarget.kt:219)
        at org.jetbrains.kotlin.gradle.targets.jvm.KotlinJvmTarget.access$setupJavaSourceSetSourcesAndResources(KotlinJvmTarget.kt:47)
        at org.jetbrains.kotlin.gradle.targets.jvm.KotlinJvmTarget$withJava$4.execute(KotlinJvmTarget.kt:154)
        at org.jetbrains.kotlin.gradle.targets.jvm.KotlinJvmTarget$withJava$4.execute(KotlinJvmTarget.kt:150)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:122)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:161)
        at org.jetbrains.kotlin.gradle.targets.jvm.KotlinJvmTarget.withJava(KotlinJvmTarget.kt:150)
        at Build_gradle$1$1.execute(build.gradle.kts:20)
        at Build_gradle$1$1.execute(build.gradle.kts:19)
        at org.jetbrains.kotlin.gradle.dsl.KotlinTargetContainerWithPresetFunctions$jvm$5.invoke(KotlinTargetContainerWithPresetFunctions.kt:38)
        at org.jetbrains.kotlin.gradle.dsl.KotlinTargetContainerWithPresetFunctions$jvm$5.invoke(KotlinTargetContainerWithPresetFunctions.kt:38)
        at org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtensionKt.configureOrCreate(KotlinMultiplatformExtension.kt:343)
        at org.jetbrains.kotlin.gradle.dsl.KotlinTargetContainerWithPresetFunctions$DefaultImpls.jvm(KotlinTargetContainerWithPresetFunctions.kt:28)
        at org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension.jvm(KotlinMultiplatformExtension.kt:30)
        at org.jetbrains.kotlin.gradle.dsl.KotlinTargetContainerWithPresetFunctions$DefaultImpls.jvm$default(KotlinTargetContainerWithPresetFunctions.kt:24)
        at org.jetbrains.kotlin.gradle.dsl.KotlinTargetContainerWithPresetFunctions$DefaultImpls.jvm(KotlinTargetContainerWithPresetFunctions.kt:38)
        at org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension.jvm(KotlinMultiplatformExtension.kt:30)
        at Build_gradle$1.execute(build.gradle.kts:19)
        at Build_gradle$1.execute(build.gradle.kts:17)
        at org.gradle.internal.extensibility.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:177)
        at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:64)
        at org.gradle.internal.extensibility.DefaultConvention.configure(DefaultConvention.java:207)
        at org.gradle.kotlin.dsl.Accessors8rihyt52ywg47pk3ez2ijmcwzKt.kotlin(Unknown Source)
        at Build_gradle.<init>(build.gradle.kts:17)
        at Program.execute(Unknown Source)
```

**Affected platforms**
- JVM

**Versions**
- Kotlin version*: 2.0.0-RC1 
- Compose Multiplatform version*: 1.6.10-beta01

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Clone https://github.com/rjaros/compose-1.6.10-beta01-issue
2. Run any gradle task , e.g. `./gradlew clean`
3. See error

**Expected behavior**
No error, successful gradle task execution.

**Comment by terrakok** [comment]
Unfortunately, it is a problem in Kotlin Gradle Plugin: https://youtrack.jetbrains.com/issue/KT-67636
I didn't find a workaround yet. Try to ask there

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4669">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
