### ISSUE TITLE
Null pointer exception on using drawable resource on compose multiplatform - decodeByteArray(...) must not be nul

### ISSUE THREAD

**Issue by Jafar-Al-Rashid** [JetBrains/compose-multiplatform#4670]
**Describe the bug**
Null pointer exception on using drawable resource on compose multiplatform

                                                                                                    java.lang.NullPointerException: decodeByteArray(...) must not be null
                                                                                                    	at org.jetbrains.compose.resources.ImageResources_androidKt.toImageBitmap(ImageResources.android.kt:10)
                                                                                                    	at org.jetbrains.compose.resources.ImageResourcesKt$imageResource$imageBitmap$3$cached$1.invoke(ImageResources.kt:62)
                                                                                                    	at org.jetbrains.compose.resources.ImageResourcesKt$imageResource$imageBitmap$3$cached$1.invoke(ImageResources.kt:61)
                                                                                                    	at org.jetbrains.compose.resources.ImageResourcesKt$loadImage$2$deferred$1$1$1.invokeSuspend(ImageResources.kt:140)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
                                                                                                    	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                                                                                                    	at org.jetbrains.compose.resources.ResourceState_blockingKt.rememberResourceState(ResourceState.blocking.kt:30)
                                                                                                    	at org.jetbrains.compose.resources.ImageResourcesKt.imageResource(ImageResources.kt:59)

**Affected platforms**
Tested on Android only

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-dev1593
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64):
- Device (model or simulator for iOS issues): Pixle 6 pro API 33

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Try loading an image from kotlin multiplatform resources
        Image(
            bitmap = imageResource(Res.drawable.app_icon),
            contentDescription = "",
        )

**Expected behavior**
Resource drawables should load with no errors

**Comment by terrakok** [comment]
What is a extension of the image? Could you provide a sample?

**Comment by Jafar-Al-Rashid** [comment]
svg, attached
![app_icon](https://github.com/JetBrains/compose-multiplatform/assets/13495754/8f1cdf88-3d47-4ed1-8098-0b23712b122f)

**Comment by Jafar-Al-Rashid** [comment]
webp version of this works but not svg

**Comment by terrakok** [comment]
Because Android doesn't support SVG resources. I will implement a special check during a build for thet

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4670">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
