### ISSUE TITLE
Encountered error after upgrading from 1.6.10-beta01 to 1.6.10-rc01

### ISSUE THREAD

**Issue by Omico** [JetBrains/compose-multiplatform#4815]
```txt
org.gradle.internal.snapshot.impl.IsolationException: Could not isolate value org.jetbrains.compose.internal.service.ConfigurationProblemReporterService$Parameters_Decorated@6e5b35b7 of type ConfigurationProblemReporterService.Parameters
	at org.gradle.internal.snapshot.impl.DefaultIsolatableFactory.isolate(DefaultIsolatableFactory.java:51)
	at org.gradle.api.services.internal.RegisteredBuildServiceProvider.instantiate(RegisteredBuildServiceProvider.java:128)
	at org.gradle.api.services.internal.RegisteredBuildServiceProvider.getInstance(RegisteredBuildServiceProvider.java:119)
	at org.gradle.api.services.internal.RegisteredBuildServiceProvider.calculateOwnValue(RegisteredBuildServiceProvider.java:112)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:80)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
	at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer.handle(DefaultBuildEventsListenerRegistry.java:261)
	at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer.handle(DefaultBuildEventsListenerRegistry.java:238)
	at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$AbstractListener.run(DefaultBuildEventsListenerRegistry.java:180)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: java.lang.IllegalStateException: BuildScopeServices has been closed.
	at org.gradle.internal.service.DefaultServiceRegistry.serviceRequested(DefaultServiceRegistry.java:291)
	at org.gradle.internal.service.DefaultServiceRegistry.getService(DefaultServiceRegistry.java:331)
	at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:325)
	at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:310)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory.getObjectFactory(ManagedObjectFactory.java:140)
	at org.gradle.internal.instantiation.generator.ManagedObjectFactory.newInstance(ManagedObjectFactory.java:95)
	at org.jetbrains.compose.internal.service.ConfigurationProblemReporterService$Parameters_Decorated.getUnsupportedPluginWarningProviders(Unknown Source)
	at org.jetbrains.compose.internal.service.ConfigurationProblemReporterService$Parameters_Decorated.unpackState(Unknown Source)
	at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processManaged(AbstractValueProcessor.java:127)
	at org.gradle.internal.snapshot.impl.AbstractValueProcessor.processValue(AbstractValueProcessor.java:98)
	at org.gradle.internal.snapshot.impl.DefaultIsolatableFactory.isolate(DefaultIsolatableFactory.java:49)
	... 10 more

```

**Comment by eymar** [comment]
Do you have a reproducer for this issue?

**Comment by Omico** [comment]
@eymar  It cannot be reproduced stably, but it will break my CI from time to time after upgrading. https://scans.gradle.com/s/43zyx7dja22yc

**Comment by igordmn** [comment]
Probably it is https://github.com/JetBrains/compose-multiplatform/issues/4773. The solution is in the comments

**Comment by Omico** [comment]
> Probably it is #4773. The solution is in the comments

Not sure what's going on. 
https://scans.gradle.com/s/mmlzuzbvgolgo
https://scans.gradle.com/s/gqynlmhckpdbg
It took a long time to debug. Something wrong with 1.6.10-beta03.
https://github.com/JetBrains/compose-multiplatform/compare/v1.6.10-beta02...v1.6.10-beta03

**Comment by amir1376** [comment]
for me it seems when I add compose plugin using `buildSrc` this problem shows up
it's ok with jb-compose 1.6.2 with kotlin 1.9.23
but have error with jb-compose 1.6.10 with kotlin 2.0.0

**Comment by svenjacobs** [comment]
I'm having the same problem since updating to Kotlin 2.0.0.
I'm also using the plugins within convention plugins.

[Here's](https://github.com/svenjacobs/reveal/actions/runs/9304161445/job/25608104740#step:5:86) a failed build.

**Comment by Omico** [comment]
https://scans.gradle.com/s/hkyvpfi4jbpgs
Here is a live demo https://github.com/Omico/picsum/tree/cmp

**Comment by Omico** [comment]
> Probably it is #4773. The solution is in the comments

This doesn't work at all. Getting tired, let it fail all the time https://github.com/OmicoDev/wwm/actions/runs/9409655695.

**Comment by svenjacobs** [comment]
It seems the fix was too late for `1.6.11`? Which stable release will contain this fix?

**Comment by igordmn** [comment]
1.7.0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4815">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
