### ISSUE TITLE
Cannot boot for Desktop after upgrade to 1.6.10*

### ISSUE THREAD

**Issue by touchnotes** [JetBrains/compose-multiplatform#4816]
After upgrade from 1.6.0 to 1.6.10(I try 1.6.2, and it works well).
The application run with below error:
```
5月 16, 2024 4:10:38 下午 com.sun.javafx.application.PlatformImpl startup
警告: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @534bf26d'
Exception in thread "main" java.lang.IllegalStateException: Method setCurrentState must be called on the main thread
	at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.jvm.kt:302)
	at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.jvm.kt:106)
	at androidx.compose.ui.scene.ComposeContainer.updateLifecycleState(ComposeContainer.desktop.kt:436)
	at androidx.compose.ui.scene.ComposeContainer.onChangeWindowFocus(ComposeContainer.desktop.kt:216)
	at androidx.compose.ui.scene.ComposeContainer.setWindow(ComposeContainer.desktop.kt:297)
	at androidx.compose.ui.scene.ComposeContainer.<init>(ComposeContainer.desktop.kt:164)
	at androidx.compose.ui.scene.ComposeContainer.<init>(ComposeContainer.desktop.kt:82)
	at androidx.compose.ui.awt.ComposeWindowPanel.<init>(ComposeWindowPanel.desktop.kt:56)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:65)
	at androidx.compose.ui.awt.ComposeWindow.<init>(ComposeWindow.desktop.kt:63)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:182)
	at androidx.compose.ui.window.Window_desktopKt$Window$3.invoke(Window.desktop.kt:176)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:409)
	at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:406)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:70)
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:69)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1295)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:984)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1005)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1099)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:221)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

I tried to remove the code in main.kt and only run the following small piece of code, but the same issue still exists. 

   ```kt
fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        title = "Demo",
    ) {
        MaterialTheme {
            Text("123")
        }
    }
}

   ```

- Desktop (Windows, macOS)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10-rc02
  - Navigation Multiplatform version (for related issues):1.6.10-rc02
  - ...
- Kotlin version: 
- OS version(s) (required for Desktop and iOS issues): macOS 14.4.1
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues):  jbr 17.0.7

**Comment by eymar** [comment]
Using the same JDK (jbr 17.0.7) version on macos and the provided snippet doesn't reproduce the issue in my case.

Do you think there could be other required things to reproduce?

**Comment by touchnotes** [comment]
Create a new demo is work well,
But for my old project, it reproduce the issue.
I guess it is related to the integration of some libraries that I have done.

**Comment by eymar** [comment]
Got it! If you find any details to add which would help to reproduce the issue, feel free to reopen the issue :)

**Comment by touchnotes** [comment]
After add ``` implementation("io.github.kevinnzou:compose-webview-multiplatform:1.2.0")```, application reproduce the issue. 
compose-webview-multiplatform:1.9.7 works well, But 1.9.7 need to download kcef-bundle before show webview.

**Comment by antonindrawan** [comment]
@eymar I encountered this crash with the same identical stacktrace as above in one JVM project (let's call it app1). Unfortunately, I can't take this project out of the company project (yet).

In my another KMP project (created via the kmp wizard), it works (let's call it app2)

I was debugging both apps in this method LifecycleRegistry.jvm.kt line 302

```
    private fun enforceMainThreadIfNeeded(methodName: String) {
        if (enforceMainThread) {
            check(isMainThread()) { --> this one fails on app1, but it doesn't on app2
                ("Method $methodName must be called on the main thread")
            }
        }
    }
```

Debugging observation:
1. In app1 (the one that  **does** crash), it calls `isMainThread` from `LifecycleRegistry.desktop.kt` (part of `androidx.lifecycle/lifecycle-runtime-desktop/2.8.0/efd89430fd03f9671c124018cc89a12f10e0705d`). There was a change in the implementation a few months ago: https://github.com/JetBrains/compose-multiplatform-core/commit/238132708132891c89913af56f32dca7d6106deb
This project uses a dependency to `implementation(compose.desktop.currentOs)`.


2. In app2 (the one that **doesn't** crash), it calls `isMainThread` from `LifecycleRegistry.web.kt` (part of `org.jetbrains.androidx.lifecycle/lifecycle-runtime/2.8.0/6dc28ff7a9255a6b3f680ee07f956acbddd32c5d`), which always returns true.
This project doesn't have a dependency to `implementation(compose.desktop.currentOs)`, but `implementation(compose.runtime)`


I am puzzled on several things:
1. why does app1 uses `LifecycleRegistry.desktop.kt` from `lifecycle-runtime-desktop`, and app2 uses `LifecycleRegistry.web.kt` from `lifecycle-runtime`?
2. I couldn't find a way how to reproduce this on a sample KMP project by explicitly putting a dependency to `compose.desktop.currentOs`. I would like to force app2 to use `lifecycle-runtime-desktop` to reproduce the issue.

Any help to reproduce and find the root cause will be appreciated.

**Comment by MatkovIvan** [comment]
@antonindrawan A few things here:
1. That module uses redirects to Google's published artifact not only for Android but for desktop too. So sources should be in sync between fork and AOSP in this place, but anyway.
2. Main tread check is based on `Dispatchers.Main` that might be different on JVM based on your dependencies. Compose uses Swing for Desktop integration so `kotlinx-coroutines-swing` should be used. See [Dispatchers.Main documentation](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-main.html) for details.

Since JavaFX is mentioned in the original description I guess it's because of mixing that

**Comment by antonindrawan** [comment]
@MatkovIvan : I overlooked that the bug reporter had JavaFx, but in my case, I don't have JavaFX at all. The stacktrace is identical though, but there is no "Unsupported JavaFX conf..." at all.

I've tried to add `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:<version>")`, but it doesn't help.


Here is an additional debugging information on this function `fun isMainDispatcherThreadd(): Boolean` (https://github.com/JetBrains/compose-multiplatform-core/blob/release/1.6.11/lifecycle/lifecycle-runtime/src/desktopMain/kotlin/androidx/lifecycle/MainDispatcherChecker.desktop.kt#L37-L58)
* I took a screenshot of my debugging session where the function will return false
![isMainDispatcherThread-returning-false](https://github.com/JetBrains/compose-multiplatform/assets/8410993/4a44a547-7d9a-49e9-958c-c7fb5628241c)

Could you help figure out if there is a problem there with the main thread?

**Comment by MatkovIvan** [comment]
@kropp maybe do you have any ideas here?

**Comment by antonindrawan** [comment]
Additional information: Our setup (where we reproduce the crash) is based on old kotlin `1.8.22` and compose compiler `1.4.8`. This might be an incompatible with compose `1.6.11`.

**Comment by kropp** [comment]
@antonindrawan I know it may be tricky, but could you first try to upgrade to the latest versions of all related dependencies (Compose, Kotlin, Coroutines) and check the app once again?

**Comment by antonindrawan** [comment]
@kropp : We will try that which will take some time, because of other modules relying on the older kotlin and compose compiler versions.

Here is a further piece of information from debugging:
It seems that the thread from `Dispatchers.Main.immediate` is different than the thread where the compose application is run, but they are running on the same thread group. 

I tried to explore https://github.com/JetBrains/compose-multiplatform-core/blob/release/1.6.11/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/window/Application.desktop.kt#L194, but I couldn't fully understand it properly.


See the screenshot below when `mainDispatcherThread` is set to `MainThread @corouting#6,6,main` and the compose application (just showing a Window) runs on `AWT-EventQueue-0 @coroutine#4,6,main`.
![mainDispatcherThread-compose](https://github.com/JetBrains/compose-multiplatform/assets/8410993/def9ff67-b8d5-4b6f-b702-d5d16189bcae)

Does this give some pointer?

Our Main.kt looks like the following:
```
fun main() = application {
    ...
    MainView() 
}

@Composeable
private fun MainView() = Window(...) {
}
```
Thank you for helping investigate this.

**Comment by MohamedRejeb** [comment]
Adding `kotlinx-coroutines-swing` fixes the issue for me, coroutines version: `1.8.1`

**Comment by antonindrawan** [comment]
@kropp I use kotlinx-coroutines version `1.7.3`

**Comment by antonindrawan** [comment]
@kropp : My colleague found the root cause. It appears that internally we implement our own JVM MainDispatcher, which was somehow broken after updating from 1.6.2 to 1.6.11.

**Comment by kropp** [comment]
@antonindrawan thanks for the update

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4816">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
