### ISSUE TITLE
[Compose Resources] commonMainResourceAccessors is not generated in multi-module architecture using Kotlin 2.0.0

### ISSUE THREAD

**Issue by sereden** [JetBrains/compose-multiplatform#4873]
The official statement says: `Starting with 1.6.10, you can place resources in any module or source set, as long as you are using Kotlin 2.0.0 or newer, and Gradle 7.6 or newer.`

However, when the resources are placed in another module then composeApp (I don't know whether it name or application plugin dependent) they are not generated

**Affected platforms**
- All
**Versions**
- Libraries:
  - Compose Plugin version: 1.6.10
  - Kotlin version: 2.0.0
  - Gradle version: 8.7 

**To Reproduce**
1. Download zip archive
2. Click run Android app
3. Navigate to App.kt and try to uncomment 36 line

**Expected behavior**
The resources could be imported from another module

**Screenshots**
<img width="1327" alt="Screenshot 2024-05-25 at 22 01 59" src="https://github.com/JetBrains/compose-multiplatform/assets/1812174/c186f502-e3a2-41ed-81d6-09cf5a83b355">

**Demo**
[KotlinProject 2.zip](https://github.com/JetBrains/compose-multiplatform/files/15444667/KotlinProject.2.zip)

**Comment by jcaiqueoliveira** [comment]
I'm getting a similar problem but with fonts

Config:
```
compose-plugin = "1.6.10"
kotlin = "2.0.0"

jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
```

// res config:

```kotlin
compose.resources {
    publicResClass = true
    packageOfResClass = "sample.resources"
    generateResClass = always
}
```

Code to expose font:
```kotlin
@Composable
public fun workSans(): FontFamily {
    return FontFamily(Font(Res.font.worksans_default))
}
```

```
Caused by: java.lang.IllegalStateException: 
Unable to load font Font(assetManager, path=composeResources/sample.resources/font/worksans-default.ttf, weight=FontWeight(weight=400), style=Normal)
                                                                                                    	at androidx.compose.ui.text.font.FontListFontFamilyTypefaceAdapterKt.firstImmediatelyAvailable(FontListFontFamilyTypefaceAdapter.kt:195)
                                                                                                    	at androidx.compose.ui.text.font.FontListFontFamilyTypefaceAdapterKt.access$firstImmediatelyAvailable(FontListFontFamilyTypefaceAdapter.kt:1)
                                                                                                    	at androidx.compose.ui.text.font.FontListFontFamilyTypefaceAdapter.resolve(FontListFontFamilyTypefaceAdapter.kt:133)
                                                                                                    	at androidx.compose.ui.text.font.FontFamilyResolverImpl$resolve$result$1.invoke(FontFamilyResolver.kt:93)
                                                                                                    	at androidx.compose.ui.text.font.FontFamilyResolverImpl$resolve$result$1.invoke(FontFamilyResolver.kt:92)
                                                                                                    	at androidx.compose.ui.text.font.TypefaceRequestCache.runCached(FontFamilyResolver.kt:192)
                                                                                                    	... 131 more
```

[Testproject.zip](https://github.com/JetBrains/compose-multiplatform/files/15445339/Testproject.zip)

**Comment by nowiwr01w** [comment]
Guys, do you know is it possible to share resources between `composeApp` and `server`?
I can't do it because it says my `server` module should be marked as multiplatform module (because `resources` module, that I apply to `server` module` should be also marked as multiplatform) - https://kotlinlang.slack.com/archives/C3PQML5NU/p1716676813612929

**Comment by Nek-12** [comment]
> Guys, do you know is it possible to share resources between `composeApp` and `server`? I can't do it because it says my `server` module should be marked as multiplatform module (because `resources` module, that I apply to `server` module` should be also marked as multiplatform) - https://kotlinlang.slack.com/archives/C3PQML5NU/p1716676813612929

How is this related to the issue?

**Comment by YoussefHachicha** [comment]
same issue here using 
kotlin = "2.0.0"
compose = "1.6.20-dev1646"

whenever I try to create a composeResources directory I only get suggested this which is the old impl 
<img width="467" alt="Screenshot 2024-05-26 at 11 08 03 AM" src="https://github.com/JetBrains/compose-multiplatform/assets/126149415/80645ea2-6dfb-4a66-a141-3267bfd8b1b5">
is one

**Comment by terrakok** [comment]
@sereden you forgot about the src dir: move `resources/commonMain` -> `resources/src/commonMain`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4873">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
