### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "x" because "rc" is null

### ISSUE THREAD

**Issue by Omico** [JetBrains/compose-multiplatform#5056]
**Affected platforms**

- Desktop (Windows)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.7.0-dev1703
- Kotlin version: 2.0.0
- JDK (for desktop issues): 17

**To Reproduce**
Run this & input any chars.
 ```kotlin
@OptIn(ExperimentalMaterial3Api::class)
fun main() {
    singleWindowApplication {
        Scaffold(
            topBar = {
                TopAppBar(
                    title = {
                        var title by remember { mutableStateOf("Default") }
                        BasicTextField(
                            value = title,
                            onValueChange = { title = it },
                            textStyle = LocalTextStyle.current,
                            singleLine = true,
                            modifier = Modifier.fillMaxWidth(),
                        )
                    },
                )
            },
            content = {}
        )
    }
}
```

This will throw:
```txt
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "x" because "rc" is null
	at java.desktop/sun.awt.windows.WInputMethod$1.run(WInputMethod.java:617)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by igordmn** [comment]
Thanks!

Reproduced in `1.7.0-dev1703` with Chines input

Not reproduced in `1.6.10` or with English input.

It seems only the popup position is affected. Crash only appears in the console, it doesn't crash the app.

**Comment by igordmn** [comment]
The same crash was fixed before in https://github.com/JetBrains/compose-multiplatform-core/pull/339. It might doesn't work after big TextField rewriting in 1.7.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5056">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
