### ISSUE TITLE
1.7.0-alpha01 is incompatible with KGP 2.0.0 when using android projects

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains/compose-multiplatform#5061]
**Describe the bug**
1.7.0-alpha01 fails during gradle sync when used with an android application target.

```
Caused by: org.gradle.api.InvalidUserDataException: Cannot change hierarchy of dependency configuration ':androidTestImplementation' after it has been included in dependency resolution.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.preventIllegalMutation(DefaultConfiguration.java:1475)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:1414)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.extendsFrom(DefaultConfiguration.java:404)
	at org.jetbrains.kotlin.gradle.utils.GradleConfigurationUtilsKt.addExtendsFromRelation(gradleConfigurationUtils.kt:25)
	at org.jetbrains.kotlin.gradle.utils.GradleConfigurationUtilsKt.addExtendsFromRelation$default(gradleConfigurationUtils.kt:18)
	at org.jetbrains.kotlin.gradle.plugin.AndroidProjectHandler.addKotlinDependenciesToAndroidSourceSets$addDependenciesToAndroidSourceSet(AndroidProjectHandler.kt:131)
	at org.jetbrains.kotlin.gradle.plugin.AndroidProjectHandler.addKotlinDependenciesToAndroidSourceSets(AndroidProjectHandler.kt:141)
	at org.jetbrains.kotlin.gradle.plugin.AndroidProjectHandler.access$addKotlinDependenciesToAndroidSourceSets(AndroidProjectHandler.kt:52)
	at org.jetbrains.kotlin.gradle.plugin.AndroidProjectHandler$configureTarget$2.invoke(AndroidProjectHandler.kt:98)
	at org.jetbrains.kotlin.gradle.plugin.AndroidProjectHandler$configureTarget$2.invoke(AndroidProjectHandler.kt:88)
	at org.jetbrains.kotlin.gradle.utils.WhenEvaluatedKt$whenEvaluated$2.execute(whenEvaluated.kt:19)
	at org.jetbrains.kotlin.gradle.utils.WhenEvaluatedKt$whenEvaluated$2.execute(whenEvaluated.kt:19)
	at  ...
```

**Affected platforms**

Gradle plugin

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.7.0-alpha01
- Kotlin version: 2.0.0
- Gradle 8.8
- KGP 2.0.0
- AGP 8.5.0

**To Reproduce**
1. Checkout this repo: https://github.com/zacsweers/fieldspottr
2. Change the compose multiplatform version to 1.7.0-alpha01
3. Try to sync in the IDE

**Expected behavior**
I expect it not to fail during sync

**Screenshots**

**Additional context**

**Comment by Him188** [comment]
FYI: I was able to switch to 1.7.0-alpha01 with Kotlin 2.0.0 and Android. https://github.com/open-ani/ani/pull/502 might help you?

**Comment by ZacSweers** [comment]
Doesn't help the repro case I've provided above

**Comment by igordmn** [comment]
[A reduced reproducer](https://github.com/user-attachments/files/16123801/AboutLibrariesBug.zip)

```
./gradlew
```

One of these changes fixes the issue:
1. Downgrade Compose to 1.6.11
2. Remove `alias(libs.plugins.aboutLicenses)`
3. Remove `org.gradle.configuration-cache=true`

**Comment by igordmn** [comment]
The issue is either in Compose Gradle plugin or in the `aboutLicenses` plugin - it needs further investigation.

**Comment by mikepenz** [comment]
I have looked briefly into this problem. And it appears to be caused by the following call accessing the `resolvedConfigurations` during task execution:

```
configuration.resolvedConfiguration
```

Moving the code to the `action` method of the task will resolve it, however, this won't allow the access to `Task.porject` braking configuration cache:

```
invocation of 'Task.project' at execution time is unsupported.
```

This is shown in this following reproducible example: 
[plugin-demo.zip](https://github.com/user-attachments/files/16125809/plugin-demo.zip)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5061">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by kasem-sm** [comment]
facing the same issue + using about aboutLicenses lib as well!
