### ISSUE TITLE
Unable to run tests using Multiplatform Resources

### ISSUE THREAD

**Issue by Quantamm** [JetBrains/compose-multiplatform#5092]
First of all, thank you for adding support for Multiplatform Resources; it's huge for our ability to leverage KMM.

We would like the ability to run unit tests that use these resources. Currently, when I try to run an androidTest test that uses them, I get:

```
java.lang.NullPointerException: Cannot invoke "android.content.res.Resources.getConfiguration()" because the return value of "android.content.res.Resources.getSystem()" is null
	at org.jetbrains.compose.resources.ResourceEnvironment_androidKt.getSystemEnvironment(ResourceEnvironment.android.kt:9)
	at org.jetbrains.compose.resources.ResourceEnvironmentKt$getResourceEnvironment$1.invoke(ResourceEnvironment.kt:83)
	at org.jetbrains.compose.resources.ResourceEnvironmentKt$getResourceEnvironment$1.invoke(ResourceEnvironment.kt:83)
	at org.jetbrains.compose.resources.ResourceEnvironmentKt.getSystemResourceEnvironment(ResourceEnvironment.kt:90)
	at org.jetbrains.compose.resources.StringResourcesKt.getString(StringResources.kt:99)
```

**Comment by terrakok** [comment]
https://youtrack.jetbrains.com/issue/CMP-5092

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5092">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
