### ISSUE TITLE
Scrollbar doesn't work for DropdownMenu

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-multiplatform#587]
Tested it in diffirent ways, find out what it work just for `LazyColumn/Row` or content wrapped by `Box`. All attempts add `scrollbar` to `Column/ColumnScope` result in an exceptions. `DropdownMenu` can't be wrapped into `BoxScope` as in examples cos it change it size which provide an exception. 

**So here is the question:** Is it even possible to add scrollbar to DropdownMenu and I just miss info or this is missing feature?
_ofcourse I can make crutch with `LazyColumn` and `clickable` elements but there is no `onDismissRequest`_

**Comment by igordmn** [comment]
Unfortunately it isn't possible right now.

As a temporary measure, you can copy code from here:
https://github.com/androidx/androidx/blob/8cb282ccdbb00687dbf253a4419ded0dfc786fb5/compose/material/material/src/desktopMain/kotlin/androidx/compose/material/DesktopMenu.desktop.kt
https://github.com/androidx/androidx/blob/8cb282ccdbb00687dbf253a4419ded0dfc786fb5/compose/material/material/src/commonMain/kotlin/androidx/compose/material/Menu.kt

And add scrollbar into Card here:
https://github.com/androidx/androidx/blob/8cb282ccdbb00687dbf253a4419ded0dfc786fb5/compose/material/material/src/commonMain/kotlin/androidx/compose/material/Menu.kt#L116

Thanks for raising the issue. I think it is important use case for scrollbars. We will think about how we can integrate it into DropdownMenu easily.

**Comment by Thomas-Vos** [comment]
@igordmn I tried adding `VerticalScrollbar` to a `DropdownMenu`. However, it seems that `VerticalScrollbar` always fills the max height of the screen. So the `DropdownMenu` appears larger than needed. Any way to fix that? I tried adding `height(IntrinsicSize.Max)` to the `VerticalScrollbar` but that causes the following error:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Can't represent a size of 2147483647 in Constraints
	at androidx.compose.ui.unit.Constraints$Companion.bitsNeedForSize(Constraints.kt:403)
	at androidx.compose.ui.unit.Constraints$Companion.createConstraints-Zbe2FdA$ui_unit(Constraints.kt:363)
	at androidx.compose.ui.unit.Constraints$Companion.fixedHeight-OenEA2s(Constraints.kt:345)
	at androidx.compose.foundation.layout.MaxIntrinsicHeightModifier.calculateContentConstraints-l58MMJ0(Intrinsic.kt:163)
	at androidx.compose.foundation.layout.IntrinsicSizeModifier$DefaultImpls.measure-3p2s80s(Intrinsic.kt:252)
	at androidx.compose.foundation.layout.MaxIntrinsicHeightModifier.measure-3p2s80s(Intrinsic.kt:157)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1388)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1387)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui(LayoutNode.kt:1387)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:75)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1331)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:143)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:44)
	at androidx.compose.foundation.layout.IntrinsicSizeModifier$DefaultImpls.measure-3p2s80s(Intrinsic.kt:253)
	at androidx.compose.foundation.layout.MaxIntrinsicWidthModifier.measure-3p2s80s(Intrinsic.kt:142)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s(Padding.kt:364)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.foundation.layout.SizeModifier.measure-3p2s80s(Size.kt:781)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.foundation.layout.SizeModifier.measure-3p2s80s(Size.kt:781)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1388)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1387)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui(LayoutNode.kt:1387)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:75)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1331)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:121)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:44)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:405)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.graphics.BlockGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:342)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.graphics.BlockGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:342)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1388)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1387)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui(LayoutNode.kt:1387)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:75)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1331)
	at androidx.compose.ui.window.DesktopPopup_desktopKt$PopupLayout$6$composition$1$1$1.invoke(DesktopPopup.desktop.kt:191)
	at androidx.compose.ui.window.DesktopPopup_desktopKt$PopupLayout$6$composition$1$1$1.invoke(DesktopPopup.desktop.kt:189)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:939)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:924)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui(OwnerSnapshotObserver.kt:52)
	at androidx.compose.ui.node.LayoutNode.layoutChildren$ui(LayoutNode.kt:924)
	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui(LayoutNode.kt:909)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:79)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-aW-9-wM(Placeable.kt:398)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeOuterWrapper-f8xVGno(OuterMeasurablePlaceable.kt:160)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.access$placeOuterWrapper-f8xVGno(OuterMeasurablePlaceable.kt:28)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:146)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:145)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui(OwnerSnapshotObserver.kt:59)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:145)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelativeWithLayer(Placeable.kt:387)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelativeWithLayer$default(Placeable.kt:246)
	at androidx.compose.ui.layout.RootMeasurePolicy$measure$2.invoke(RootMeasurePolicy.kt:43)
	at androidx.compose.ui.layout.RootMeasurePolicy$measure$2.invoke(RootMeasurePolicy.kt:39)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:68)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:939)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:924)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui(OwnerSnapshotObserver.kt:52)
	at androidx.compose.ui.node.LayoutNode.layoutChildren$ui(LayoutNode.kt:924)
	at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui(LayoutNode.kt:909)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:79)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:372)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeOuterWrapper-f8xVGno(OuterMeasurablePlaceable.kt:158)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.access$placeOuterWrapper-f8xVGno(OuterMeasurablePlaceable.kt:28)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:146)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:145)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2064)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:115)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui(OwnerSnapshotObserver.kt:59)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:145)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative(Placeable.kt:361)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Placeable.kt:179)
	at androidx.compose.ui.node.LayoutNode.place$ui(LayoutNode.kt:787)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:278)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:38)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:208)
	at androidx.compose.ui.platform.SkiaBasedOwner.measureAndLayout(SkiaBasedOwner.skiko.kt:257)
	at androidx.compose.ui.node.Owner$DefaultImpls.measureAndLayout$default(Owner.kt:196)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:383)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:236)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:235)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:88)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:68)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:235)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:455)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.update(MetalRedrawer.kt:66)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.access$update(MetalRedrawer.kt:13)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invokeSuspend(MetalRedrawer.kt:38)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@705670bf, SwingDispatcher@1935cd73]
```

**Comment by igordmn** [comment]
DropdownMenu currently is very opinionated, and already uses scroll inside. That is the reason why we can't put scrollbar into DropdownMenu (scrollbar should be outside of scrollable content). The only way to add scrollbar - is to write a custom DropdownMenu as described [here](https://github.com/JetBrains/compose-jb/issues/587#issuecomment-818752463). It is inconvenient, so we will look at it at some point in the future, providing out-of-the box support for scrollbar.

**Comment by Thomas-Vos** [comment]
I know, that is what I did. I copied the source code you linked, into my project and made my own version that has a scrollbar. However, it seems that the `VerticalScrollbar` always tries to fill max height internally, and I cannot get it fixed with `height(IntrinsicSize.Max)` as that just crashes.

**Comment by Thomas-Vos** [comment]
@igordmn To clarify the issue, I did copy the source code. I replaced [this Column](https://github.com/androidx/androidx/blob/8cb282ccdbb00687dbf253a4419ded0dfc786fb5/compose/material/material/src/commonMain/kotlin/androidx/compose/material/Menu.kt#L125-L131) with the code below:

```kt
Box(
    modifier = modifier
        .width(IntrinsicSize.Max)
) {
    val scrollState = rememberScrollState()
    Column(
        modifier = Modifier
            .padding(vertical = DropdownMenuVerticalPadding)
            .verticalScroll(scrollState),
        content = content
    )
    VerticalScrollbar(
        modifier = Modifier
            .align(Alignment.CenterEnd),
        scrollState = scrollState
    )
}
```

Here is a screenshot of how it looks like:

<img width="1312" alt="Screenshot 2022-05-27 at 01 07 28" src="https://user-images.githubusercontent.com/11077217/170593809-06090885-2706-49d9-8d10-5f8fc2c20b70.png">


As you can see, the right dropdown menu is too large due to scrollbar filling max height. I tried playing around with intrinsic heights, but that either crashes with the error mentioned earlier, or just doesn't do anything. But I may be misunderstanding how it works.

I managed to work around this by using `onSizeChanged` and setting the resulting height to the scrollbar:

```kt
Box(
    modifier = modifier
        .width(IntrinsicSize.Max)
) {
    val scrollState = rememberScrollState()
    var columnSize by remember { mutableStateOf<IntSize?>(null) }
    Column(
        modifier = Modifier
            .padding(vertical = DropdownMenuVerticalPadding)
            .verticalScroll(scrollState)
            .onSizeChanged { size ->
                columnSize = size
            },
        content = content
    )
    columnSize?.let { size ->
        VerticalScrollbar(
            modifier = Modifier
                .align(Alignment.CenterEnd)
                .height(with(LocalDensity.current) { size.height.toDp() }),
            scrollState = scrollState
        )
    }
}
```

I know it is not the best but at least it works. This is how it looks like with this workaround (expected):

<img width="1312" alt="Screenshot 2022-05-27 at 01 08 37" src="https://user-images.githubusercontent.com/11077217/170593827-664c2642-d1b5-4eeb-91d5-c1406c6c7ce5.png">

If you or anyone else has any suggestions on how to improve this, please let me know.

**Comment by dev-jesser** [comment]
@Thomas-Vos & @igordmn Thanks for posting what you did to make the Scrollbar show up, I was totally having a problem on this. I had to change one more thing, which was putting back in the current [DesktopDropdownMenuPositionProvider](https://github.com/JetBrains/compose-multiplatform-core/blob/eb888df246ad3908183a21a5c1a938f46be246b8/compose/material/material/src/desktopMain/kotlin/androidx/compose/material/DesktopMenu.desktop.kt#L377) as my Dropdown's were overflowing the top of my app.

**Comment by wwalkingg** [comment]
@igordmn I think there are bugs in VerticalScrollBar. I just Use Box instead of VerticalScrollBar,It Works
1. use Box
```kotlin
val scrollState = rememberScrollState()
    Box(
        modifier = Modifier
            .height(IntrinsicSize.Min)
            .shadow(4.dp, RoundedCornerShape(10.dp))
            .clip(RoundedCornerShape(10.dp))
            .background(Color.Red),
        contentAlignment = Alignment.CenterEnd
    ) {
        Column(
            modifier = modifier
                .padding(vertical = DropdownMenuVerticalPadding)
                .width(IntrinsicSize.Max)
                .verticalScroll(scrollState),
            content = content
        )
        Box(
            modifier = Modifier
                .fillMaxHeight()
                .width(4.dp)
                .background(Color.Black)
        )
    }
```

![image](https://github.com/JetBrains/compose-multiplatform/assets/42681996/ba6bdb48-4a33-4e04-b35e-2bea0e435100)


2. use VerticalScrollbar
```kotlin
val scrollState = rememberScrollState()
    Box(
        modifier = Modifier
            .height(IntrinsicSize.Min)
            .shadow(4.dp, RoundedCornerShape(10.dp))
            .clip(RoundedCornerShape(10.dp))
            .background(Color.Red),
        contentAlignment = Alignment.CenterEnd
    ) {
        Column(
            modifier = modifier
                .padding(vertical = DropdownMenuVerticalPadding)
                .width(IntrinsicSize.Max)
                .verticalScroll(scrollState),
            content = content
        )
        VerticalScrollbar(
            modifier = Modifier
                .fillMaxHeight()
                .pointerHoverIcon(PointerIcon.Hand),
            adapter = rememberScrollbarAdapter(scrollState)
        )
    }
  
```
 
 error comes

![image](https://github.com/JetBrains/compose-multiplatform/assets/42681996/561453e2-b21b-4681-8e97-8bef3917cc7d)

**Comment by m-sasha** [comment]
This won't help with a `DropdownMenu`, but see https://github.com/JetBrains/compose-multiplatform/issues/1916

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6012">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
