### ISSUE TITLE
Compose Web Compiler Exception: `e: java.lang.IllegalStateException: Unreachable execution: there could not be back-links`

### ISSUE THREAD

**Issue by MrPowerGamerBR** [JetBrains/compose-multiplatform#656]
So, this is a very brittle bug that I just can't figure out how to reproduce. I will try to explain what caused the issue for me, and what fixed the issue.

Let's suppose we have this
```kotlin
@Composable
fun ServerIcon(iconUrl: String, routingManager: RoutingManager, path: String, selected: Boolean) {
    Img(src = iconUrl, attrs = {
        val classes = mutableListOf("server-icon")
        if (selected)
            classes += "selected"
        classes(*classes.toTypedArray())

        onClick {
            routingManager.navigate(path)
        }
    })
}

@Composable
inline fun Aside(
    crossinline attrs: (AttrsBuilder<Tag.Div>.() -> Unit) = {},
    crossinline style: (StyleBuilder.() -> Unit) = {},
    content: @Composable ElementScope<HTMLDivElement>.() -> Unit
) {
    TagElement(
        tagName = "aside",
        applyAttrs = attrs,
        applyStyle = style,
        content = content
    )
}
```

And then we have a nested class hierachy, consisting of:
`View` -> `SidebarsView -> render()`

And, in the `render()` method, we have...
```kotlin
            Aside(attrs = attrClasses("server-selector")) {
                ServerIcon(
                    "https://cdn.discordapp.com/avatars/123170274651668480/8bd2b747f135c65fd2da873c34ba485c.png?size=2048",
                    routingManager,
                    "/users",
                    false
                )
                ServerIcon(
                    "https://cdn.discordapp.com/icons/297732013006389252/a_fee7591870d26c60af64179c4ab520ed.gif?size=2048",
                    routingManager,
                    "/servers/1",
                    false
                )
                ServerIcon(
                    "https://cdn.discordapp.com/emojis/523233744656662548.png?v=1",
                    routingManager,
                    "/servers/2",
                    false
                )
                ServerIcon(
                    "https://cdn.discordapp.com/emojis/523233744656662548.png?v=1",
                    routingManager,
                    "/servers/2",
                    false
                )
            }
```

If we have a `ServerIcon` that has the same parameters as another `ServerIcon` the compiler throws an exception

```
e: java.lang.IllegalStateException: Unreachable execution: there could not be back-links (sig: public net.perfectdreams.loridash.frontend.views/SidebarsView.leftSidebarContents$composable|7445798109038866580[0])
        at org.jetbrains.kotlin.backend.common.serialization.CurrentModuleDeserializer.deserializeIrSymbol(IrModuleDeserializer.kt:213)
        at org.jetbrains.kotlin.backend.common.serialization.CurrentModuleWithICDeserializer.deserializeIrSymbol(IncrementalCompilationSupport.kt:95)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrDeserializerForFile.deserializeIrSymbolData(KotlinIrLinker.kt:388)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrDeserializerForFile.deserializeIrSymbol(KotlinIrLinker.kt:404)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeIrSymbolAndRemap(IrFileDeserializer.kt:144)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeIrFunction(IrFileDeserializer.kt:1249)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeDeclaration(IrFileDeserializer.kt:1450)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeIrClass(IrFileDeserializer.kt:1085)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeDeclaration(IrFileDeserializer.kt:1449)
        at org.jetbrains.kotlin.backend.common.serialization.IrFileDeserializer.deserializeDeclaration(IrFileDeserializer.kt:1491)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrDeserializerForFile.deserializeDeclaration(KotlinIrLinker.kt:288)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrDeserializerForFile$FileDeserializationState.processPendingDeclarations(KotlinIrLinker.kt:276)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$IrDeserializerForFile.deserializeAllFileReachableTopLevel(KotlinIrLinker.kt:459)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$BasicIrModuleDeserializer$ModuleDeserializationState.processPendingDeclarations(KotlinIrLinker.kt:101)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker$BasicIrModuleDeserializer.deserializeReachableDeclarations(KotlinIrLinker.kt:219)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.deserializeAllReachableTopLevels(KotlinIrLinker.kt:529)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.findDeserializedDeclarationForSymbol(KotlinIrLinker.kt:548)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.getDeclaration(KotlinIrLinker.kt:586)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGeneratorKt.getDeclaration(ExternalDependenciesGenerator.kt:60)
        at org.jetbrains.kotlin.ir.util.ExternalDependenciesGenerator.generateUnboundSymbolsAsDependencies(ExternalDependenciesGenerator.kt:50)
        at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateUnboundSymbolsAsDependencies(ModuleGenerator.kt:69)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:86)
        at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateModuleFragmentWithPlugins(klib.kt:344)
        at org.jetbrains.kotlin.ir.backend.js.KlibKt.generateKLib(klib.kt:170)
        at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:194)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:74)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
        at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:178)
        at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:75)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:286)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:111)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:74)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:65)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:550)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:96)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1747)
        at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

However the issue with reproducing this bug is because it is very brittle, after I changed the `Aside` signature a bit (I literally just added the return types) the issue went away, even after reverting to the old implementation of the `Aside` tag.

So for now this is a bug report that isn't reproducible, yet... 😭 But I still decided to report it because who knows, maybe someone else is able to reproduce it.

**Comment by MrPowerGamerBR** [comment]
I had this exception again after I added a instance check like this:

```kotlin
                ServerIcon(
                    "https://cdn.discordapp.com/avatars/123170274651668480/8bd2b747f135c65fd2da873c34ba485c.png?size=2048",
                    routingManager,
                    "/users",
                    this@SidebarsView is UserHomeView
                )
```

Using `./gradlew :frontend:clean` fixed the issue, so I think it is the compiler getting confused somewhere.

**Comment by eymar** [comment]
Hi @MrPowerGamerBR 
I tried to reproduce it using the code sample you provided and it worked.

Was there anything else special in `leftSidebarContents` function?
I believe nothing unusual, although do you mind adding its code here? 

And thanks a lot for reporting this. Even though it's not easy to reproduce we'd like to learn about such unusual cases.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5427">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
